### ISSUE TITLE
Search function stopped working

### ISSUE THREAD

**Issue by sukhysall** [DobyTang/LazyLibrarian#332] opened 2016-04-02 08:03 UTC
Just updated to ee2b7e6cfc94b815799bb8846c79496683321255 and just noticed something odd. The search function is no longer working? I just tried searching for an author and when I enter, it doesn't go away and search. Nothing in the log either like it doesn't recognise the Enter key or something?

**Comment by sukhysall** [comment] 2016-04-02 08:06
Added a new author by way of importing a book and doing a library scan. Can confirm it's the search prompt in the top right corner that doesn't work

**Comment by philborman** [comment] 2016-04-02 19:53
Strange, seems to be working here. Can't see why that function should have changed in the last commits. Can you try running from a terminal with debug on and see if anything shows up?

**Comment by aldrouil** [comment] 2016-04-02 20:10
Having the same issue. Strange thing is, I can search for and add books from the terminal when just straight up running the python script.

**Comment by aldrouil** [comment] 2016-04-02 20:17
Changing the UI to the bookstrap option allows me to search for books again.

**Comment by philborman** [comment] 2016-04-02 20:20
That's great, thanks. Just the clue I needed :-)
I can reproduce it here now, so should be easy to fix.

**Comment by philborman** [comment] 2016-04-03 14:30
Well, found a fix for it, can't pretend I understand what's going on though.
In data/interfaces/default/base.html, line 130
<input type="text" value="" onfocus="if(this.value==this.defaultValue) this.value='';" name="name" placeholder="Title / Author / ISBN" class="deletable" id="searchbox" />
it seems not to like the class="deletable" id="searchbox" part any more. If you delete that from the end of the line, just leaving the closing >  it all works again.
Strange thing is, as far as I can see this hasn't been changed?

I have submitted a patch to my git repository, but can't get it into the master DobyTang one for a week as nncrypted is away.  You can grab the file from my git, or edit it yourself for now ;-)

**Comment by nncrypted** [comment] 2016-04-03 20:35
The resort has good WiFi in my room so submit your pull request and I'll merge it.

**Closed** 2016-04-23 17:52 UTC
