### ISSUE TITLE
Deluge + Jackett magnet link not working correctly

### ISSUE THREAD

**Issue by Matthijz98** [DobyTang/LazyLibrarian#1638] opened 2018-10-20 14:28 UTC
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
ed11cc7c18d514c48a57832951cace63494da7e5
### Operating system used (windows, mac, linux, NAS type)
Docker
### Interface in use (default, bookstrap)
Bookstrap
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
DockerHub
### Relevant debug log with api keys and any passwords redacted

I use a Docker container with Deluge to download this works great with the build in Providers.
But a added a few using Jackett but when the result is past to Deluge is goes wrong.
The link that is past to Deluge is not working when i open the link i my browser (chrome) my desktop version of QBitTorrent does pick up the right magent URL

History:

Title: The Adjustment by Suzanne Young epub
Type: torznab eBook
Date: 2018-10-20 14:11:24
Size: 2.2 Mb
Provider: 1337x
Downloader: None
DownloadID: None
URL: http://*jacketIP*:9117/dl/1337x/?jackett_apikey=*apikey*=Q2ZESjhGTHF0a3RqM1VWS3VOSkdaME9FM215dXdFV09UNkJIbDdWTmZtUkY1RnZtUG9lRWNSUmdxN0NsMlZhdEFtM3Z0Z1NKVUIyazZ0b3lBQU9ZWnZaZmZnMzN1RjlKakwzVHFCcDVqOGE1a2xGdUxJcExQMU02dWpoZFZmRXI4SDRvN0M4cThweDZKQW5VVDVTYjctSGsxRDRIYVhJNDQ1LU0zeVZHU0JoLU1LWWdPNVRPakROcmstZGpmcTJxT0tjbEtPdWJwS3JvVUZnaXFoVGEyZjlFUEdj&file=The+Adjustment+by+Suzanne+Young+.epub
Error: Deluge returned status None 

Log:

2018-10-20 14:23:55 | ERROR | SEARCHBOOK | deluge.py | addTorrent | 165 | Deluge returned status None
2018-10-20 14:23:55 | ERROR | SEARCHBOOK | deluge.py | _add_torrent_magnet | 463 | Deluge: Adding magnet failed: Is the WebUI running?
2018-10-20 14:23:55 | DEBUG | SEARCHBOOK | deluge.py | addTorrent | 53 | Deluge: Got a magnet link: magnet:?xt=urn:btih:312E7CD1F21B666B258A076A37E11CFEFE4EFCAC&dn=The+Adjustment+by+Suzanne+Young+.epub&tr=UDP:%2F%2FTRACKER.LEECHERS-PARADISE.ORG:6969%2FANNOUNCE&tr=udp:%2F%2Ftracker.zer0day.to:1337%2Fannounce&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969%2Fannounce&tr=udp:%2F%2Fcoppersurfer.tk:6969%2Fannounce
2018-10-20 14:23:55 | DEBUG | SEARCHBOOK | downloadmethods.py | TORDownloadMethod | 419 | Sending The Adjustment by Suzanne Young epub url to Deluge
2018-10-20 14:23:55 | DEBUG | SEARCHBOOK | downloadmethods.py | calculate_torrent_hash | 540 | Torrent Hash: 312E7CD1F21B666B258A076A37E11CFEFE4EFCAC
2018-10-20 14:23:55 | DEBUG | SEARCHBOOK | downloadmethods.py | TORDownloadMethod | 278 | Redirecting to magnet:?xt=urn:btih:312E7CD1F21B666B258A076A37E11CFEFE4EFCAC&dn=The+Adjustment+by+Suzanne+Young+.epub&tr=UDP:%2F%2FTRACKER.LEECHERS-PARADISE.ORG:6969%2FANNOUNCE&tr=udp:%2F%2Ftracker.zer0day.to:1337%2Fannounce&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969%2Fannounce&tr=udp:%2F%2Fcoppersurfer.tk:6969%2Fannounce
2018-10-20 14:23:55 | DEBUG | SEARCHBOOK | downloadmethods.py | TORDownloadMethod | 275 | Requests exception: No connection adapters were found for 'magnet:?xt=urn:btih:312E7CD1F21B666B258A076A37E11CFEFE4EFCAC&dn=The+Adjustment+by+Suzanne+Young+.epub&tr=UDP:%2F%2FTRACKER.LEECHERS-PARADISE.ORG:6969%2FANNOUNCE&tr=udp:%2F%2Ftracker.zer0day.to:1337%2Fannounce&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969%2Fannounce&tr=udp:%2F%2Fcoppersurfer.tk:6969%2Fannounce'
2018-10-20 14:23:54 | DEBUG | SEARCHBOOK | downloadmethods.py | TORDownloadMethod | 249 | Fetching http://192.168.178.11:9117/dl/1337x/?jackett_apikey=8sr0jllj2u8l33499p1h2huwp5uo26w9&path=Q2ZESjhGTHF0a3RqM1VWS3VOSkdaME9FM216TnI4S05NZlBCeFZjbDBGZTVlczNoblFGRnh0aVFGcUpOb3I3aTQ1TWZqbmNzZmgxYnFiVWRsd1dWYy1UcURnY0V0OS1zSFA2bDZOMFoyOUNQSzN6RFZsRDRhOWE5S0Jla0dSRVJsbmdiVjFHZ2RVZHpKSXh4aHpvcDFNYTdWY1VDMVo4ZVlCdFJPbzZ5MHdScTRiV242b0lnZnhtdzVIenVfcFZESlgtUHZqYTJ1VmRzTVU3QldzUUhpb3hFU0NJ&file=The+Adjustment+by+Suzanne+Young+.epub

**Comment by philborman** [comment] 2018-10-20 14:47
Can you check your config and whether deluge is working, the log shows
 Deluge: Adding magnet failed: Is the WebUI running?
which usually means your config is wrong or deluge isn't running, does the deluge test button work?

**Comment by Matthijz98** [comment] 2018-10-20 14:51
![chrome_2018-10-20_16-49-40](https://user-images.githubusercontent.com/17087153/47256975-47338680-d488-11e8-95dd-a0c25b83b4eb.png)
Yes delug works just fine.

**Comment by philborman** [comment] 2018-10-20 15:06
ok, can you try a magnet link with lazylibrarian loglevel set to 16 (much more messages from deluge)
Thanks

**Comment by Matthijz98** [comment] 2018-10-20 15:13
2018-10-20 15:10:35 | INFO | SEARCHBOOK | searchbook.py | search_book | 341 | Search for Wanted items complete, found 0 books
-- | -- | -- | -- | -- | -- | --
2018-10-20 15:10:35 | ERROR | SEARCHBOOK | deluge.py | addTorrent | 165 | Deluge returned status None
2018-10-20 15:10:35 | ERROR | SEARCHBOOK | deluge.py | _add_torrent_magnet | 463 | Deluge: Adding magnet failed: Is the WebUI running?
2018-10-20 15:10:35 | DEBUG | SEARCHBOOK | deluge.py | _add_torrent_magnet | 461 | Deluge: Response was None
2018-10-20 15:10:35 | DEBUG | SEARCHBOOK | deluge.py | _add_torrent_magnet | 456 | {"id": 2, "result": null, "error": null}
2018-10-20 15:10:35 | DEBUG | SEARCHBOOK | deluge.py | _add_torrent_magnet | 455 | Status code: 200
2018-10-20 15:10:35 | DEBUG | SEARCHBOOK | deluge.py | _add_torrent_magnet | 444 | Deluge: Adding magnet
2018-10-20 15:10:35 | DEBUG | SEARCHBOOK | deluge.py | addTorrent | 53 | Deluge: Got a magnet link: magnet:?xt=urn:btih:A3232D041D9203F6E69DD8652EFC0893E6B9B9FC&dn=A+Hero+of+France+A+Novel+by+Alan+Furst+.epub&tr=UDP:%2F%2FTRACKER.LEECHERS-PARADISE.ORG:6969%2FANNOUNCE&tr=udp:%2F%2Ftracker.zer0day.to:1337%2Fannounce&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969%2Fannounce&tr=udp:%2F%2Fcoppersurfer.tk:6969%2Fannounce
2018-10-20 15:10:35 | DEBUG | SEARCHBOOK | downloadmethods.py | TORDownloadMethod | 419 | Sending A Hero of France A Novel by Alan Furst epub url to Deluge
2018-10-20 15:10:35 | DEBUG | SEARCHBOOK | downloadmethods.py | calculate_torrent_hash | 540 | Torrent Hash: A3232D041D9203F6E69DD8652EFC0893E6B9B9FC
2018-10-20 15:10:35 | DEBUG | SEARCHBOOK | downloadmethods.py | TORDownloadMethod | 278 | Redirecting to magnet:?xt=urn:btih:A3232D041D9203F6E69DD8652EFC0893E6B9B9FC&dn=A+Hero+of+France+A+Novel+by+Alan+Furst+.epub&tr=UDP:%2F%2FTRACKER.LEECHERS-PARADISE.ORG:6969%2FANNOUNCE&tr=udp:%2F%2Ftracker.zer0day.to:1337%2Fannounce&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969%2Fannounce&tr=udp:%2F%2Fcoppersurfer.tk:6969%2Fannounce
2018-10-20 15:10:35 | DEBUG | SEARCHBOOK | downloadmethods.py | TORDownloadMethod | 275 | Requests exception: No connection adapters were found for 'magnet:?xt=urn:btih:A3232D041D9203F6E69DD8652EFC0893E6B9B9FC&dn=A+Hero+of+France+A+Novel+by+Alan+Furst+.epub&tr=UDP:%2F%2FTRACKER.LEECHERS-PARADISE.ORG:6969%2FANNOUNCE&tr=udp:%2F%2Ftracker.zer0day.to:1337%2Fannounce&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969%2Fannounce&tr=udp:%2F%2Fcoppersurfer.tk:6969%2Fannounce'

**Comment by philborman** [comment] 2018-10-20 15:45
Seems we are not talking to deluge properly, got response none, error none and status code 200 (ok)
What version of deluge and can you post your lazylibrarian config settings for deluge.

**Comment by Matthijz98** [comment] 2018-10-20 17:10
I use version 1.3.10 of Deluge
![2018-10-20_18-22-27](https://user-images.githubusercontent.com/17087153/47258436-5bcd4a00-d49b-11e8-8997-4e08ba511a5f.png)

**Comment by philborman** [comment] 2018-10-20 17:20
ok thanks. config looks ok, I am just downloading deluge to try it. I only have 1.2.12, I normally use transmission. Could be a bug in the deluge interface, have you tried the daemon instead of the webui just in case it makes a difference?

**Comment by Matthijz98** [comment] 2018-10-20 17:29
I will try the daemon.

**Comment by Matthijz98** [comment] 2018-10-20 17:36
When using the daemon it works better now only 2 fail.

Title: The Names They Gave Us by Emery Lord epub
Type: torznab eBook
Date: 2018-10-20 17:32:57
Size: 1.4 Mb
Provider: 1337x
Downloader: None
DownloadID: None
URL: http://192.168.178.11:9117/dl/1337x/?jackett_apikey=8sr0jllj2u8l33499p1h2huwp5uo26w9&path=Q2ZESjhGTHF0a3RqM1VWS3VOSkdaME9FM214cUx2enNYSUVnZDROMWpvVmNIMjV6VnVDQ3hwN1JfV3FLa2tIdk1Nb2hyNXM0bGlwTVRnOG14X3NiQ0s4NTRTaDI4QTVGbXlzTEQ5ckpacEZJUXpqY0VhajBubG9aV2tyZ1JFNXN5YXNWbnRxTDlqcUxPdDFaWGR4UUE2OE1UVmFWeGJKc3FXLVZwS3dnVk5RT1Jhb0ltdngwRXNDYlBuUHVYak80ODYyX185dGFWQ0w0ZzB1a3o0OHQ5ek5kSHZB&file=The+Names+They+Gave+Us+by+Emery+Lord+.epub
Error: Sending The Names They Gave Us by Emery Lord epub magnet to DelugeRPC failed

Title: A Hero of France A Novel by Alan Furst epub
Type: torznab eBook
Date: 2018-10-20 17:32:48
Size: 1.2 Mb
Provider: 1337x
Downloader: None
DownloadID: None
URL: http://192.168.178.11:9117/dl/1337x/?jackett_apikey=8sr0jllj2u8l33499p1h2huwp5uo26w9&path=Q2ZESjhGTHF0a3RqM1VWS3VOSkdaME9FM215enQ4dlFLY2VKelVJZFhIdVVWeFBOY1NUZThzcktaalhEWDBVOVl4aUdzUVR3YjU5eDZQeU55ODNJbWtZSmcyNmRjaUdCTGNmcEljNjB6UTBNdk1YaEFadGNhUi1BamJGMDQ4MDVWWllrRV9GV2plR1lZU0N0azctX0RQbkdxVzlsOHRrS1dJYWVfeXkxYVVQY2pWRlhRaDRpX1lyN1BZU2FYanItdXJqcGwzM0lOYmpOQVFHMFRvTlB1TEhlWW8w&file=A+Hero+of+France+A+Novel+by+Alan+Furst+.epub
Error: Sending A Hero of France A Novel by Alan Furst epub magnet to DelugeRPC failed

**Comment by philborman** [comment] 2018-10-20 17:52
ok, anything unusual about the magnet links for those two? Struggling to reproduce it here. Tried a couple of jackett provided downloads and hey worked fine. I don't have 1337x set up though. Unfortunately deluge doesn't give us any info back, 200/ok, no error, no id. Should get the id back.

**Comment by Matthijz98** [comment] 2018-10-20 19:10
No i really don't know what is wrong my desktop kan handel te url just fine.
But the problem is mostly fix by changing to the daemon.

**Comment by philborman** [comment] 2018-11-03 13:12
Marking as closed for now, unable to reproduce

**Closed by philborman** 2018-11-03 13:12 UTC
