### ISSUE TITLE
Unable to connect to SAB regardless of "Host" field content

### ISSUE THREAD

**Issue by realcanadrian** [DobyTang/LazyLibrarian#724] opened 2017-04-04 22:07 UTC
I have tried filling the "SABnzbd Host" field with "localhost", "127.0.0.1", my external IP, and my DuckDNS dynamic DNS name, all to no avail. Sonarr and Radarr have no issues connecting to SAB. 
### Relevant debug log with api keys and any passwords redacted:
(Hopefully this is enough detail - my Calibre library is currently importing and the log is full of LIBRARYSYNC cruft)
```
$ cat log/lazylibrarian.log | grep -v LIBRARYSYNC
04-Apr-2017 15:45:05 - DEBUG   :: WEBSERVER : Request url for <a href="http://:/api?output=json&mode=auth">SABnzbd</a>
04-Apr-2017 15:45:05 - ERROR   :: WEBSERVER : Unable to connect to SAB with URL: http://:/api?output=json&mode=auth, [Errno -2] Name does not resolve
04-Apr-2017 15:45:59 - INFO    :: WEBSERVER : Config file [/config/config.ini] has been updated
04-Apr-2017 15:46:03 - DEBUG   :: WEBSERVER : Request url for <a href="http://:/api?output=json&mode=auth">SABnzbd</a>
04-Apr-2017 15:46:03 - ERROR   :: WEBSERVER : Unable to connect to SAB with URL: http://:/api?output=json&mode=auth, [Errno -2] Name does not resolve
04-Apr-2017 15:46:06 - DEBUG   :: WEBSERVER : Request url for <a href="http://:/api?output=json&mode=auth">SABnzbd</a>
04-Apr-2017 15:46:06 - ERROR   :: WEBSERVER : Unable to connect to SAB with URL: http://:/api?output=json&mode=auth, [Errno -2] Name does not resolve
04-Apr-2017 15:47:17 - INFO    :: WEBSERVER : Config file [/config/config.ini] has been updated
04-Apr-2017 15:47:55 - DEBUG   :: WEBSERVER : Request url for <a href="http://:/api?output=json&mode=auth">SABnzbd</a>
04-Apr-2017 15:47:55 - ERROR   :: WEBSERVER : Unable to connect to SAB with URL: http://:/api?output=json&mode=auth, [Errno -2] Name does not resolve
04-Apr-2017 15:50:39 - DEBUG   :: POSTPROCESS : Checking 0 files in /home/canadrian/Downloads/complete/ebooks
04-Apr-2017 15:50:40 - DEBUG   :: POSTPROCESS : Found 2 files marked "Snatched"
04-Apr-2017 15:50:40 - INFO    :: POSTPROCESS : No snatched books/mags have been found
04-Apr-2017 15:52:44 - DEBUG   :: AUTHORUPDATE : Oldest author info is 0 days old
04-Apr-2017 15:59:51 - DEBUG   :: WEBSERVER : Request url for <a href="http://:/api?output=json&mode=auth">SABnzbd</a>
04-Apr-2017 15:59:51 - ERROR   :: WEBSERVER : Unable to connect to SAB with URL: http://:/api?output=json&mode=auth, [Errno -2] Name does not resolve
04-Apr-2017 16:00:37 - DEBUG   :: POSTPROCESS : Checking 0 files in /home/canadrian/Downloads/complete/ebooks
04-Apr-2017 16:00:37 - DEBUG   :: POSTPROCESS : Found 2 files marked "Snatched"
04-Apr-2017 16:00:37 - INFO    :: POSTPROCESS : No snatched books/mags have been found
```

**Comment by markgifford** [comment] 2017-04-04 22:45
I just noticed this too. Also installed via the same Docker image. Looks like it's failing to build the sabnzbd URL properly:

> Unable to connect to SAB with URL: http://:/api?output=json&mode=auth, [Errno -2] Name does not resolve

**Comment by philborman** [comment] 2017-04-05 07:39
Are the host and port settings in config correct for sab ? If so can you check if the setting.ini file has the right values ?

**Comment by philborman** [comment] 2017-04-05 10:29
Seems to be working fine with the bookstrap interface, just not with the default one. For now I suggest switching to the bookstrap interface until I can figure out what's broken.

**Comment by markgifford** [comment] 2017-04-05 13:32
@philborman yeah the correct values are being put into config.ini by the config form. It looks like this is an issue with a theme or something, like you said - I just confirmed the sabnzbd functionality actually works fine despite the "test connection" not working.

> For now I suggest switching to the bookstrap interface 

Don't want to sidetrack but I couldn't find a way to do that via the UI - will carry on looking.

**Comment by philborman** [comment] 2017-04-05 14:36
Found the problem and hopefully fixed it, just need to do a bit more
testing.

Bookstrap interface is selected from the first config tab.

**Comment by philborman** [comment] 2017-04-05 19:43
OK should be fixed now

**Comment by realcanadrian** [comment] 2017-04-05 20:25
Excellent, thank you. I also noticed after I posted that the Bookstrap interface didn't throw an error, but despite saying some items were "snatched", I wasn't seeing them in the SAB queue. I looked again this morning though and they did end up on SAB - I guess there's a delay of some kind?

How do I update my docker container (linuxserver/lazylibrarian) with the fixes? Just pull again, or do I need to add a tag to pull a particular image or something?

**Comment by philborman** [comment] 2017-04-05 20:30
Docker updates their image overnight I think.
Not sure if the lazy librarian internal update mechanism works inside
Docker,  might be worth a try. Check Version button on the configuration
page might offer an upgrade option

On Wed, 5 Apr 2017, 22:25 realcanadrian, <notifications@github.com> wrote:

Excellent, thank you. I also noticed after I posted that the Bookstrap
interface didn't throw an error, but despite saying some items were
"snatched", I wasn't seeing them in the SAB queue. I looked again this
morning though and they did end up on SAB - I guess there's a delay of some
kind?

How do I update my docker container (linuxserver/lazylibrarian) with the
fixes? Just pull again, or do I need to add a tag to pull a particular
image or something?

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/DobyTang/LazyLibrarian/issues/724#issuecomment-291986312>,
or mute the thread

**Comment by Hughlander** [comment] 2017-04-07 17:32
The linuxserver.io's Docker instance can be updated just by using the interior website, or you can wait till they do an update and fetch it.  (Just checking they haven't updated their image for the past 7 days.)

I rolled my own image though using theirs as a base and then adding glibc and calibredb.

**Comment by realcanadrian** [comment] 2017-04-07 17:36
That's a good point - I've been noticing failures that state they can't find calibredb, even though I've triple-checked the path. So I need to add calibredb to the image?

- Adrian

**Comment by Hughlander** [comment] 2017-04-07 17:52
It's much more complicated than that since as I mentioned Alpine doesn't even by default use a compatible libc.  If I get time over the weekend I'll push my Dockerfile.

**Closed** 2017-04-20 11:44 UTC
