### ISSUE TITLE
database integrity error: unique constraint failed: authors.AuthorID  perhaps similar to issue 1178?

### ISSUE THREAD

**Issue by Hydro-guy** [DobyTang/LazyLibrarian#1444] opened 2018-05-30 22:39 UTC
Author has several pseudonyms.  John Creasey writing as Anthony Morton or J.J. Marric .  

Not sure of how to deal with this.

30-May-2018 15:25:44 - INFO :: AUTHORUPDATE : common.py:authorUpdate:509 : Starting update for John Creasey (jj Marric)
30-May-2018 15:25:44 - DEBUG :: AUTHORUPDATE : common.py:authorUpdate:511 : Oldest author info (John Creasey (jj Marric)) is 85 days old
30-May-2018 15:25:44 - DEBUG :: AUTHORUPDATE : importer.py:addAuthorToDB:149 : Updating author John Creasey (jj Marric)
30-May-2018 15:25:44 - DEBUG :: AUTHORUPDATE : cache.py:get_cached_request:231 : Got error response for https://www.goodreads.com/author/show/7948377.xml?key=ckvsiSDsuqh7omh74ZZ6Q: Response status 404: not_found
30-May-2018 15:25:44 - DEBUG :: AUTHORUPDATE : gr.py:get_author_info:287 : Error requesting author info
30-May-2018 15:25:44 - WARNING :: AUTHORUPDATE : importer.py:addAuthorToDB:182 : Nothing found for 7948377
30-May-2018 15:25:44 - DEBUG :: AUTHORUPDATE : gr.py:find_author_id:250 : Searching for author with name: John Creasey (jj Marric)
30-May-2018 15:25:44 - DEBUG :: AUTHORUPDATE : common.py:gr_api_sleep:144 : GoodReads sleep 0.466, total 0.466
30-May-2018 15:25:45 - DEBUG :: AUTHORUPDATE : cache.py:get_cached_request:193 : CacheHandler: Storing XML a9bf795eac4a23e72a3d3ef3f2786db8 for https://www.goodreads.com/api/author_url/John%20Creasey%20%28jj%20Marric%29?key=ckvsiSDsuqh7omh74ZZ6Q
30-May-2018 15:25:45 - DEBUG :: AUTHORUPDATE : gr.py:get_author_info:305 : [J.J. Marric] Processing info for authorID: 378102
30-May-2018 15:25:45 - DEBUG :: AUTHORUPDATE : importer.py:addAuthorToDB:210 : Now updating author: John Creasey (jj Marric)
30-May-2018 15:25:45 - ERROR :: AUTHORUPDATE : database.py:action:79 : Database Integrity error: UNIQUE constraint failed: authors.AuthorID

30-May-2018 15:25:45 - ERROR :: AUTHORUPDATE : database.py:action:80 : Failed query: [UPDATE authors SET Status = ?, DateAdded = ?, AuthorBorn = ?, AuthorLink = ?, AuthorID = ?, AuthorDeath = ?, AuthorImg = ? WHERE AuthorName = ?]
30-May-2018 15:25:45 - ERROR :: AUTHORUPDATE : database.py:action:81 : Failed args: [['Loading', '2018-05-30', None, 'https://www.goodreads.com/author/show/378102.J_J_Marric', '378102', None, 'https://s.gr-assets.com/assets/nophoto/user/u_200x266-e183445fd1a1b5cc7075bb1cf7043306.png', u'John Creasey (jj Marric)']]
30-May-2018 15:25:45 - ERROR :: AUTHORUPDATE : importer.py:addAuthorToDB:319 : Unhandled exception in addAuthorToDB: Traceback (most recent call last):
  File "C:\lazylibrarian\lazylibrarian\importer.py", line 230, in addAuthorToDB
    myDB.upsert("authors", newValueDict, controlValueDict)
  File "C:\lazylibrarian\lazylibrarian\database.py", line 124, in upsert
    self.action(query, list(valueDict.values()) + list(keyDict.values()))
  File "C:\lazylibrarian\lazylibrarian\database.py", line 48, in action
    sqlResult = self.connection.execute(query, args)
IntegrityError: UNIQUE constraint failed: authors.AuthorID

**Comment by philborman** [comment] 2018-05-31 07:29
Similar to 1178 but not the same. We assume authorid is unique, which is needed for allocating books to the right author. Goodreads has 3 different authorids for John Creasey  Anthony Morton and J.J. Marric which is ok. I will look into this, might not be straightforward.

**Comment by philborman** [comment] 2018-05-31 14:45
Wow, he's got about 20 pseudonyms!
The problem isn't the pseudonyms as such, it's that goodreads has tried to rationalise their entries a bit. Seems they used to have at least one book by author John Creasey (jj Marric) as authorid 7948377  but they have moved him so now when we search for that authorid we get Response status 404: not_found
We then search for his name and are given authorid 378102  and as we can't have two authorids for the same author we fall over.  I think someone entered one of his books as if it was a different author and then goodreads has realised and merged 378102 and 7948377 together.

Fix looks fairly easy, just move all our database entries to point to the new authorid. I tried faking it by setting an imaginary authorid for an author and then updating the author and it corrected ok, so should be fixed in the next release.

**Closed** 2018-06-08 16:31 UTC
Labels: fixed
