### ISSUE TITLE
Calibri Auto Add Feature

### ISSUE THREAD

**Issue by mccorkled** [DobyTang/LazyLibrarian#1052] opened 2017-10-03 00:49 UTC
I tried a feature request with the guys over at https://github.com/janeczku/calibre-web/issues/344 and they weren't having it. One of them suggested that LL had a feature which could auto add books from a directory to a Calibre database. I cannot seem to get this to work because I cannot figure out if it's even possible. 

After LL snatches the books, sends them to SAB, post processes them, and then places them into /books, it would be great if these got automatically added to the Calibra database on the NAS located at /calibre/books 

Calibre-web is a really nice UI but it lacks an auto add feature and instead makes you upload each book individually which is simply not feasible for larger collections. 

Please let me know if this is possible, or maybe already even a thing and I just don't understand it. 

Thanks!

**Comment by philborman** [comment] 2017-10-03 08:42
Duplicate of #1040 
See the wiki for calibre integration details, there are lots of options depending on what you want to do.
https://github.com/DobyTang/LazyLibrarian/wiki/Configuration

**Closed by philborman** 2017-10-03 08:42 UTC

**Comment by kianrafiee** [comment] 2018-09-02 06:32
That link takes you to a blank page.

**Comment by kianrafiee** [comment] 2018-09-02 06:34
I see the page after browsing to wiki but that deals with calibre server and not calibre/web and would result in no syncing with calibre-web.

**Comment by philborman** [comment] 2018-09-02 07:28
Updated the link, thanks.
I don't know what calibre web needs, there are already several options for talking to calibre, do none of them work? Presumably calibre web still uses the calibre database, does it have a running calibre-server, or does it talk to the database direct?

**Comment by kianrafiee** [comment] 2018-09-02 07:31
Since I use LL as a tool to download new books, it would need to sync with calibre-web(proffered) or calibre-server. I love calibre-webs features and interface for a library of my books. LL is strictly for finding books. LL can communicate with both the calibredb file or calibre-server.

**Comment by philborman** [comment] 2018-09-02 08:05
To talk to the calibre database you just need to put the path to the calibredb program in lazylibrarian, lazylibrarian can use it to add books to the database file. The calibre database location is normally the lazylibrarian eBook Library Folder. This only works if calibre and lazylibrarian are on the same machine.

Calibre server is a more complicated option, but works across different machines, and exactly how it's used depends on the version of calibre.

**Comment by philborman** [comment] 2018-09-02 08:27
Does calibre-web have it's own database file? If calibre web is using the calibre database file it should be ok, but if it has it's own then we need some way of telling calibre-web about changes.

**Comment by kianrafiee** [comment] 2018-09-02 08:32
Indeed, it seems to have its own db. Here is the discussion on the issue over their: https://github.com/janeczku/calibre-web/issues/344#issuecomment-417913528

**Comment by kianrafiee** [comment] 2018-09-02 08:35
Wait actually all I did was insert my calibre db file into calibre web. Huh...

**Comment by philborman** [comment] 2018-09-02 08:46
Calibre itself needs the calibre database (metadata.db) to be in the same folder as the books, top level, alongside the author names. LazyLibrarian calls this the "eBook Library Folder" and we use calibredb to talk to the database in that folder. calibredb is part of calibre, so it knows the database structure, we just tell it "here is a folder with a new book"

If you are running inside dockers, the dockers need to be able to share the eBook Library Folder.
There is a lazylibrarian docker that includes calibredb which makes it a bit simpler, it's linked to on the lazylibrarian git page. 

Hopefully calibre-web notices if calibre installs or removes a new book?  If not it's a fairly major omission that needs rectifying at their end. As far as the calibre database is concerned, it doesn't care who we are since we used calibredb to make the changes

**Comment by kianrafiee** [comment] 2018-09-02 08:49
I think this is on me. But can’t find out till tomorrow. I need to check if my mount for the LL container’ book folder is the same as calibre-web’s one. I suspect it may not be anymore and at that time I had no books in LL :x

**Comment by kianrafiee** [comment] 2018-09-02 08:49
Will update you tomorrow.

**Comment by kianrafiee** [comment] 2018-09-02 19:05
Yep! It was user error. I didn't realize I changed the book folder for LL. It wasn't the one with the metadata file used by calibre-web(and calibre for that matter). So far its slowly importing books and I am pleasantly surprised at the exceptional sorting/organizing of files. 

Only thing to check last is whether calibre-web will see some books I never uploaded to it but that are in the books folder and being processed by LL shortly.

**Comment by kianrafiee** [comment] 2018-09-02 19:06
And on that note, I believe their should be some documentation added to LL and Calibre-web so other users are aware of the inherent cross-syncing of the two apps. I spent way too much time fixing a problem that never was. I blame myself but google searches made it seem like this _was_ a problem. No bad on you or anyone else. Just my suggestion.

**Comment by philborman** [comment] 2018-09-02 19:27
Yes, documentation is definitely a problem with lazylibrarian, a few people have offered to help with it in the past year or two, but nothing ever materialised. Maybe I will get around to it myself eventually.

**Comment by kianrafiee** [comment] 2018-09-02 19:28
I might have some time to just put a blurb about this. I will also ask the calibre-web repo if I can do the same.

**Comment by kianrafiee** [comment] 2018-09-02 21:48
Strange, LL sorted and renamed book files. And I am pretty sure that means its in the calibre db file. But Calibre-web has not seen anything. I'm wondering if LL actually wrote to the db file or not....

**Comment by kianrafiee** [comment] 2018-09-03 01:07
Alright can confirm that LL did not in fact update the calibre db file with new books it has added to its own database. That is why calibre-web cannot see new books added. But the books LL grabbed are sorted and organized/renamed in my books folder fine now. Not sure whats going on since the debug log shows nothing in particular with log level 2.

**Comment by mccorkled** [comment] 2018-09-03 01:53
Are you available tomorrow evening Eastern time for a Team Viewer session? I should be able to get this sorted for you.

**Comment by kianrafiee** [comment] 2018-09-03 02:30
I'm pretty sure I should be, yes.

Here is an update:

I am now using this container: https://github.com/Thraxis/docker-lazylibrarian-calibre

It combines LL and calibre(with calibredb) so they can cross-communicate.

Anyway, I have the calibredb path set in LL but I do not see LL adding books automatically from the db file even with access to calibredb. It seems post processing still iterates through every folder to find new books in the books folder. The debug log shows no mention of calibredb.

**Comment by mccorkled** [comment] 2018-09-03 02:51
I can 100% solve this for you tomorrow. I have the exact setup you want. I’ve been writing tutorials on this thing but been really busy with school. Email me direct at Dustin.mccorkle@gmail.com

**Comment by kianrafiee** [comment] 2018-09-03 02:56
Great, sounds good. Emailed.
