### ISSUE TITLE
Sort by Downloaded in first digit order, not proportion

### ISSUE THREAD

**Issue by rutskiuk** [DobyTang/LazyLibrarian#729] opened 2017-04-14 20:10 UTC
Previously raised issue #717 #725 

Hi there, I've still not seen an update that fixes this issue, the sort order is still sorting by the first digit. I'm sorry, I did see you said to run the bootstrap but I'm still on the master release:

![image](https://cloud.githubusercontent.com/assets/25068977/25054693/90ea9886-2156-11e7-86c1-9bb512ba2ebf.png)

Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: a7b94179ae0971a8145a662dc439a923cf77a0a5

**Comment by philborman** [comment] 2017-04-14 20:33
Bizarre. Still working on bookstrap but not on the default interface. It was working fine, not sure why it's not again. The fix was a missing reference to js/natural.js in index.html an that's still there. I'll take another look. Sorry.

**Comment by philborman** [comment] 2017-04-15 18:31
Ok, seems the problem is that the natural sort addon does not work with the older version of the datatables library that the default interface uses. The default interface is on 1.8.1 and bookstrap interface is on 1.10..13

I have a working version of the author page which uses the new datatables version and it sorts correctly but the styling is different. I haven't yet figured out how to make it look similar, so I am wondering whether to move the whole default interface to the new datatables version so it looks consistent. 

The new version of the index page is attached if you want to try it, just drop it in place of the existing version. Feedback would be appreciated

**Comment by philborman** [comment] 2017-04-20 11:43
Should be fixed in latest version. We have two "natural sort" libraries now, different for each interface. A bit messy, but it works ;-)

**Comment by philborman** [comment] 2017-04-24 16:56
Can you confirm if this is now working for you (seems to be here). If so I will close the ticket. Thanks.

**Comment by rutskiuk** [comment] 2017-04-24 23:07
Working perfectly now, thank you!

**Closed** 2017-04-25 06:57 UTC
