### ISSUE TITLE
Reload after update goes to wrong url if webroot is set

### ISSUE THREAD

**Issue by claym** [DobyTang/LazyLibrarian#452] opened 2016-09-01 14:46 UTC
Pretty small issue actually. 

I have a web root specified, but after I update, it goes to / instead of /lazylibrarian.

**Comment by philborman** [comment] 2016-09-01 16:06
sorry, I have no idea how to fix that. Restart code looks like it restarts from the beginning, so should reload all the config values

**Comment by claym** [comment] 2016-09-20 02:22
Yeah, same behavior on restart.

It does pick up the right root - it shows it in the config values.

However I can't verify in logs - every time I set it to 4 and restart, it resets the value to 0 :D

**Comment by philborman** [comment] 2016-09-20 19:57
ok, I can reproduce it, that's the first step.
Headphones doesn't behave this way, and much of lazylibrarian code was
inherited from headphones, so should be able to track it down...

**Comment by philborman** [comment] 2016-09-23 15:14
Getting a bit nearer. 
Seems to work fine here with default theme,  only errors on Bookstrap theme. 
Just need to figure out what the difference is. 
Are you running on default interface?

**Comment by philborman** [comment] 2016-09-24 19:16
Think I've fixed this now, combination of a typo in the bookstrap theme update page and an upgraded cherrypy library.   Can you check it and confirm it works for you. If so we can close this ticket. Thanks.

**Closed** 2016-10-03 13:18 UTC
