### ISSUE TITLE
Add support for rutorrent/rtorrent

### ISSUE THREAD

**Issue by mlg9000** [DobyTang/LazyLibrarian#477] opened 2016-09-16 21:04 UTC
This is a popular torrent client and should be supported.

**Comment by mlg9000** [comment] 2016-09-29 07:36
So a little background on my setup first:

I use rtorrent for sickrage, couchpotato, and a few other things (hopefully this too).  I use labels and specify a download directory for each, along with the auto move feature, so that when downloads are complete they all get auto sorted in sub directories based on what they are so these apps can pick them up for post processing accordingly.  

I've tested both the magnet->torrent blackhole conversion and the rtorrent downloader you added.  The magnet->torrent conversion doesn't seem to work at all as the torrents I tested so far have failed.  The rtorrent stuff sort of works (with auth) but there are some weird issues with it so far:

Most of the torrents don't actually load and show zero seeds.  I'm note sure if this is a provider issue or not as I've not tested that yet.

For the torrents that do load, they seem to download a meta file, which oddly gets automoved into my lazy librarian specific download directory, then stops the torrent.  When I start the torrent manually it usually downloads the correct file, but to the rtorrent default download directory.  I have no idea how it even picks up the librarian specific download directory in the first place, as there is no option to set a download directory and/or label, which is a feature the rtorrent downloader would need to have to do that. (request for that to be added).

Post processing does not work. I suspect this is just because it has no idea where to find completed downloads at and there doesn't seem to be a place in the config to tell it to look.  The black hole downloader has this setting, so if I enable that and move files into that directory post processing seems to work.

**Comment by philborman** [comment] 2016-09-29 11:12
Thanks for the feedback. Seems there is still a bit of work to do. Unfortunately I don't have a working rtorrent server here, always seems to be unable to connect to trackers so I guess it's a rtorrent.rc issue at my end.  

The magnet to torrent conversion is based on the bash code here 
http://snarvaez.com.ar/libertad/index.php/2013/05/10/download-magnet-links-with-rtorrent-from-command-line/
Tried it with a magnet link, we produce the same output as the bash script (all the script does is add a simple header to the magnet). The converted torrent works with deluge and transmission, and is loaded by rtorrent. Since your feedback I have tried it with a few more magnets,  and it seems to work fine with some and not others. Not sure why yet, maybe seeders or different indexers?  Not too crucial as if we can get rtorrent working properly we won't need to convert. I will remove it for now.

The news that sickrage works is useful. That's a fork of sickbeard and much of lazylibrarian code is based on sickbeard and headphones (but sickbeard and headphones don't use rtorrent either)

Had a quick look at sickrage rtorrent code, seems they use set_custom1 to pass a label to rtorrent, and they use set_directory where I'm using set_directory_base. Other than that we're pretty much on the right track.

The meta file gets put in your lazylibrarian  specific download directory because we tell it to. It's configured in the downloaders config tab, last entry. All downloaders are expected to drop their books into here, and that's where the postprocessor looks. rtorrent uses our lazylibrarian directory for the torrent file, and I think deletes it once the download completes?

Couldn't find anything about labels in the rtorrent xmlrpc details here
https://github.com/mdevaev/emonoda/wiki/rTorrent-XMLRPC-Reference
but now I know sickrage uses custom1 I will do the same. I guess you have something in rtorrent.rc that moves the completed download to a different download_dir depending on custom1
Do you pass it a full directory, or just the last part?  ie for transmission I send "/home/phil/ebooks"
but for deluge I just send the label "ebook" 

As for the non-loading or zero seeds issue, I think that's either genuinely no seeds, a broken magnet link, or an rtorrent or network issue. Once we've sent the torrent or magnet across and it's appeared in the main view we just wait for the download to complete. In theory we check the number of seeders, but we are relying on the torrent provider for the info, which may not be correct. I think as long as the details have arrived at rtorrent, the lazylibrarian code is probably ok.

I will add labels and change set_directory_base to just set_directory same as sickrage. Maybe then you could try again and report back. Much easier if you have a working rtorrent server :-)

**Comment by philborman** [comment] 2016-09-29 18:22
ok, added labels, force download directory if no label, magnet2torrent using libtorrent (if available).
magnet2torrent works on all the magnets I've tried, deluge and transmission happy.
Rtorrent interface now looks much like the sickrage one, so should be better.

**Comment by mlg9000** [comment] 2016-09-29 19:50
Ok,

Slightly different behaviour with the rtorrent downloader.  Now when it loads torrents it creates hash.meta torrents /with the label correctly set.  When it finishes downloading the torrent files from the magnets that have just been loaded  either the name of the torrent changes to the correct file, or it stays the same (hash.meta) and the torrent stops and the label is lost.  No torrent files are being placed in my downloads directory as well (good).  If I manually start the stopped torrents it downloads the files and puts them in the default download directory, not where I've told LazyLibrarian to expect them.  That's sort of expected because there is no option to set "Downloaded files location" (aka Sickrage).  The label doesn't work the way I think you assumed, it's simply a tag and doesn't specify where a downloaded file gets placed.  Labels are useful for setting the correct ratio group and a bunch of other things however. Also, the "Downloaded files location" can (and in my case does) differ from where LazyLibrarian "Directory" is. So the flow works like this:

1. Load the torrent, set a ratio based on the label, and a "Downloaded files location" (example /torrents/active/books, a sub directory within the default /torrents/active)
2. Torrent finishes downloading/seeding, automove in rtorrent moves the files to a completed folder and removes the torrent.  Automove just moves everything that's done from /torrents/active to /torrents/complete, preserving the directory structure (books dir)
3. Post processing looks for files in "Directory" (/torrents/complete/books).

With Blackhole the label/download location is automatically set by what watch directory the torrent file is in.  None of the torrents are actually loading for me still.  I'm going to have to figure out what providers (if any) work and which don't too see if I can tell if there is something wrong.  SickRage / Couchpotato and probably Sonarr and some of the others also don't seem to handle magnets the way you are doing it here.  With Sickrage it uses iptorrents.org (there are several others too) to grab the torrent file based on the hash (see sickrage/providers/GenericProvider.py).

**Comment by philborman** [comment] 2016-09-30 17:37
Thanks for the info. I saw here that you can use labels to move finished torrents 
http://unix.stackexchange.com/questions/127382/move-completed-torrents-in-rtorrent-according-to-label
but it seems couchpotato/sickrage etc send both label and directory to rtorrent, so this latest version of lazylibrarian does the same.

I am sticking with libtorrent for magnet->torrent conversion for now. Spent quite a bit of time trying different methods today, and that seems to be the most reliable.
I used the first page of ebook results from piratebay as a source (the most current torrents, piratebay only does magnets)
The first method (http://snarvaez.com.ar/libertad/index.php/2013/05/10/download-magnet-links-with-rtorrent-from-command-line/)  always produces a torrent file, but less than 20% are valid (ie accepted by transmission and deluge)
The second method (libtorrent) produces a torrent file for 95% of magnets, and 100% are accepted by transmission/deluge
The third method (taken from sickbeard/couchpotato) only produces a torrent file 30% of the time, but 100% of those are accepted as valid by transmission/rtorrent. The rest either give "not found" or "forbidden" result codes.  Maybe video files are more successful than ebooks?

**Comment by mlg9000** [comment] 2016-09-30 19:32
It is possible to use the label to move the torrent but yuck.  Myself and I think almost everyone else uses autotools, which also handles torrents without a label (all magnet link torrents I manually click on in my browser), and that would break it.

So further testing last night and today after this update:

It turns out the torrent providers currently in LazyLibrarian all suck.  I added some RSS providers and disabled the rest and it now produces 100% working torrents on everything I tried, both to rtorrent directly and the blackhole.  The current state of what I'm seeing:

rtorrent: There is something broken with how torrents are being inserted into rtorrent.  They are all stopped, with no label, and the download directory not set.  It looks like when the magnet (it's all magnets) is inserted it does set those (it's too fast to see now) but as soon as it pulls down the torrent file all that stuff is lost. I'm going to try to find a RSS feed with torrents only as see how that fairs.  Also, there would still need to be a download directory option in rtorrent as you'd need to be able to set it differently than what's in the "directory" option in LazyLibrarian.  

blackhole:  With the RSS providers I've add this is now a 100% working option for me.  It happily creates the torrent file which gets picked up in my watch folder automatically labeling it correctly and moving it to the correct location when done.  Working rtorrent would be better, as I suspect at least a few magnet conversions won't produce working torrent files and there is no delay as with watch directories.

Thanks for your efforts so far on getting this working.

**Comment by philborman** [comment] 2016-10-01 10:26
ok, thanks for that. 
I don't think the problem is "the torrent providers currently in LazyLibrarian all suck"
as they all work fine with deluge, transmission, utorrent, qbittorrent
I think that the problem is we're not sending magnets to rtorrent correctly (but we are sending torrents to rtorrent correctly). I guess your rss feeds all return torrents rather than magnets?

Simplest way round it for now is for lazylibrarian to not send magnets to rtorrent, convert them to torrent first. Had a quick look through couchpotato sources and that's certainly what it does. 

It sounds as though rtorrent uses the magnet to fetch the torrent metadata, then stops. Maybe we can watch for the metadata arriving, then issue the label and directory options, then restart the download. Or maybe it's not worth the effort, just do it the couchpotato way.

Still not sure why you need a separate download directory for rtorrent, lazylibrarian only looks in it's own folder, like a "watch" folder in reverse. If we tell rtorrent this is where to put the completed downloads, why do we need another folder?

**Comment by mlg9000** [comment] 2016-10-02 04:54
> Still not sure why you need a separate download directory for rtorrent, lazylibrarian only looks in it's own folder, like a "watch" folder in reverse. If we tell rtorrent this is where to put the completed downloads, why do we need another folder?

Automation. Without this feature the completed torrents won't get moved to the correct location for post processing to pick them up. Rutorrent, the frontend I think nearly everyone uses as there's really nothing else remotely decent, has an autotools plugin.  Automove (one of the tools in this plugin) moves files from one directory (active torrents) to another (completed torrents) preserving the directory structure.  Setting a download directory means that the files get placed in the correct sub directory within the active downloads directory, as thus moved to the same named sub directory in completed torrents when done.  The "directory" option is set to this sub directory in completed torrents.  If you look at sickrage/couchpotato/sonarr they all have this feature.  Without this right now what happens is if you set a label the files just get dropped in the root of the active downloads directory, so are never moved to the correct dir when finished.  If you don't set a label it just uses "directory", which is where completed files go so post processing can potentially grab them before they are finished downloading. Yes you could automate moving files another way, via the label as you mentioned in a previous reply, but that breaks autotools (which is a lot more powerful).  I don't want to go down that route, neither would most other rtorrent/rutorrent users I'd imagine.  That's why sickrage/couchpotato/sonarr all have this feature.

As far as the providers go I've seeing a ton of unseeded torrents with zoogle and torrentdownloads.  TPB works it seems ok, but it's a little sketchy and unreliable these days.  KAT was awesome but obviously long gone now.  Extratrorrents and limetorrents both have books/magazines and an API it seems as they are providers for sickrage, those would be nice adds.

My primary interest with Lazy Librarian is magazines.  I already have a (nearly) fully automated magazine setup.  All my magazines are downloaded via RSS feeds being monitored via a plugin for Rutorrent which involves some sometimes complex regex rules and a schedule for each magazine.  Then I have some post processing scripts I wrote that try and determine the issue date and/or issue number for each name from the filename/directory and rename them to my naming schema, then it adds them to calibre with the appropriate tags and other information.  Some of the magazines I only want to keep around for a few months for example, so I tag them with a remove_on_date tag and a cleanup process then removes them then.  Then it sends me a push notification I have new issue of magazine X. So far that successfully downloads 95% of everything correctly, with very little things I don't want.  Post-processing however is only ~ 70%, when it can't figure it out I do it manually and drop them in another directory for re-processing (which is annoying).  The biggest issue I've had is that, unlike TV/movies/books, there doesn't seem to be any decent sources of magazine issue data online, and the people that release them are all over the place on how they name them.  I was hoping to use Lazy Librarian to do some of the heavy lifting, mostly consistently named magazines I could easily deal with.

**Comment by philborman** [comment] 2016-10-02 07:34
Sure,  I get the automation part,  what I don't get is why it needs to be a
different directory to the usual lazylibrarian one.

It looks like you either send a directory to rtorrent,  or you don't. There
is only one directory setting per torrent,  and no control over when it is
applied. No separate "incomplete directory" and "complete directory"
options to pass.

The other downloaders append .part (or similar) to incomplete files,  so
can use one directory safely.  Rtorrent doesn't.  If you don't pass a
directory to it,  it uses its own separate "incomplete"  and "complete"
folders,  which is fine,  but then how do we move the finished files to
where we want them? If we're going to use the rtorrent folders and some
sort of external "move" (maybe with rutorrent or label processing or
rtorrent rules) then you don't need a separate directory sending at all.

I suppose we could monitor rtorrent and watch for the download completing?
This is what sonarr does for tv shows,  looks very neat,  nice progress
bars. A lot of work though.

I'll ponder it for a while and in the meantime look at adding extratorrents
and limetorrents

**Comment by mlg9000** [comment] 2016-10-02 08:39
> It looks like you either send a directory to rtorrent, or you don't. There is only one directory setting per torrent, and no control over when it is applied. No separate "incomplete directory" and "complete directory" options to pass.

Correct

> The other downloaders append .part (or similar) to incomplete files, so can use one directory safely. Rtorrent doesn't. If you don't pass a directory to it, it uses its own separate "incomplete" and "complete" folders, which is fine, but then how do we move the finished files to where we want them? If we're going to use the rtorrent folders and some sort of external "move" (maybe with rutorrent or label processing or rtorrent rules) then you don't need a separate directory sending at all.

rtorrent doesn't have it's own "incomplete" and "complete" folders.  You specify a directory option in rtorrent.rc and that's it (say /rtorrent/download).  All your downloads go into that directory with their final name regardless if they are downloading, finished but seeding, or completely done and don't move.  The problem them becomes how do you sort them as you can't use that directory in Lazy Librarian.  I can set any arbitrary command to run based on events (torrent finishing) to move files, but that can't sort unless I use a label.  Not all torrents get labels, and setting that command in rtorrent.rc would break my autotools plugin in rutorrent, so that's no good.  The only other option is to set a directory when the torrent is added (/rtorrent/download/lazylib).  That way everything goes into a specific directory, as long as that directory is a subdirectory within the directory I specified in rtorrent.rc I can then use autotools in rutorrent to move completed torrents into another directory where they will still be sorted into their sub directories (/rtorrent/complete/lazylib).  Not having a working rtorrent/rutorrent setup that might be a little confusing to follow.  Having one for years though, and testing out using pretty much every tool there is that works with it, sickbeard/sickrage, couchpotato, android clients, browser extensions, etc they ALL allow you to override the download directory to whatever you want when you add a torrent.  Lazy Librarian really needs that option too, otherwise blackhole is the only way I can even use it.

> I suppose we could monitor rtorrent and watch for the download completing? This is what sonarr does for tv shows, looks very neat, nice progress bars. A lot of work though.

That's complete overkill. 

I think the best option for now is to just convert magnets to torrents an submit them to rtorrent with an optional label and optional download directory to override the default.  I've not spent much time looking though the Couchpotato code but if that's how it handles it then it's been bulletproof in terms of getting things into rtorrent appropriately and having it all work.

**Comment by philborman** [comment] 2016-10-02 09:11
ok, so are there just two options,
1. send lazylibrarian directory
2. send nothing

or do we need a third option
3. send a different directory to the lazylibrarian one

If there are just 2 options it can easily be done with a tick box
If there are 3 we need a new directory entry field.

Label is easy. Only send it if the field isn't blank.

**Comment by mlg9000** [comment] 2016-10-02 17:40
Actually there is no reason to ever set the download directory to the lazylibrarian directory,  Instead you'd just do:

1. Set a download directory manually via a entry field and send that to rtorrent
2. If the field is empty send nothing so that it just uses the default rtorrent download directory

So essentially it works exactly the same a label

**Comment by philborman** [comment] 2016-10-02 17:54
Right, so you **do** actually need a directory field, a tick box won't do.
I've currently got it set with a tick box   [X] Send LazyLibrarian download directory to rTorrent
so we send our directory or nothing. (current version in my git)
If you need to send a different directory I will need to change this to an entry field

**Comment by philborman** [comment] 2016-10-02 19:07
ok, added a directory field for rtorrent, blank to send nothing.
Also added limetorrents and exratorrents but neither extensively tested yet, just a couple of books each.

**Comment by mlg9000** [comment] 2016-10-03 19:53
The directory field works as expected, thanks for adding.  Extratorrent/limetorrent also seem to work fine.

The only issue I think that remains for rtorrent is the magnet links leaving stopped torrents without a label/directory set.  Glancing at sickrage it seems to handle this by rechecking rtorrent until there is a torrent with a matching hash and then starting it up appropriately.  Couchpotato just converts them to torrents then submits.  I suppose either method works fine.

**Comment by philborman** [comment] 2016-10-04 08:08
At the moment we are doing magnets the couchpotato way.
I will have a play with the sickrage method and see if that works for us, it would be better to do it that way if we can. Converting file to magnet adds the limitation that the rtorrent server and lazylibrarian need to be on the same host. Not a problem with blackhole as that can be a network shared folder, but we can't pass a filename (or it's contents)  over xmlrpc to rtorrent on a different host.
We already do the "wait for torrent with a matching hash" bit to check the torrent loaded successfully (rtorrent always returns zero whether success or fail) so it might be as simple as moving the check so it's between the "load" command and the "label" command

**Comment by philborman** [comment] 2016-10-04 18:10
Well, it's even more bizarre than  I thought.
Magnets work fine with rtorrent PROVIDING YOU DON'T SET A DIRECTORY
As soon as you send the "set_directory" command, rtorrent stops the torrent, and it won't restart with
any of the load/restart/open commands.  If you send a magnet and then set the label or directory they set correctly until rtorrent downloads the metadata, when the label and directory get discarded.
If you send the "start" command and then wait for the torrent name to change from hash_id.meta to the correct filename, you can then set a label. If you also set a directory it stops the torrent as above.
For torrents you can simply load the torrent, start it, set label, set directory and it all works. Or load the torrent, set directory and label, then start and it all works.

So....
We now send torrents with or without directory.
Magnets are only sent as magnets if you're not setting a directory, otherwise we convert magnet2torrent first.

I've pushed this to the master branch tonight, and will close this ticket in a day or two unless there are still problems. Thanks for your help with the testing.

**Comment by mlg9000** [comment] 2016-10-04 19:44
Yeah that's how it works.  You have to stop the torrent in order to change the directory and then restart it.  A magnet you'd have to wait until the metadata (torrent) download, then stop it to change the directory and restart.

**Closed** 2016-10-09 16:17 UTC
