### ISSUE TITLE
Clear snatched does not clear snatched from title status

### ISSUE THREAD

**Issue by seanvree** [DobyTang/LazyLibrarian#1170] opened 2018-01-07 04:30 UTC
**ISSUE**:

When I go to audiobooks, there are titles that say SNATCHED.  However, when I go to the history tab, there are no items listed as snatched.  When I clear snatched, I get the logs below, but the SNATCHED status is never cleared from the title status. 

### Source of your LazyLibrarian installation: GIT

**LOGS**:

```
Jan 06 20:11:35 LazyLibrarian lazylibrarian.log:  06-Jan-2018 20:11:33 - INFO    :: WEBSERVER : webServe.py:clearhistory:2978 : Clearing history where status is Snatched
Jan 06 20:22:06 LazyLibrarian lazylibrarian.log: 06-Jan-2018 20:22:05 - INFO    :: WEBSERVER : webServe.py:clearhistory:2978 : Clearing history where status is Snatched
```
**DEBUG LOG:**

https://gist.github.com/seanvree/d5fe173412e006c077490aa8db27fbc3

![image](https://user-images.githubusercontent.com/8906637/34646541-c9e1f3d2-f31f-11e7-9a85-11101f8d2c29.png)

**Comment by philborman** [comment] 2018-01-07 08:58
Broken by design.
The buttons on the history page only clear the history table. Probably they shouldn't. I will take a look at this. Easy fix for now is to go to audiobooks page, use the filter to select Snatched, tick them and mark as Skipped

**Comment by seanvree** [comment] 2018-01-07 11:49
@philborman  got it! thanks!

**Comment by philborman** [comment] 2018-01-09 12:49
Should be fixed now

**Closed by philborman** 2018-01-09 12:49 UTC
