### ISSUE TITLE
Error seaching Author

### ISSUE THREAD

**Issue by vader083** [DobyTang/LazyLibrarian#442] opened 2016-08-26 22:54 UTC
search?name=Dan+Simmons
with latest from Master
results in

Error !
KeyError: 'authorid'
<tbody> %if searchresults: %for result in searchresults: <% if result['bookrate'] < 0.5: starimg = '0-stars.png' elif result['bookrate'] >= 0.5 and result['bookrate'] < 1.5: starimg = '1-stars.png' elif result['bookrate'] >= 1.5 and result['bookrate'] < 2.5:
/opt/lazylibrarian/data/interfaces/default/searchresults.html, line 25:
<%
/opt/lazylibrarian/data/interfaces/default/base.html, line 156:
${next.body()}
/opt/lazylibrarian/mako/runtime.py, line 890:
callable_(context, *args, **kwargs)
/opt/lazylibrarian/mako/runtime.py, line 864:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/opt/lazylibrarian/mako/runtime.py, line 829:
**_kwargs_for_callable(callable_, data))
/opt/lazylibrarian/mako/template.py, line 445:
return runtime._render(self, self.callable_, args, data)
/opt/lazylibrarian/lazylibrarian/webServe.py, line 46:
return template.render(**kwargs)

**Comment by philborman** [comment] 2016-08-27 14:10
Which provider are you using (goodreads/googlebooks) and can you post a debug log where it fails?
Can't reproduce it at the moment.

**Comment by vader083** [comment] 2016-08-27 14:25
It's with googlebooks, if I switch to goodreads it works fine.

I don't see the exception in the logs, just in the response above.  These are the last lines from the log

27-Aug-2016 11:22:07 - DEBUG   :: GB-RESULTS : Skipped a book with language fr
27-Aug-2016 11:22:07 - DEBUG   :: GB-RESULTS : Skipped a book with language es
27-Aug-2016 11:22:07 - DEBUG   :: GB-RESULTS : Found 9 total results
27-Aug-2016 11:22:07 - DEBUG   :: GB-RESULTS : Removed 2 bad language results
27-Aug-2016 11:22:07 - DEBUG   :: GB-RESULTS : Removed 0 books with no author
27-Aug-2016 11:22:07 - DEBUG   :: GB-RESULTS : Showing 7 results for (intitle:) with keyword: Dan Simmons
27-Aug-2016 11:22:07 - DEBUG   :: GB-RESULTS : The Google Books API was hit 0 times for keyword Dan Simmons

**Comment by philborman** [comment] 2016-08-27 14:51
ok, think I may have found it.

Would be useful to know what browser you are on, what operating system 
and what version of python as it's not reproducible on linux with 
chrome. I'd like to be able to test it before releasing a fix.

Otherwise I could tell you where to apply a small patch to a text file 
to see if it fixes the problem on your end?

Thanks

**Comment by philborman** [comment] 2016-08-27 16:14
ok, found it. Able to reproduce it after all. Fixed now.
Only errors if searching using GoogleBooks _and_ author is already in database _and_  googlebooks authorname is exactly the same as goodreads authorname. 
Some authornames aren't, including several in my test library, which is why I couldn't find it at first, eg
W.E. Bowman vs W E Bowman,  Henri Charriere vs Henri Charrière

**Closed by philborman** 2016-08-27 16:14 UTC
