### ISSUE TITLE
email notifier doesn't work for non-SSL SMTP servers

### ISSUE THREAD

**Issue by adamgoldberg** [DobyTang/LazyLibrarian#801] opened 2017-05-24 18:27 UTC
notifiers/email_notify.py doesn't correctly check whether the 'SSL' tick box is checked, yielding the situation where it always attempts to use SSL, and if the SMTP server doesn't support SSL, it fails.

The fix is simple.  I'll submit a pull request (assuming I'm not a continuing idiot with git, which is certainly possible).

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment] 2017-05-24 18:42
Thanks for this, not sure I understand the difference though. I'm fairly
new to python, but I thought "if variable:" returned true or false anyway.
False if zero / empty string / boolean false, true otherwise. The variable
is read and stored as a boolean value?

If I'm missing something here there are probably lots of other config
variables with the same issue :-(

**Comment by adamgoldberg** [comment] 2017-05-24 18:48
Sigh.  This is literally the first line of Python I’ve written.

The value returned by lazylibrarian.CONFIG[‘EMAIL_SSL’] is either ‘True’ or ‘False’, but somehow when it returns False, that if statement just calls through into the if (not else) code.

I don’t think it should.  But I don’t know how it should be.  Maybe it’s the lookup of EMAIL_SSL that’s the problem?  I wonder if

   use_ssl = lazylibrarian.CONFIG[‘EMAIL_SSL’]
   if use_ssl:
        mailserver = …


would work?  I’m more lost than you are, but this one line change fixes /my/ problem. ☺


Adam Goldberg
AGP, LLC
+1-202-507-9900

**Comment by philborman** [comment] 2017-05-24 18:54
Ok thanks, I will have a play. There was a problem in the html code because
python uses False and javascript uses false (lowercase) so maybe this is
something similar. I wonder if we are getting a string back, ie the word
"True" rather than  a boolean True. Fun.

**Comment by adamgoldberg** [comment] 2017-05-24 18:57
shrug.  I found it by putting in a debug statement on lazylibrarian.CONFIG[‘EMAIL_SSL’], and was getting "False" and "True", but the if statement wasn't working correctly... 

and I feel like a complete idiot learning a new language.

**Comment by philborman** [comment] 2017-05-24 19:05
I think I might change the config values to integers so we only return 1 or
0
Less chance of confusion and the "if variable:" statements should still
work.

I only started on Python with this project a year ago, so it's all new to
me too. The other problem for me is it's not just python to learn, but also
html, css, javascript, bootstrap and they seem much harder to debug.

Found a nice code checker for the python files (pycharm) that helped me a
lot.

**Comment by philborman** [comment] 2017-05-24 21:13
ok, seems we are getting a string result "True"  instead of a boolean value, will push a fix for this and other similar variables shortly. Thanks for the bug report.

**Closed by philborman** 2017-05-24 21:13 UTC

**Comment by philborman** [comment] 2017-05-25 12:24
Well, it turns out the problem is actually the javascript code that talks to the test button. The javascript variables in config.html get passed as strings, and the test button fed them back to python as strings. It only applied to the email notifier as that's the only one with boolean variables, but a similar problem was found in provider and downloader port values, which also were passed as strings when they should be integers. Hopefully all fixed now, just a bit more testing and will push the fix later today. Thanks for the bug report.

**Comment by adamgoldberg** [comment] 2017-05-25 14:49
Ah, cool.  Glad to be of help.

OT: Is there an example custom notifier?

**Comment by philborman** [comment] 2017-05-25 14:57
Yes, there are a couple of example_custom_notification files in the git
source, one in bash and one in python. These just show the data that is
sent sent to the custom_notification and how to read it.
There is also example_ebook_convert.py that shows how to send the data on
to calibre.
