### ISSUE TITLE
Problem w. SSL when starting LL after latest update

### ISSUE THREAD

**Issue by madgabz** [DobyTang/LazyLibrarian#258] opened 2016-01-23 21:57 UTC
Running LL on my FreeBSD based Nas4free, inside a jail! Tried installing fresh in second jail, same error reproduced, when starting with: python /usr/local/LazyLibrarian.py --daemon --quiet

Traceback (most recent call last):
  File "LazyLibrarian.py", line 179, in <module>
    main()
  File "LazyLibrarian.py", line 125, in main
    lazylibrarian.initialize()
  File "/usr/local/LazyLibrarian/lazylibrarian/__init__.py", line 635, in initialize
    BOOKSTRAP_THEMELIST = build_bookstrap_themes()
  File "/usr/local/LazyLibrarian/lazylibrarian/__init__.py", line 890, in build_bookstrap_themes
    resp = urllib2.urlopen(req)
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/local/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)>

The log contains nothing unusual! :/

Looking at the latest commits, it seems that urllib2 is broken! https://github.com/DobyTang/LazyLibrarian/commit/3720c2d4ced5e65e725e249f5162839764a64a17 
LazyLibrarian/__init__.py
+import urllib2

**Comment by famewolf** [comment] 2016-01-24 07:13
https://github.com/DobyTang/LazyLibrarian/issues/259 is dupe of this one.

**Comment by philborman** [comment] 2016-01-24 18:30
Can be closed now

**Closed** 2016-01-24 22:11 UTC
