### ISSUE TITLE
Database Error: database is locked

### ISSUE THREAD

**Issue by hctancredi** [DobyTang/LazyLibrarian#735] opened 2017-04-21 16:44 UTC
Current Version: 6918a5c89a2cdb97bf1c679aff7fbd025df683c4
S.O: Unraid Docker
Interface: bookstrap
Branch: Master
Hello.

I'm trying to do a "Library Scan" and I keep stuck getting a lot of errors like this:

Database Error: database is locked
Error finding rescan results: string indices must be integers.

Any workaround?

**Comment by philborman** [comment] 2017-04-21 16:56
Would need more info, debug log would be useful. The two lines quoted 
don't give enough context to know what's happening or which part of 
lazylibrarian the lines came from.

Latest version includes a database upgrade, not sure what would happen 
if you try to libraryscan while the database upgrade is still in 
progress, but probably not good. Maybe that's the problem, hard to say.

**Comment by hctancredi** [comment] 2017-04-21 17:40
here you have

[lazylibrarian.log.txt](https://github.com/DobyTang/LazyLibrarian/files/947853/lazylibrarian.log.txt)

**Comment by hctancredi** [comment] 2017-04-21 17:44
[logs.zip](https://github.com/DobyTang/LazyLibrarian/files/947866/logs.zip)
 here you go

**Comment by philborman** [comment] 2017-04-21 17:58
That zip file is empty??

**Comment by hctancredi** [comment] 2017-04-21 18:03
[log.zip](https://github.com/DobyTang/LazyLibrarian/files/947924/log.zip)

sorry about that

**Comment by philborman** [comment] 2017-04-21 18:47
The problem occurs just after a database "unique constraint failed" error. I have added a bit of code to exit cleanly, and more debugging messages if it still fails as the existing message (string indices must be integers) doesn't really tell us where the problem is.  Try upgrading to latest version, and if it still fails we should get enough info in the log to be able to fix it properly. Thanks.

**Comment by hctancredi** [comment] 2017-04-21 23:42
Understood. Just one question. How am I suppose to upgrade it? it's saying that I on the latest level available.

2017-04-21 20:39:47	DEBUG	Update check complete
2017-04-21 20:39:47	DEBUG	(getLatestVersion_FromGit) Branch [master] Currently on Latest Version
2017-04-21 20:39:46	DEBUG	(getLatestVersion_FromGit) Retrieving latest version information from github command=[https://api.github.com/repos/dobytang/lazylibrarian/commits/master]
2017-04-21 20:39:46	DEBUG	(getCurrentVersion) - Install type [git] Local Version is set to [6918a5c89a2cdb97bf1c679aff7fbd025df683c4]

**Comment by hctancredi** [comment] 2017-04-22 00:02
I did a pull from within my docker, it seems that I got your latest commits.

**Comment by hctancredi** [comment] 2017-04-22 00:44
I did a new library scan and the log is flooded with 
21-Apr-2017 21:40:33 - DEBUG   :: LIBRARYSYNC : Unique entry suppressed [INSERT INTO seriesauthors ("SeriesID", "AuthorID") VALUES ("43", "5780686")]

[log_20170421.zip](https://github.com/DobyTang/LazyLibrarian/files/948617/log_20170421.zip)

**Comment by philborman** [comment] 2017-04-22 07:13
The code I added to (hopefully) unlock the database got stuck in a loop. Should be fixed now, couldn't test it here as I can't reproduce the original problem. Sorry about that.

**Comment by hctancredi** [comment] 2017-04-22 21:15
I decided to delete my DB and recreate it all over again. What's weird is that I had troubles during the past 2 DB version update. Maybe increasing the code debug level that might help you find out what's going on in the future. 
For now everything seems fine, but I'll keep an eye on future upgrades and let you know.
thanks for your help.

**Comment by philborman** [comment] 2017-04-23 07:38
Trying to do anything else while a database upgrade is in progress could cause issues. I put up a home page with a warning message saying "upgrade in progress please wait" and a counter so you can see how far the upgrade has got. There is nothing stopping you from navigating away from this page though, and I don't know how to prevent it (yet). Alternatively there could be a problem with the upgrade itself, there was in an earlier version a while back where the upgrade could abort part way through causing issues, but I don't think that's the case with the latest upgrade. Hard to pin it down. No more database upgrades are planned at the moment, so hopefully we're ok for a while ;-)

**Closed by philborman** 2017-04-23 07:38 UTC

**Comment by hctancredi** [comment] 2017-04-26 22:24
Alright thanks for trying. As I said. I'll keep an eye on that DB.
