### ISSUE TITLE
Exception in Audioscan

### ISSUE THREAD

**Issue by PeteJB** [DobyTang/LazyLibrarian#1209] opened 2018-01-30 13:55 UTC
30-Jan-2018 23:22:20 - ERROR :: AUDIO_SCAN : librarysync.py:LibraryScan:949 : Unhandled exception in libraryScan: Traceback (most recent call last):

File "/app/lazylibrarian/lazylibrarian/librarysync.py", line 570, in LibraryScan
newauthor, authorid, new = addAuthorNameToDB(author) # get the author name as we know it...
File "/app/lazylibrarian/lazylibrarian/importer.py", line 43, in addAuthorNameToDB
author = formatAuthorName(author)
File "/app/lazylibrarian/lazylibrarian/formatter.py", line 379, in formatAuthorName
author = makeUnicode(author)
File "/app/lazylibrarian/lazylibrarian/formatter.py", line 241, in makeUnicode
txt = txt.decode(encoding)
AttributeError: 'list' object has no attribute 'decode'

**Comment by philborman** [comment] 2018-01-30 22:54
I had another report about this a few days ago. I think it's an audiobook with multiple authors, in which case there will be a fix in a couple of days (I'm just moving house) but the previous reporter said the problem went away when he changed the encoding on his id3 tags. If its an encoding problem then we might need to change the id3 tag reader in lazylibrarian.

**Comment by PeteJB** [comment] 2018-01-31 10:06
Thanks for the reply. There was a a book which had the author name as "Author One & Author Two".

I updated that to only have Author One. Still have the same problem.

I then removed all books audio books from the audio book directory and did a rescan which completed successfully. 

I then copied only one book back and tried again and received the exception message. 

Interestingly after removing all books from the library and doing the rescan, the audiobook tab still showed the books as being there (even though they weren't).

**Comment by mcaron1234** [comment] 2018-01-31 17:32
I had a similar issue when scanning my audio book library.  What I did was convert all tags to v2.4 utf8 (not sure if this was strictly necessary), and then I had to go through my library and remove all characters that were not standard.  Troublesome ones for me were "&" and "é", make sure you move them from not just the file names, but the tags as well.

**Comment by philborman** [comment] 2018-01-31 21:43
I think I need to do some work on the id3 library, it shouldn't really need tags modifying to work.
I will try creating some fake tags with odd characters and see what happens.
Odd characters in filenames shouldn't be a problem with the libraryscan unless there are no tags in the files. We use tags if present, and only use the filename if we have nothing better.

**Comment by PeteJB** [comment] 2018-02-02 11:54
Thanks for the comments. I've been through all the tags and can't find any non-standard characters. There was in one book at first, but I fixed that. Still having the problem.

**Comment by philborman** [comment] 2018-02-02 17:13
I've fixed the exception, will push a new version in the next couple of days, but not sure what the underlying problem is. I tried throwing in some non-standard characters but didn't hit the problem.
One thing that might help, the id3reader library can be called from the command line. If you have a book causing issues, could you run the id3reader on one of the books mp3 files and post the output?
It would be something like...
/lazylibrarian_program_folder/lib/id3reader.py  /book_folder/bookfile.mp3
Thanks

**Comment by PeteJB** [comment] 2018-02-03 00:26
will do. Might not be till tomorrow though. Not sure I can get to it today, but will try

**Comment by PeteJB** [comment] 2018-02-04 00:07
Hi. I tried that. Here's the output:

root@0a7f5519f37c:/audiobooks/Brandon Sanderson/Snapshot (Unabridged)$ python /app/lazylibrarian/lib/id3reader.py /'Snapshot (Unabridged) - 007.mp3'
Traceback (most recent call last):
  File "/app/lazylibrarian/lib/id3reader.py", line 11, in <module>
    from lib.six import PY2
ImportError: No module named lib.six

**Comment by philborman** [comment] 2018-02-04 08:55
Ah yes, forgot that part. It temporarily relied on another library, doesn't need it any more.
If you change into the lazylibrarian library first it should work, so change directory to /app/lazylibrarian
python lib/id3reader.py c:/audiobooks/author/directory/007.mp3

**Comment by PeteJB** [comment] 2018-02-04 11:35
Hi. Thanks for the response. I tried that. Got the same issue.


root@0a7f5519f37c:/app/lazylibrarian$ python lib/id3reader.py /audiobooks/testauthor/testbook/001.mp3
Traceback (most recent call last):
  File "lib/id3reader.py", line 11, in <module>
    from lib.six import PY2
ImportError: No module named lib.six

**Comment by PeteJB** [comment] 2018-02-05 00:50
Thanks. I'll wait for the next release. Appreciate your time.

**Comment by PeteJB** [comment] 2018-02-11 05:01
Hi. My docker has been updated and is now running the latest commit
Current Version: b53cbb15f05265e21c022a4d9c20310b8a6949b7

Ran a scan of the audiobook library again. Here's the results:

11-Feb-2018 15:56:25 - INFO :: AUDIO_SCAN : librarysync.py:LibraryScan:314 : Scanning Audio directory: /audiobooks
11-Feb-2018 15:56:29 - INFO :: AUDIO_SCAN : importer.py:addAuthorNameToDB:95 : Adding new author [Yps]
11-Feb-2018 15:56:42 - INFO :: AUDIO_SCAN : gr.py:get_author_books:789 : [Yps] Book processing complete: Added 0 books to the database
11-Feb-2018 15:56:42 - INFO :: AUDIO_SCAN : importer.py:addAuthorToDB:302 : [Yps] Author update complete, status Active
11-Feb-2018 15:56:42 - ERROR :: AUDIO_SCAN : librarysync.py:LibraryScan:968 : Unhandled exception in libraryScan: Traceback (most recent call last):

File "/app/lazylibrarian/lazylibrarian/librarysync.py", line 600, in LibraryScan
book = replace_all(book, dic)
File "/app/lazylibrarian/lazylibrarian/formatter.py", line 485, in replace_all
text = text.replace(item, dic[item])
AttributeError: 'list' object has no attribute 'replace'

Interesting this is I don't have any audiobooks with a composer value set to Yps.

Hope this helps.

Thanks again

**Comment by philborman** [comment] 2018-02-11 08:37
Can you try that again with debug level logging set to 3
Should get some useful extra messages. Thanks.

**Comment by philborman** [comment] 2018-02-11 09:12
Brilliant thanks, 
Can see the problem clearly there, all the strings are separated out into individual characters. Just need to figure out why now, might take me a while...

**Comment by PeteJB** [comment] 2018-02-11 10:02
Awesome. Thanks

**Comment by philborman** [comment] 2018-02-11 11:54
ok, think I've found it. There is an optional ByteOrderMarker that the library wasn't handling. I've attached a new id3reader library for you to try if you don't mind.
Rename your old version of lib/id3reader.py first, try the new one, then put your old one back. If you don't replace the old one, the upgrade mechanism will stop working because of "local changes"
[id3reader.zip](https://github.com/DobyTang/LazyLibrarian/files/1714314/id3reader.zip)

**Comment by PeteJB** [comment] 2018-02-11 12:13
Hi. I installed the new id3reader.py, restarted LL and then rescanned the audio library. I have debug level 3 on. Here's the lines from the log

11-Feb-2018 23:06:15 - INFO :: AUDIO_SCAN : librarysync.py:LibraryScan:314 : Scanning Audio directory: /audiobooks
11-Feb-2018 23:06:15 - DEBUG :: AUDIO_SCAN : librarysync.py:LibraryScan:439 : [/audiobooks] Now scanning subdirectory /Stieg Larsson/Stieg Larsson - The Girl with the Dragon Tattoo 64k
11-Feb-2018 23:06:15 - DEBUG :: AUDIO_SCAN : librarysync.py:LibraryScan:527 : id3reader author list [\xff\xfeS, t, i, e, g, , L, a, r, s, s, o, n]
11-Feb-2018 23:06:15 - DEBUG :: AUDIO_SCAN : librarysync.py:LibraryScan:535 : id3reader error AttributeError 'list' object has no attribute 'decode' [/audiobooks/Stieg Larsson/Stieg Larsson - The Girl with the Dragon Tattoo 64k/1-2 Stieg Larsson - The Girl with the Dragon Tattoo.mp3]

Header:
{'majorVersion': 3, 'bUnsynchronized': False, 'bExperimental': False, 'bFooter': False, 'flags': 0, 'revision': 0, 'size': 4086}
Frames:
[{'bEncrypted': False, 'value': ['\xff\xfeT', 'h', 'e', ' ', 'G', 'i', 'r', 'l', ' ', 'w', 'i', 't', 'h', ' ', 't', 'h', 'e', ' ', 'D', 'r', 'a', 'g', 'o', 'n', ' ', 'T', 'a', 't', 't', 'o', 'o'], 'bReadOnly': False, 'bFileAlterPreserve': False, 'bTagAlterPreserve': False, 'flags': 0, 'rawData': '\x01\xff\xfeT\x00h\x00e\x00 \x00G\x00i\x00r\x00l\x00 \x00w\x00i\x00t\x00h\x00 ', 'bInGroup': False, 'id': 'TALB', 'bCompressed': False, 'size': 67},
{'bEncrypted': False, 'value': ['\xff\xfeS', 'i', 'm', 'o', 'n', ' ', 'V', 'a', 'n', 'c', 'e'], 'bReadOnly': False, 'bFileAlterPreserve': False, 'bTagAlterPreserve': False, 'flags': 0, 'rawData': '\x01\xff\xfeS\x00i\x00m\x00o\x00n\x00 \x00V\x00a\x00n\x00c\x00e\x00\x00\x00', 'bInGroup': False, 'id': 'TPE1', 'bCompressed': False, 'size': 27},
{'bEncrypted': False, 'value': ['\xff\xfeS', 'i', 'm', 'o', 'n', ' ', 'V', 'a', 'n', 'c', 'e'], 'bReadOnly': False, 'bFileAlterPreserve': False, 'bTagAlterPreserve': False, 'flags': 0, 'rawData': '\x01\xff\xfeS\x00i\x00m\x00o\x00n\x00 \x00V\x00a\x00n\x00c\x00e\x00\x00\x00', 'bInGroup': False, 'id': 'TPE2', 'bCompressed': False, 'size': 27},
{'bEncrypted': False, 'value': '\xff\xfeR\x00e\x00a\x00d\x00 \x00b\x00y\x00 \x00S\x00i\x00m\x00o\x00n\x00 \x00V\x00a\x00n\x00c\x00e\x00;\x00 \x00U\x00n\x00a\x00b\x00r\x00\x00', 'bReadOnly': False, 'bFileAlterPreserve': False, 'bTagAlterPreserve': False, 'flags': 0, 'rawData': '\x01eng\xff\xfe\x00\x00\xff\xfeR\x00e\x00a\x00d\x00 \x00b\x00y\x00 \x00S\x00i\x00', 'bInGroup': False, 'id': 'COMM', 'bCompressed': False, 'size': 64},
{'bEncrypted': False, 'value': ['\xff\xfeS', 't', 'i', 'e', 'g', ' ', 'L', 'a', 'r', 's', 's', 'o', 'n'], 'bReadOnly': False, 'bFileAlterPreserve': False, 'bTagAlterPreserve': False, 'flags': 0, 'rawData': '\x01\xff\xfeS\x00t\x00i\x00e\x00g\x00 \x00L\x00a\x00r\x00s\x00s\x00o\x00n\x00\x00', 'bInGroup': False, 'id': 'TCOM', 'bCompressed': False, 'size': 31},
{'bEncrypted': False, 'value': ['\xff\xfeA', 'u', 'd', 'i', 'o', 'b', 'o', 'o', 'k'], 'bReadOnly': False, 'bFileAlterPreserve': False, 'bTagAlterPreserve': False, 'flags': 0, 'rawData': '\x01\xff\xfeA\x00u\x00d\x00i\x00o\x00b\x00o\x00o\x00k\x00\x00\x00', 'bInGroup': False, 'id': 'TCON', 'bCompressed': False, 'size': 23},
{'bEncrypted': False, 'value': ['\xff\xfe1', '-', '2'], 'bReadOnly': False, 'bFileAlterPreserve': False, 'bTagAlterPreserve': False, 'flags': 0, 'rawData': '\x01\xff\xfe1\x00-\x002\x00\x00\x00', 'bInGroup': False, 'id': 'TIT2', 'bCompressed': False, 'size': 11},
{'bEncrypted': False, 'value': '01/02', 'bReadOnly': False, 'bFileAlterPreserve': False, 'bTagAlterPreserve': False, 'flags': 0, 'rawData': '\x0001/02\x00', 'bInGroup': False, 'id': 'TRCK', 'bCompressed': False, 'size': 7}]
TALB: '\xff\xfeT', 'h', 'e', ' ', 'G', 'i', 'r', 'l', ' ', 'w', 'i', 't', 'h', ' ', 't', 'h', 'e', ' ', 'D', 'r', 'a', 'g', 'o', 'n', ' ', 'T', 'a', 't', 't', 'o', 'o'
TPE1: '\xff\xfeS', 'i', 'm', 'o', 'n', ' ', 'V', 'a', 'n', 'c', 'e'
TPE2: '\xff\xfeS', 'i', 'm', 'o', 'n', ' ', 'V', 'a', 'n', 'c', 'e'
COMM: ?: '\xff\xfeR\x00e\x00a\x00d\x00 \x00b\x00y\x00 \x00S\x00i\x00m\x00o\x00n\x00 \x00V\x00a\x00n\x00c\x00e\x00;\x00 \x00U\x00n\x00a\x00b\x00r\x00\x00'
11-Feb-2018 23:06:15 - DEBUG :: AUDIO_SCAN : librarysync.py:LibraryScan:537 : None
11-Feb-2018 23:06:15 - DEBUG :: AUDIO_SCAN : importer.py:addAuthorNameToDB:47 : Author ÿþS not found in database, trying to add
11-Feb-2018 23:06:15 - DEBUG :: AUDIO_SCAN : gr.py:find_author_id:241 : Searching for author with name: ypS
11-Feb-2018 23:06:15 - DEBUG :: AUDIO_SCAN : cache.py:get_cached_request:152 : CacheHandler: Returning CACHED response for https://www.goodreads.com/api/author_url/ypS?key=ckvsiSDsuqh7omh74ZZ6Q
11-Feb-2018 23:06:15 - DEBUG :: AUDIO_SCAN : cache.py:get_cached_request:152 : CacheHandler: Returning CACHED response for https://www.goodreads.com/author/show/11469510.xml?key=ckvsiSDsuqh7omh74ZZ6Q
11-Feb-2018 23:06:15 - DEBUG :: AUDIO_SCAN : gr.py:get_author_info:297 : [Yps] Processing info for authorID: 11469510
11-Feb-2018 23:06:15 - DEBUG :: AUDIO_SCAN : importer.py:addAuthorNameToDB:93 : Found goodreads authorname Yps in database
11-Feb-2018 23:06:15 - DEBUG :: AUDIO_SCAN : librarysync.py:LibraryScan:590 : Preferred authorname changed from [ÿþS] to [Yps]
11-Feb-2018 23:06:15 - ERROR :: AUDIO_SCAN : librarysync.py:LibraryScan:968 : Unhandled exception in libraryScan: Traceback (most recent call last):

File "/app/lazylibrarian/lazylibrarian/librarysync.py", line 600, in LibraryScan
book = replace_all(book, dic)
File "/app/lazylibrarian/lazylibrarian/formatter.py", line 485, in replace_all
text = text.replace(item, dic[item])
AttributeError: 'list' object has no attribute 'replace'

**Comment by philborman** [comment] 2018-02-11 12:39
ok, thanks for trying.
Think I might need a file that fails to play with. Any chance you can send me 
[/audiobooks/Stieg Larsson/Stieg Larsson - The Girl with the Dragon Tattoo 64k/1-2 Stieg Larsson - The Girl with the Dragon Tattoo.mp3]
so I can track the problem down. Seems the problem is the '\xff\xfe' at the start of the strings that we're not interpreting properly. I don't have any audiofiles with utf-16 tags to try and my id3 tag editor (easytag) doesn't use utf-16 either. Probably best to email me at phil.borman@gmail.com rather than upload to github.

**Comment by philborman** [comment] 2018-02-11 16:13
ok, think this is probably fixed now. Changed the id3 tag library in the next version. We now use tinytag which seems to be more resilient.  Didn't use that library before as it didn't handle all the tags we need, its geared more for music than audiobooks so it didn't include narrator. Turned out it was easier to add narrator to tinytag than to debug id3reader. New version out in a few hours.

**Comment by PeteJB** [comment] 2018-02-11 20:59
Thanks.

 

In case it’s useful here’s the link to the file you wanted.

 

https://drive.google.com/open?id=1vHcMrY3Rm5W5Z6lHtMPBRns5Lz93y1A5

 

Pete

**Comment by PeteJB** [comment] 2018-02-11 22:06
Thanks. That fixed it. All good now

**Closed** 2018-02-12 08:24 UTC
Labels: fixed
