### ISSUE TITLE
Python errors 

### ISSUE THREAD

**Issue by thyeestes** [DobyTang/LazyLibrarian#1129] opened 2017-11-23 16:37 UTC
To help with identifying and fixing issues, please include as much information as possible, including:
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)

I get these errors when I manually try change something e.g. delete books.

Hope this is a config thing, so it can be solved quickly.

Thanks,
Martijn

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.
Traceback (most recent call last):
  File "/volume1/@appstore/lazylibrarian/share/LazyLibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/volume1/@appstore/lazylibrarian/share/LazyLibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/lazylibrarian/share/LazyLibrarian/cherrypy/_cpdispatch.py", line 67, in __call__
    raise sys.exc_info()[1]
HTTPError: (404, 'Missing parameters: library')

**Comment by philborman** [comment] 2017-11-23 17:18
Duplicate of #1128

**Closed by philborman** 2017-11-23 17:18 UTC
