### ISSUE TITLE
Calibre Help

### ISSUE THREAD

**Issue by mccorkled** [DobyTang/LazyLibrarian#1152] opened 2017-12-28 20:32 UTC
Hello again, 

I have been without internet while moving and have not had time to mess with this anymore. I thought we had it all figured out last time, but something is still not right. Once the book is down downloading, it should be processed into Calibre but instead the book is being placed in /books even though I have /books/calibre setup. 

Here is the log. 
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1592039/debug.zip)

**Comment by philborman** [comment] 2017-12-28 22:41
You are getting "connection reset by peer" from calibredb so it seems you have a calibre config problem. Maybe missing user/password, or maybe the calibre server isn't running? Anything in the calibre logs that might help? Unfortunately calibre isn't telling us what the problem is. Because the import using http://calibre_database is not working, lazylibrarian retries the import with /books as the library. This works, but isn't what you want, so it seems we are talking to calibredb properly, it looks like the problem is calibredb talking to the calibre server.

**Comment by mccorkled** [comment] 2017-12-28 23:41
I know people rave about the power of Calibre, but I have a heck of a time figuring it out and navigating it. I am using Docker, so I am not sure where the logs for Calibre are. I cannot even find a log option within the program.

**Comment by philborman** [comment] 2017-12-29 09:58
Not sure about docker, but on my laptop the logs are in /home/username/.cache/calibre/  (calibre v3.x) and on my server (raspberry pi, calibre v2.x) the logs are in /home/username/.config/calibre/

if you have ssh access to your docker it may include the "find" command, so you could 
find -iname calibre

**Comment by mccorkled** [comment] 2017-12-29 15:48
I don't have a username and password setup but I can get into Calibre without that, and server is definitely running. I posted on the thraxis fork and I guess we'll see what he says.

**Comment by philborman** [comment] 2017-12-29 18:05
It could be author/pass that's the problem. If you are using http://xxx to access the calibre server you __need__ author/pass, otherwise you are only given read access which means you can't add books. If you use /path/to/library (ie server is on the same machine as calibredb) then you can read/write without user/pass

**Comment by mccorkled** [comment] 2017-12-29 19:10
Yes, everything is on the same machine.

**Comment by philborman** [comment] 2017-12-29 19:57
Yes but because you are using calibre_server = http://192.168.0.12:9000/  you need to set calibre user/password.  

The alternative is to use calibre_server = /path/to/calibre/metadata.db
but both dockers need to share the same metadata.db, not sure if the dockers allow this, depends if you can configure the location of metadata.db

**Comment by mccorkled** [comment] 2017-12-29 20:43
In my /books/calibre I have...

.driveinfo.calibre
.metadata.calibre
metadata_db_prefs_backup
metadata.db

I configured Calibre to use this directory for book when I initially set it up.

**Comment by philborman** [comment] 2017-12-29 22:27
So...
It looks like Calibre uses /books as it's library
so your book library looks like /books/Author Name/Book Title (num)/BookFile.epub
and your calibre database is /books/metadata.db

The (num) part is calibres book_id, starts at 1 and goes up with each book added to their library, not useful to us.  If the above is correct then...

You have a couple of options depending on whether you are on calibre v2.x or calibre v3.x and whether you want to use the main calibre program at the same time (not the web interface, the main gui)

Details are in https://manual.calibre-ebook.com/generated/en/calibredb.html

The first option works on both calibre versions, but NOT if you want to use the calibre gui...
If you set `LazyLibrarian eBook Library Folder` to /books to match your calibre settings then lazylibrarian will share same folder layout, and if you untick `Use Calibre Content Server`, we will use calibredb to read/write the calibre metadata.db file found in /books. On calibre v3.x you need to start calibre-server with  --enable-local-write , I don't think this option is needed on calibre-server v2.x  This is how I use it on my headless raspberry pi server.

The second method is to use `Calibre Content Server` or Calibre main gui with Connect/share  →  Start Content server
This allows you to use the main calibre program at the same time without problems as everything goes through the one content server. If both calibre and lazylibrarian are on the same machine, in lazylibrarian config just set `Calibre Server` to /books
If they are on different machines you need to use the URL form http://whatever, and also set user/pass on both calibre and lazylibrarian to match. If you don't set user/pass you will only get read access, no changes allowed. The URL form only works on calibre v3.x

**Comment by mccorkled** [comment] 2017-12-30 01:24
I deleted Calibre from my NAS, and unchecked "Use Calibre Content Server" in LL and everything is working. The books are downloaded, thraxis's LL/Calibre does what is does with them, places them into /books, and then I can view them using Calibre-web at http://192.168.0.12:8082

**Comment by philborman** [comment] 2017-12-30 16:43
ok, excellent. I will close this for now.

**Closed by philborman** 2017-12-30 16:43 UTC
