### ISSUE TITLE
f_group parameter missing for gen.lib.rus.ec?

### ISSUE THREAD

**Issue by dkids** [DobyTang/LazyLibrarian#1313] opened 2018-04-12 19:15 UTC
Already sent version of LL and OS in issue a few minutes ago.

Search all fields: 
http://gen.lib.rus.ec/foreignfiction/index.php?s=kelley+armstrong+betrayals&f_lang=English&f_columns=0&f_ext=All&f_group=1

Results:
Found 1 results
Author(s) | Series | Title | Language | DL links
-- | -- | -- | -- | --
Armstrong, Kelley | Cainsville 4 | Betrayals | English | EPUB (2 Mb): [Libgen.io] [Libgen.pw]

Search author field:
http://gen.lib.rus.ec/foreignfiction/index.php?s=kelley+armstrong+betrayals&f_lang=English&f_columns=2&f_ext=All&f_group=1

Results:
0 results 
Author(s) | Series | Title | Language | DL links
-- | -- | -- | -- | --

/Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.1:12-Apr-2018 11:10:04 - DEBUG   :: SEARCHBOOK : directparser.py:GEN:124 : Parsing results from <a href="http://gen.lib.rus.ec//foreignfiction/index.php?s=Kelley+Armstrong+Betrayals&f_lang=All&f_ext=All&f_columns=0">libgen.io</a>
/Users/kids/src/LazyLibrarian-master/Logs/lazylibrarian.log.1:12-Apr-2018 11:10:04 - DEBUG   :: SEARCHBOOK : directparser.py:GEN:259 : Found 0 results from libgen.io for Kelley Armstrong Betrayals

I wondered if it might be case-sensitive so I tried: http://gen.lib.rus.ec/foreignfiction/index.php?s=Kelley+Armstrong+Betrayals&f_lang=English&f_columns=0&f_ext=All&f_group=1 

and got 

found 1 results
Author(s) | Series | Title | Language | DL links
-- | -- | -- | -- | --
Armstrong, Kelley | Cainsville 4 | Betrayals | English | EPUB (2 Mb): [Libgen.io] [Libgen.pw]

I tried modifying the URL but didn't have any luck.

/foreignfiction/index.php?f_group=1

12-Apr-2018 11:29:25 - DEBUG   :: SEARCHBOOK : providers.py:IterateOverDirectSites:458 : [IterateOverDirectSites] - http://gen.lib.rus.ec/ foreignfiction/index.php
12-Apr-2018 11:29:26 - DEBUG   :: SEARCHBOOK : directparser.py:GEN:124 : Parsing results from <a href="http://gen.lib.rus.ec//foreignfiction/index.php?s=Kelley+Armstrong+Betrayals&f_lang=All&f_ext=All&f_columns=0">libgen.io</a>
12-Apr-2018 11:29:26 - DEBUG   :: SEARCHBOOK : directparser.py:GEN:259 : Found 0 results from libgen.io for Kelley Armstrong Betrayals
12-Apr-2018 11:29:26 - DEBUG   :: SEARCHBOOK : providers.py:IterateOverDirectSites:458 : [IterateOverDirectSites] - 93.174.95.27 foreignfiction/index.php?f_group=1
12-Apr-2018 11:29:26 - DEBUG   :: SEARCHBOOK : directparser.py:GEN:124 : Parsing results from <a href="http://93.174.95.27/search.php?column=def&res=100&req=Kelley+Armstrong+Betrayals&phrase=0&open=0&view=simple">libgen.io</a>
12-Apr-2018 11:29:27 - DEBUG   :: SEARCHBOOK : directparser.py:GEN:259 : Found 0 results from libgen.io for Kelley Armstrong Betrayals
12-Apr-2018 11:29:27 - INFO    :: SEARCHBOOK : searchbook.py:search_book:289 : DIRECT Searches for eBook Kelley Armstrong Betrayals returned no results.

**Comment by philborman** [comment] 2018-04-13 07:46
Yes we don't use f_group, could be added though.  What does it do, can't find any documentation on it.
Also we use f_lang=All as some are incorrectly labelled.

**Comment by Code-Slave** [comment] 2018-04-13 14:37
fgroup looks like it groups download links per title record. no fgroups looks entirely easier to handle programmatically

**Comment by philborman** [comment] 2018-04-13 16:01
Yes, doesn't look useful.
Not sure why op doesn't get a result without it though, the libgen.io link in blue above (line 124) works for me.

**Comment by philborman** [comment] 2018-04-15 15:53
Actually it's nothing to with fgroup, the problem is libgen have changed the page layout so our scraper fails. Fixed now :-)

**Closed** 2018-04-18 11:54 UTC
Labels: fixed
