### ISSUE TITLE
"Upgrading Database" loop after upgrade

### ISSUE THREAD

**Issue by uzegonemad** [DobyTang/LazyLibrarian#650] opened 2017-02-14 05:22 UTC
I upgraded from 49a0edea6f132aec48f761e7467589280ab1071e to 67a4827ade8a9d6e243f41ff295a770ea0ff8937 and after upgrading, LL became stuck in a loop. The web interface displayed "Updating database, please wait" and the logs were filled with "database is locked" messages.

Restarting several times did nothing.

I traced this to #626 where the initial `UPDATE_MSG` value was changed to `''`. On a hunch I changed it back to `None`, restarted, and it fixed the issue. Then I changed it back to `''`, restarted again, and everything is still functioning properly. [Reference](https://github.com/DobyTang/LazyLibrarian/pull/626/files#diff-56b022d2f1ff4a4f27455b95a3fb2506)

### Operating system used (windows, mac, linux, NAS type)
FreeNAS 9.3

### Interface in use (default, bookstrap)
Default

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
FreeNAS plugin

### Relevant debug log with api keys and any passwords redacted
```13-Feb-2017 20:59:34 - INFO    :: MAIN : Config file loaded
13-Feb-2017 20:59:34 - INFO    :: MAIN : SYS_ENCODING is UTF-8
13-Feb-2017 20:59:34 - INFO    :: DB_UPGRADE : Updating database to version 13, current version is 0
13-Feb-2017 20:59:34 - DEBUG   :: MAIN : Bookstrap found 16 themes
13-Feb-2017 20:59:34 - DEBUG   :: MAIN : (LazyLibrarian) Setup install,versions and commit status
13-Feb-2017 20:59:34 - DEBUG   :: MAIN : (getInstallType) [source] install detected. Setting Branch to [master]
13-Feb-2017 20:59:34 - DEBUG   :: MAIN : Current Version [67a4827ade8a9d6e243f41ff295a770ea0ff8937] - Latest remote version [not checked] - Install type [source]
13-Feb-2017 20:59:34 - INFO    :: MAIN : Starting LazyLibrarian on port: 5299, webroot ""
13-Feb-2017 20:59:34 - DEBUG   :: MAIN : Writing PID 22752 to /var/run/lazylibrarian/lazylibrarian.pid
13-Feb-2017 20:59:34 - INFO    :: MAIN : Starting LazyLibrarian web server on http://0.0.0.0:5299/
13-Feb-2017 20:59:34 - INFO    :: MAIN : Web server authentication is enabled, username is 'admin'
13-Feb-2017 20:59:34 - INFO    :: DB_UPGRADE : Updating database to hold WorkPage
13-Feb-2017 20:59:34 - DEBUG   :: MAIN : Start processDir job in 10 minutes
13-Feb-2017 20:59:34 - INFO    :: DB_UPGRADE : Updating books to hold SeriesNum
13-Feb-2017 20:59:34 - DEBUG   :: MAIN : Start search_tor_book job in 360 minutes
13-Feb-2017 20:59:34 - DEBUG   :: MAIN : Start search_magazines job in 360 minutes
13-Feb-2017 20:59:34 - DEBUG   :: MAIN : Start checkForUpdates job in 24 hours
13-Feb-2017 20:59:34 - INFO    :: DB_UPGRADE : Adding WorkPage to existing books
13-Feb-2017 20:59:34 - INFO    :: DB_UPGRADE : Removing units from wanted table
13-Feb-2017 20:59:34 - DEBUG   :: ADDWORKPAGE : No missing WorkPages
13-Feb-2017 20:59:36 - INFO    :: DB_UPGRADE : Removing SeriesOrder from books table
13-Feb-2017 20:59:36 - INFO    :: DB_UPGRADE : Updating stats table to hold duplicates
13-Feb-2017 20:59:36 - INFO    :: DB_UPGRADE : Updating books table to hold Manual setting
13-Feb-2017 20:59:37 - INFO    :: DB_UPGRADE : Updating wanted table to hold Source and DownloadID
13-Feb-2017 20:59:38 - INFO    :: DB_UPGRADE : Updating magazines table
13-Feb-2017 20:59:38 - INFO    :: DB_UPGRADE : Updating author table to hold last book image
13-Feb-2017 20:59:38 - INFO    :: DB_UPGRADE : Updating magazine table to hold last issue image
13-Feb-2017 20:59:38 - INFO    :: DB_UPGRADE : Updating authors table to hold Manual setting
13-Feb-2017 20:59:39 - INFO    :: DB_UPGRADE : Database updated to version 13
13-Feb-2017 20:59:55 - WARNING :: MAIN : Database Error: database is locked```

**Comment by philborman** [comment] 2017-02-14 09:11
Strange. There seems to be some sort of timing issue, not sure how to track it down as it's not repeatable here. The "database is locked" message is after the update completes, and doesn't show why the database is locked. I added some code after the last report of this problem so the log should show what's causing the lock, but that doesn't seem to be working. The last report was a user on a Raspberry Pi 2, which is quite a slow machine. You're running on a NAS which is also slower than my dev machine. Maybe a pause after the database update completes would help?

Do you still have a copy of the pre-update database (a backup perhaps) so you could run the upgrade again? If so I could send you some extra debugging code to try and pin it down.

**Comment by uzegonemad** [comment] 2017-02-14 18:32
After some sleep though, I'm realizing that my changing `UPDATE_MSG` is unrelated. I don't work much with python but `''` and `None` should both evaluate to false, right? So it seems like the restart button in LL didn't affect the lock/loop, but restarting the Jail did.

I don't have a database backup unless LL takes automated backups (I like to live dangerously), but I think I could recreate similar conditions. I'll start at 49a0edea6f132aec48f761e7467589280ab1071e, configure & back up the db, and run through the upgrade again to see if it's repeatable on my environment.

FWIW my server is running a i7-4790k (quad core 4ghz) with 8gb ram, although LL is running in a jail so I'm not sure what its virtual resources are. (Honestly it could be comparable to a pi.)

**Comment by philborman** [comment] 2017-02-14 19:11
Would be good to track it down if we can, but if it's a lot of work it
might not be worth the effort, see if we get more reports of the issue that
might help narrow down where the problem is. I will add more debugging
messages in the database functions to.

You're right about empty string and None both evaluating to False. The
"main loop" shows a different index page if UPDATE_MSG is True, and the
database updater feeds different messages into UPDATE_MSG to show progress,
finally setting UPDATE_MSG = '' on completion.

Interesting that the "Database is locked" message didn't appear until AFTER
the "database upgrade is complete" message. In the previous report (pi 2
user), the "database is locked" message appeared between upgrade 12 and 13.

**Comment by philborman** [comment] 2017-02-15 11:19
Ok, think this might be fixed now. I _think_ the problem was that the search tasks were being started while the database update was still in progress. I have moved the code that starts the search tasks until _after_ the update completes. Will push a new version in the next hour or two, just running some more tests. would be good to know if this fixes it.

**Comment by uzegonemad** [comment] 2017-02-16 16:22
Awesome! I'll have time this weekend to try to recreate my environment and test again.

**Closed** 2017-03-05 11:33 UTC
