### ISSUE TITLE
Issue running update.

### ISSUE THREAD

**Issue by mrsrockguru** [DobyTang/LazyLibrarian#1215] opened 2018-02-11 14:16 UTC
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
ad2145999866d53c570bd73d5c5d4ef18454a61c 
### Operating system used (windows, mac, linux, NAS type)
Ubuntu 17.10
### Interface in use (default, bookstrap)
Bookstrap
### Which api (Goodreads, GoogleBooks, both)
Goodreads
### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Git
### Relevant debug log with api keys and any passwords redacted

When I try to run update it fails, with this output to the debug log.

Updating ad214599..b53cbb15

11-Feb-2018 13:51:54 - ERROR   :: MAIN : versioncheck.py:logmsg:43 : (update) Unable to update from git: Aborting
11-Feb-2018 13:51:54 - INFO    :: MAIN : versioncheck.py:logmsg:45 : (update) Output: From https://github.com/DobyTang/LazyLibrarian
 * branch              master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	data/interfaces/bookstrap/config.html
	data/interfaces/legacy/config.html
	lazylibrarian/__init__.py
	lazylibrarian/api.py
	lazylibrarian/bencode.py
	lazylibrarian/bookwork.py
	lazylibrarian/cache.py
	lazylibrarian/calibre.py
	lazylibrarian/common.py
	lazylibrarian/csvfile.py
	lazylibrarian/database.py
	lazylibrarian/dbupgrade.py
	lazylibrarian/deluge.py
	lazylibrarian/directparser.py
	lazylibrarian/downloadmethods.py
	lazylibrarian/formatter.py
	lazylibrarian/gb.py
	lazylibrarian/gr.py
	lazylibrarian/grsync.py
	lazylibrarian/importer.py
	lazylibrarian/librarysync.py
	lazylibrarian/logger.py
	lazylibrarian/magazinescan.py
	lazylibrarian/manualbook.py
	lazylibrarian/notifiers/__init__.py
	lazylibrarian/notifiers/androidpn.py
	lazylibrarian/notifiers/custom_notify.py
	lazylibrarian/notifiers/nma.py
	lazylibrarian/notifiers/prowl.py
	lazylibrarian/notifiers/pushbullet.py
	lazylibrarian/notifiers/pushover.py
	lazylibrarian/notifiers/telegram.py
	lazylibrarian/notifiers/tweet.py
	lazylibrarian/nzbget.py
	lazylibrarian/postprocess.py
	lazylibrarian/providers.py
	lazylibrarian/qbittorrent.py
	lazylibrarian/rtorrent.py
	lazylibrarian/sabnzbd.py
	lazylibrarian/searchbook.py
	lazylibrarian/searchmag.py
	lazylibrarian/searchrss.py
	lazylibrarian/synology.py
	lazylibrarian/torrentparser.py
	lazylibrarian/transmission.py
	lazylibrarian/utorrent.py
	lazylibrarian/versioncheck.py
	lazylibrarian/webServe.py
	lazylibrarian/webStart.py
	lib/cherrypy_cors.py
	lib/feedparser/__init__.py
	lib/httpagentparser.py
	lib/id3reader.py
	lib/mobi/__init__.py
	lib/oauth2/__init__.py
	lib/pynma/__init__.py
	lib/pynma/pynma.py
	lib/pythontwitter/__init__.py
Please commit your changes or stash them before you merge.
Aborting

**Comment by philborman** [comment] 2018-02-11 16:09
Looks like git has got out of step, or you have done a __serious__ amount of editing.
Git update won't work if it thinks you have local changes.

Assuming your user files (database, cache, config.ini) are not in the lazylibrarian directory the simplest is to delete the lazylibrarian folder and reinstall. 
Alternatively you could "git checkout" each file it complains about, so...
cd into your lazylibrarian folder, then
git checkout data/interfaces/bookstrap/config.html
git checkout data/interfaces/legacy/config.html
etc...

Would be interesting to know how the error came about, git is usually quite robust.

**Comment by mrsrockguru** [comment] 2018-02-11 19:51
Umm, gona play with some options probably a reinstall., however it is worrying it is up untill now we have made no changes to the lazylibrarian install.  Before we do the install is there any files you would like us to send copies of, also we have checked permission in /opt/lazylibrarian and are 775 and ll user is primary system user, so same owner as all other system files.

**Comment by mrsrockguru** [comment] 2018-02-11 20:26
Just pulled a re-install which has installed it to /opt/LazyLibrarian ins system.d and indeed in the readme expects to find installed in /opt/lazylibrarian we came across this issue when we first installed. We renamed the install directory to lower case we are wondering which is correct, we now have both versions sided by side, but are not going to run either until we have confirmation from you as to which one to run and if it is the one installed today installed as /opt/LazyLibrarian which files to edit, as when we first installed following instructions the system.d would not run until we renamed install directory to lower case. Wondering if this is the cause of the failure to update.

**Comment by philborman** [comment] 2018-02-11 21:37
The directory difference could well be the cause, I may have to modify the init scripts.
 
LazyLibrarian doesn't care what directory it's run from, it uses it's "current directory" as it's base,  it isn't hard-coded anywhere. The "current directory" is the one the program is started from, and could be named anything, /opt/LazyLibrarian, /opt/lazylibrarian, /usr/local/bin/lazylibrarian, whatever you like as long as the path in the init default file matches. See the INSTALL.txt file. There are 3 files that need installing to the right places for ubuntu

If you download the zip file from git and unpack it you get a folder called LazyLibrarian-master
If you git clone you get a directory called LazyLibrarian in whatever folder you ran the clone from.

If the current version is in /opt/LazyLibrarian you will either need to rename that directory to /opt/lazylibrarian which is what the supplied init file expects, or edit the line in /etc/default/lazylibrarian to point to the right folder.

Personally I would edit /etc/default/lazylibrarian to point to /opt/LazyLibrarian, that's probably what the next version will use as default.

Sorry for the confusion

**Comment by mrsrockguru** [comment] 2018-02-11 22:11
Thanks will give that a try, and let you know what happens.

**Comment by mrsrockguru** [comment] 2018-02-11 22:29
Edited /etc/default/lazylibrarian, new version running will let you know what happens when the next auto update option arrives.  Now to track down our postprocessing problems, this however seems a two pipe problem and only tobacco in the house damn.

**Comment by philborman** [comment] 2018-02-13 22:15
next update just released, please close this issue if the update works as expected.
There are also postprocessor changes in this release which may alter your postprocessor issue

**Closed** 2018-02-19 13:59 UTC
