### ISSUE TITLE
Unhandled Exception while searching for magazines

### ISSUE THREAD

**Issue by VarunChugh** [DobyTang/LazyLibrarian#579] opened 2017-01-04 03:26 UTC
Get the below error while searching for magazines

Unhandled exception in search_magazines: Traceback (most recent call last): File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/searchmag.py", line 439, in search_magazines myDB.upsert(insert_table, newValueDict, controlValueDict) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/database.py", line 101, in upsert self.action(query, valueDict.values() + keyDict.values()) File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/database.py", line 48, in action sqlResult = self.connection.execute(query, args) OperationalError: no such column: NZBmode

Database error: no such column: NZBmode

**Comment by philborman** [comment] 2017-01-04 09:25
Well, that's a bit of a puzzle. Can't immediately see why. The error 
comes from this line...

myDB.upsert(insert_table, newValueDict, controlValueDict)


insert_table should either be "wanted" or "pastissues" and both those 
tables have a column called NZBmode.

I can't see how we can get to this point with insert_table having any 
other value, and can't see how those tables can be missing a column, so 
I'm stuck.

The last bug was easy to catch as I could reproduce it here, this one I 
can't.
Are you up for a bit of debugging?

**Comment by VarunChugh** [comment] 2017-01-04 09:32
sure, let me know how could I help debug this further.

**Comment by philborman** [comment] 2017-01-04 10:17
We need to know what table lazylibrarian is trying to talk to, and what the
table columns are.
Are you able to edit the python source or use sqlite3?  If not let me know
and I will send you a small test program.
If you're ok with a bit of editing...

Easiest way to get the table name is an extra line in searchmag.py
Just above line 439  myDB.upsert(insert_table, newValueDict,
controlValueDict)
we need to add logger.info("Adding to table %s" % insert_table)

To get the table columns,
sqlite3 lazylibrarian.db
.schema wanted
.schema pastissues
.quit

**Comment by VarunChugh** [comment] 2017-01-04 14:03
I am okay with editing but haven't written a code ever. If you could guide me where to put the piece of code, I can do that. My Lazy Librarian is installed on Freenas. Would you need any other information to guide me?

**Comment by philborman** [comment] 2017-01-04 15:57
Thats fine,  freenas is ok.  Linux based.
Do you know how to ssh into it,  and do you know where your lazylibrarian
database is stored

**Comment by VarunChugh** [comment] 2017-01-05 02:35
I can ssh - yes, but dont know the database of lazylibrarian (should be in the jail somewhere, that shouldn't be hard to find). What do I need to do after that?

**Comment by philborman** [comment] 2017-01-05 08:06
Ssh into the freenas,  find lazylibrarian.db
It is probably in the lazylibrarian folder or in your home folder. Change
to the folder that contains lazylibrarian.db, example
cd /usr/pbi/lazylibrarian-amd64/share/lazylibrarian

then type in these commands... The first one opens the database and your
prompt should change to sqlite>
The next two give us the answers we need,  and the quit takes you back out
of the database.
Note that the commanda all start with a dot.

sqlite3 lazylibrarian.db

.schema wanted

.schema pastissues

.quit


You should get something like this...

sqlite> .schema wanted
CREATE TABLE wanted (BookID TEXT, NZBurl TEXT, NZBtitle TEXT, NZBdate TEXT,
NZBprov TEXT, Status TEXT, NZBsize TEXT, AuxInfo TEXT, NZBmode TEXT, Source
TEXT, DownloadID TEXT);

We are checking for it containing NZBmode TEXT

On Thu, 5 Jan 2017, 03:35 VarunChugh, <notifications@github.com> wrote:

I can ssh - yes, but dont know the database of lazylibrarian (should be in
the jail somewhere, that shouldn't be hard to find). What do I need to do
after that?

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/DobyTang/LazyLibrarian/issues/579#issuecomment-270548641>,
or mute the thread

**Comment by Woody11** [comment] 2017-01-07 07:37
I have the same issue using FreeNAS.

I checked both pastissues and wanted in sqlite. Pastissues is missing NZBmode. I verified this by adding NZBmode as a column in table pastissues and it's now working as intended

**Comment by philborman** [comment] 2017-01-07 07:44
Excellent news, at least you have found it.

We just need to figure out how the table is missing the column now. Did the
table somehow get created with a column missing, or did a database upgrade
fail. I'm fairly sure the nzbmode column is not a recent addition though?

Is yours a fresh database install, or an upgrade from earlier versions?

**Comment by philborman** [comment] 2017-01-07 07:50
Another thought, as you are both on freenas, are you installing from git or a zip from the lazylibrarian  git page,  or is it a package provided by a 3rd party for freenas?

**Comment by Woody11** [comment] 2017-01-07 09:22
It's a fresh install, however it is installed from a package provided by a 3rd party. I'm trying to locate the owner of the package to get it updated to the latest git commit. In the meantime i guess the only option is for those using freenas is to manually update the table or to manually install from git

**Comment by philborman** [comment] 2017-01-07 10:03
Not necessarily, i should be able to detect it and upgrade. Will post a new
release later today

**Comment by philborman** [comment] 2017-01-07 12:24
ok, found the problem. It looks like you could be missing some other columns in the pastissues table too. The freenas version is quite old, and we weren't upgrading the database correctly. Should be fixed now.

**Closed** 2017-01-08 20:09 UTC

**Comment by VarunChugh** [comment] 2017-01-12 01:53
Thanks a ton. I was out of the country with very limited internet access, couldn't help this time around.
