### ISSUE TITLE
Import to read lists from Goodreads, amazon etc

### ISSUE THREAD

**Issue by nigelhooper** [DobyTang/LazyLibrarian#193] opened 2015-12-05 22:29 UTC
Would it be possible to import to read lists from from public wishlist sites such as Good reads and Amazon etc?  Luzme.com does it and so it is clearly possible with a bit of work.

Failing that Goodreads have an export to csv which includes ids, titles, authors, isbns etc

Thanks for all your hard work, it is really good to see that people are not willing to let this project die.

**Comment by philborman** [comment] 2015-12-06 22:08
Import a list from csv looks easy enough, I will have a look over the next day or two. 
Just struggling with python3 compatibility at the moment. It seems that Ubuntu 16.04 will drop python2 support in April.

**Comment by philborman** [comment] 2015-12-09 21:58
ok, added csv import and export now. Import any .csv from "alternate directory", adding any new authors found in the csv, and marking books found in the csv as "wanted" so they get picked up on next postprocess job (or you can force postprocess after importing)

Export creates a named/timed .csv in the "alternate directory" of any books in your library marked as wanted. Only exports bookid/author/title/isbn  but can be used to re-import if you have to rebuild your library from scratch, or should be enough to pass to goodreads as a reading list

**Comment by nigelhooper** [comment] 2015-12-13 09:22
Awesome, I will try to test it over Christmas and report back.

**Comment by nigelhooper** [comment] 2015-12-13 09:56
I have had a quick try of the import, It is finding some authors and books but I am getting an error "Unable to complete the import: 'ascii' codec can't decode byte 0xae in position 85: ordinal not in range(128)" which is causing it to stop.

Is it possible to either
1) list the book, author, line number etc that is causing the error?
2) Skip over the entry that is causing the error?

Thanks.

**Comment by philborman** [comment] 2015-12-13 12:09
ok, it's an accented character in an author or book name. Most of them 
are trapped by the routines in common.py and formatter.py

I've been doing some work on tidying these up recently as there were 
multiple functions doing broadly the same job, not sure if I've broken 
something, or if it's already fixed in my current version.

I guess you are hitting this on importing a csv, rather than exporting. 
Any chance you can post the .csv that's causing the problem so I can try 
to replicate it?

**Comment by nigelhooper** [comment] 2015-12-13 20:46
The error above is occurring when I import the attached csv file.  The file is an edited version of my goodreads export.  The original file was UTF-8 and so I have:
1) deleted all columns except Book Id,Title,Author,ISBN,ISBN13
2) sorted by Author
3) Saved as ANSI

Unless I am mistaken it doesn't appear to be importing the books in the order listed in the file (by author), which makes it a little harder for me to determine which entry is causing the problem.

I have scanned through the file and couldn't see any accented characters.

I have had to change the extension from csv to txt to allow the upload.

[goodreads_library_export.txt](https://github.com/DobyTang/LazyLibrarian/files/60595/goodreads_library_export.txt)

**Comment by philborman** [comment] 2015-12-13 21:17
Thanks for that, found it.
The book causing the problem is Practical Guidelines and Best Practices 
for Microsoft® Visual Basic® and Visual C#® Developers,Francesco Balena

The registered trademark symbol is the culprit, not getting filtered out 
correctly. (R with a ring around it).  I will fix this in the next 
release, probably in the next couple of days.

The book importing and library scanning is done in the order lines 
appear in the csv file, but if the author wasn't already in the database 
we ask GoodReads for a list of all of that authors books, and that list 
is (I think) in date-of-publication order, so won't match the csv order. 
LazyLibrarian processes all of that authors books before looking at the 
next line in the csv file, so you see lots of lines relating to books 
you haven't asked about, but that are by an author you asked about.

If you turn on debugging messages or run LazyLibrarian.py --debug from 
the console you will see a lot more about the process.

**Comment by philborman** [comment] 2015-12-13 21:40
Hmm,
Forget my earlier comment about book ordering, seems the CSV import is 
ordered on the bookid, which is the first field.

Phil.

**Comment by nigelhooper** [comment] 2015-12-13 21:45
Thanks again.  I have temporarily deleted the book and the import is getting much further, but it is erroring again with "Unable to complete the import: 'ascii' codec can't decode byte 0xe9 in position 12: ordinal not in range(128)", my money is on : Sami Hyypiä  - revised file attached.

I have tested the export and it lists gives me a csv file with 303 entries, I haven't checked the details yet but I have a couple of problems:
1) The export filename you are using has colons in it e.g Wanted - 2015-12-13 21:27:49.csv windows doesn't allow these in the filename can you replace them with e.g. full stops underscores or dashes e.g. Wanted - 2015-12-13 21.27.49.csv
2) I can't get the books page to show me just my wanted books and so I can't check the count of books on that page against the csv file

[goodreads_library_export_20151213v2.txt](https://github.com/DobyTang/LazyLibrarian/files/60613/goodreads_library_export_20151213v2.txt)

**Comment by nigelhooper** [comment] 2015-12-13 21:57
I have deleted the "Sami Hyypiä" book and it is still erroring, its probably "Barça: The Making of the Greatest Team in the World"

Do you want me to keep listing the entries that it has problems with?

**Comment by philborman** [comment] 2015-12-13 22:04
On 13/12/15 22:45, nigelhooper wrote:
>
> Thanks again. I have temporarily deleted the book and the import is 
> getting much further, but it is erroring again with "Unable to 
> complete the import: 'ascii' codec can't decode byte 0xe9 in position 
> 12: ordinal not in range(128)", my money is on : Sami Hyypiä - revised 
> file attached.
>
Yep, I would guess that too. Should be ok with accented author names, 
not so good in book titles. The one fix should solve it all. If you want 
to try it yourself, just edit postprocess.py, somewhere around line 567 
where it says
bookname = content[bookid]['Title']
change this to
bookname = formatter.latinToAscii(content[bookid]['Title'])

Wouldn't harm to do the same to authorname on line  554 as well just to 
be sure.

> I have tested the export and it lists gives me a csv file with 303 
> entries, I haven't checked the details yet but I have a couple of 
> problems:
> 1) The export filename you are using has colons in it e.g Wanted - 
> 2015-12-13 21:27:49.csv windows doesn't allow these in the filename 
> can you replace them with e.g. full stops underscores or dashes e.g. 
> Wanted - 2015-12-13 21.27.49.csv
>
ok, fixed.
>
> 2) I can't get the books page to show me just my wanted books and so I 
> can't check the count of books on that page against the csv file
>
When the import process completes it will print details for you in the 
log file.
I think of the import process fails the wanted flags are not all getting 
updated correctly. Should be fine when the import completes.

**Comment by nigelhooper** [comment] 2015-12-13 22:48
I have got to call it a night but will go back through the thread when I get a chance and follow up on any actions and post back.

**Closed** 2016-01-03 19:10 UTC
