### ISSUE TITLE
Manual Post Processing -- Folder name

### ISSUE THREAD

**Issue by DarkSir23** [DobyTang/LazyLibrarian#1218] opened 2018-02-12 03:23 UTC
For some reason some of my books aren't processing.  I haven't had time to investigate why, and I'll return to that in the near future.

However, I've built up a bunch books that I'd like to process, though they've been renamed to .fail folders.

So, my question is this:  Is there a way to manually post-process the contents of a folder, by manually naming the folder to the goodreads ID of the book, or something like that?

**Comment by philborman** [comment] 2018-02-12 08:49
Yes there is but it's not straightforward. Would be worth seeing why the folder was renamed to .fail
Try removing the .fail on the end of the name and run postprocessor with debug on and you should see what the problem is.  Will post details on how to rename with the id later, need to think about it.

**Comment by DarkSir23** [comment] 2018-02-12 13:57
I'm thinking a corrupt metadata.db has been doing me in.  However, I'm still interested in manual post processing with a forced goodreads ID :)

**Comment by philborman** [comment] 2018-02-12 15:57
ok, to force the goodreads id to be used, name the folder in download directory to include the goodreads ID like this...

/download/dir/Jeff Abbott - The Last Minute LL.(number)/

The only part we look for is LL.() with a number in the brackets. The author and title are tried first if the book is marked "Wanted". The number is the goodreads ID which you can find by hovering over the book cover in lazylibrarian (/cache/book/number.jpg) or going to the books manual page where the bookid is part of the url

**Comment by DarkSir23** [comment] 2018-02-12 16:08
Perfect.  Can that force a a specific version of the book?  Like, if the book isn't currently in the LL database?

**Comment by philborman** [comment] 2018-02-12 16:17
No, author and book must be in the database already or it fails (renames with  .fail on the end)
If the author or book are not in the database, put the book into the "alternate" directory. No need to mess with the bookid there, it will import based on tags in the book file, or an opf if present. Two options with importing that way, both on the "manage" page, both add the author and book to the database if not present...
"Include books" creates database entries for the books without moving them
"Import books" copies/moves the books into the lazylibrarian library folder structure first.

**Comment by DarkSir23** [comment] 2018-02-12 16:18
Hmm... then is there a way to specifiy a specific edition of book when adding a title to LL?

**Comment by philborman** [comment] 2018-02-12 17:19
No, the people who upload books are generally not good at specifying editions. If you want a specific edition the best way currently is to do a manual search and pick the one you want from the list of results

**Comment by DarkSir23** [comment] 2018-02-12 17:28
Ok, let me clarify...  When I search for a book in LL, I only usually find one result, even if there are 30 editions of the book.  I like to use the Kindle version of a book, as is usually matches the page count, or comes close.  However, LL doesn't seem to discern which version of a book it's importing into the database from Goodreads.

**Comment by philborman** [comment] 2018-02-12 18:32
Ah, I see what you mean.
We ask goodreads for a list of the authors books, which is the same data as you get from looking at the goodreads author page, eg https://www.goodreads.com/search?q=tom+holt
Each book is listed once, however many editions goodreads knows about, and that's the bookid we collect. Not sure how goodreads decides which one is the "main edition" to give us. Each edition within goodreads has a different id, we could delve deeper to find them, but only by scraping the html pages which they frown upon. The edition info doesn't seem to be made available in their api.

**Comment by DarkSir23** [comment] 2018-02-13 01:24
Yeah, that's not worth the trouble.  Would it be possible to allow one to change the goodreads ID via the edit screen?  I know that means changing an actual key field, and possibly renaming cached image files...

**Comment by DarkSir23** [comment] 2018-02-13 01:26
Or alternatively, add goodreads ID as one of the search methods? :)

**Comment by philborman** [comment] 2018-02-13 17:30
Goodreads id as a search won't work as the search tasks (nzb and torrent sources) don't know what to do with a goodreads id. Editing the goodreads id on the edit screen is a possible addition, we can handle changing the links if the id changes. I found a goodreads api call to get the work_editions for a goodreads bookid, probably returns the info we want, but it's not normally available,  invite only.  Would be better if we could select from a list rather than have the user type in a new ID number, though we could check that the new number matches a goodreads book with the same or similar title?

**Comment by philborman** [comment] 2018-02-13 18:58
Another thought, do you use lazylibrarian goodreads sync?
I think if you remove the books with editions you don't want from the lazylibrarian database, then add the editions you want to a goodreads shelf, you can sync your goodreads shelf to lazylibrarian and it should import the info for the specified editions.  Probably best to sync as "read" books so you don't try to download them all. You might need to run libraryscan afterwards to create links to the books you've already got (uses author/title to match, if no matching bookid)

**Comment by DarkSir23** [comment] 2018-02-19 14:59
I've not tried the goodreads sync, no.  Looking into it now.  I assume I need to be set up as a developer.  I've got an API Key and Secret, but I'm not sure which secret that's supposed to be.  Oauth or Goodreads.  And do you know where I find the other?  

Thanks

**Comment by DarkSir23** [comment] 2018-02-19 15:05
Nevermind, I figured it out :)

**Comment by DarkSir23** [comment] 2018-02-19 18:15
Hmm, so doing that added all of my wanted books to goodreads, but it doesn't look like it worked in the other direction.  The 4 books I added to goodreads don't seem to have gone to LL, and now they're gone from the goodreads shelf, too.

**Comment by DarkSir23** [comment] 2018-02-20 01:48
Just so I understand how this works... if I add a book to the wanted shelf in goodreads, it will add the book and/or author to LL, if they don't exist?

**Comment by philborman** [comment] 2018-02-20 08:06
Yes, the idea is the book and author get added if it not already there.
Statuses are variable. 
If the author is added, they get marked as "paused" and we don't grab details of all of their books, just the one book on the shelf or in a wishlist/csv import, unless you tick "include other books by new authors" in config. If the author was already in the database, author status doesn't change.
If the book is new it gets marked as "wanted", ignoring the "new authors book status". If the book was already in the database it only gets marked wanted if not already there.

**Comment by DarkSir23** [comment] 2018-02-20 11:49
Ok, so after I cleaned out the wanted shelf on both ends, I added a new author and book on goodreads end, but neither was added to LL.  I’ll add another and monitor the logs, and see if I can spot what’s happening.

**Comment by philborman** [comment] 2018-02-20 12:58
It's not very quick due to the goodreads api limits on frequency. You might need to run with debug level 3 to get much info back.

**Comment by DarkSir23** [comment] 2018-02-21 04:19
I'm getting this:

20-Feb-2018 22:19:40 - ERROR   :: GRSync : grsync.py:grsync:657 : Unhandled exception in grsync: Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/grsync.py", line 510, in grsync
    gr_shelf = GA.get_gr_shelf_contents(shelf=shelf)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/grsync.py", line 294, in get_gr_shelf_contents
    content = self.getShelfBooks(current_page, shelf)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/grsync.py", line 368, in getShelfBooks
    raise Exception('Failure status: %s for page %s' % (response['status'], page))
Exception: Failure status: 403 for page 1

I know 403 is Forbidden for some reason.  Is there a way to dig deeper?

**Comment by DarkSir23** [comment] 2018-02-21 04:33
Nevermind... I made my profile private when I accidentally added 1500 books to my shelf.  Didn't realize I wouldn't be able to get my shelves with the api, if I did that.

**Comment by DarkSir23** [comment] 2018-02-21 04:36
Request, while I'm throwing API requests all over the place:  Could grSync be added as an API call?

**Comment by philborman** [comment] 2018-02-21 09:38
ok, made the exception an error message now so it doesn't complain too much.

grsync api call in next release, probably later today

**Comment by DarkSir23** [comment] 2018-02-21 13:58
You rock :)

**Closed** 2018-02-23 12:24 UTC
