### ISSUE TITLE
Search fails for magazines

### ISSUE THREAD

**Issue by abbkos** [DobyTang/LazyLibrarian#1442] opened 2018-05-28 19:31 UTC
### Source of LazyLibrarian installation : git

Lazylibrarian searches and finds issues but all of them fails like `below:`
```
28-May-2018 22:07:15 - DEBUG   :: SEARCHALLMAG : searchmag.py:search_magazines:258 : Magazine title matched Linux Format Uk for Linux Format UK TruePDF June 2018
28-May-2018 22:07:15 - DEBUG   :: SEARCHALLMAG : searchmag.py:search_magazines:299 : Issue 2018-06-01 (regex 3) for Linux Format UK TruePDF June 2018 
28-May-2018 22:07:15 - DEBUG   :: SEARCHALLMAG : searchmag.py:search_magazines:386 : Magazine Linux Format UK TruePDF June 2018 failed: Expecting issue number
28-May-2018 22:07:15 - DEBUG   :: SEARCHALLMAG : searchmag.py:search_magazines:392 : This issue of Linux Format UK TruePDF June 2018 is unknown age; skipping.
28-May-2018 22:07:15 - DEBUG   :: SEARCHALLMAG : searchmag.py:search_magazines:258 : Magazine title matched Linux Format Uk for Linux Format UK TruePDF May 2018
28-May-2018 22:07:15 - DEBUG   :: SEARCHALLMAG : searchmag.py:search_magazines:299 : Issue 2018-05-01 (regex 3) for Linux Format UK TruePDF May 2018 
28-May-2018 22:07:15 - DEBUG   :: SEARCHALLMAG : searchmag.py:search_magazines:386 : Magazine Linux Format UK TruePDF May 2018 failed: Expecting issue number
28-May-2018 22:07:15 - DEBUG   :: SEARCHALLMAG : searchmag.py:search_magazines:392 : This issue of Linux Format UK TruePDF May 2018 is unknown age; skipping.
28-May-2018 22:07:15 - DEBUG   :: SEARCHALLMAG : searchmag.py:search_magazines:258 : Magazine title matched Linux Format Uk for Linux Format UK TruePDF April 2018
28-May-2018 22:07:15 - DEBUG   :: SEARCHALLMAG : searchmag.py:search_magazines:299 : Issue 2018-04-01 (regex 3) for Linux Format UK TruePDF April 2018 
28-May-2018 22:07:15 - DEBUG   :: SEARCHALLMAG : searchmag.py:search_magazines:386 : Magazine Linux Format UK TruePDF April 2018 failed: Expecting issue number
28-May-2018 22:07:15 - DEBUG   :: SEARCHALLMAG : searchmag.py:search_magazines:392 : This issue of Linux Format UK TruePDF April 2018 is unknown age; skipping.
```

I attached logs only for a single magazine. Problem is common for many magazines that I tried.
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/2045997/debug.zip)
[lazylibrarian.log](https://github.com/DobyTang/LazyLibrarian/files/2045998/lazylibrarian.log)

**Comment by philborman** [comment] 2018-05-28 19:56
Problem seems to be we are expecting an issue number but getting a date instead. Question is _why_ we think there should be an issue number. I'm guessing these are newly added magazine titles, not ones where you already have some issues?

Are you able to do a little editing to help track the problem down?
Adding a debug line on the code would help a lot as I can't reproduce the problem here

**Comment by philborman** [comment] 2018-05-29 15:42
Just need a line adding into searchmag.py
I think the problem is there is an invalid control date somehow. Need to know what the bad value is.

Line 335 says    if control_date is None:  # we haven't got any copies of this magazine yet
Just above that if you put    logger.debug("Control Date [%s]", % control_date)
that will show us what's going on.

Please keep a copy of the original searchmag.py so you can put it back after testing, otherwise lazylibrarian update mechanism will not work.  Thanks.

**Comment by abbkos** [comment] 2018-05-30 15:51
I did like this (as I understood):
1) I selected and removed the magazine which was pre-downloaded and added by library-scan.
2) Same magazine was added againg by library-scan
3) This time search function found missing magazines with:
`Control Date [2018-03-01]` instead of `Control Date [March 2018]`

So, this means We should do librar-scan twice for pre-downloaded magazines as workaround.

**Comment by philborman** [comment] 2018-05-30 16:48
I don't think so, one scan should work but if it happens again at least we know the workaround is ok.
I am not sure how the control date originally was wrong. Were the pre-downloaded magazines imported with an earlier version of lazylibrarian?

**Comment by abbkos** [comment] 2018-05-30 16:51
No, I added nzb file to nzbget manually, and then moved downloaded files (as directory) to lazylibrarian's magazines folder.

**Comment by philborman** [comment] 2018-05-30 16:52
same version of lazylibrarian, or an earlier one?
Just wondering if the version of libraryscan was different as the current version works

**Comment by abbkos** [comment] 2018-05-30 16:55
Probably earlier version, because I tried search after I update (by git) lazylibrarian

**Comment by philborman** [comment] 2018-05-30 19:13
Ok I will close this for now, but if the problem comes back please reopen it.

**Closed by philborman** 2018-05-30 19:13 UTC
