### ISSUE TITLE
Unicode problem on Library Scan

### ISSUE THREAD

**Issue by theguardian** [DobyTang/LazyLibrarian#155] opened 2015-10-21 21:27 UTC
Tried the "Library Scan" feature for the first time today. It got through a few authors but then errored out with this:

21-Oct-2015 14:08:35 - INFO :: DBIMPORT : [Billy Crystal] Author update complete
21-Oct-2015 14:08:35 - ERROR :: DBIMPORT : Fatal error executing SELECT BookID FROM books where AuthorName=? and BookName=? :: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

**Comment by philborman** [comment] 2015-10-22 18:04
Can't reproduce that here. I've added author "Billy Crystal" with goodreads and google books and works fine. The error is being generated in  the function "find_book_in_db" with parameters "author" and "book" . "author" has already been used in a call to myDB.action before we get to this point in the code, so I guess it's the book name it objects to. The bookname is sanitised with unidecode before we reach this point. The version of unidecode you uploaded is much smaller than mine, (has far fewer files x0??.py) maybe that's the problem?  I have uploaded my version to master, can you try that and see if the problem persists, or try my branch??  I would recommend deleting the caches in case of conflict too. You might get more help in debug mode, there should be a line  "file meta [%s] [%s] [%s] [%s]" or "book meta [%s] [%s] [%s] [%s]" which will show the bookname it doesn't like. As far as I can see the names should be unicode safe.

**Comment by theguardian** [comment] 2015-10-22 20:42
The book that failed was titled `Still Foolin' 'Em` I'm guessing the `' '` is the culprit. It was able to continue after I removed that file. However I'm now getting the following error:

```
22-Oct-2015 13:35:50 - INFO :: CP Server Thread-4 : [/directory] Now scanning subdirectory /Reza Aslan/Zealot
22-Oct-2015 13:35:50 - DEBUG :: CP Server Thread-4 : No metadata file in /directory/Reza Aslan/Zealot
22-Oct-2015 13:35:50 - ERROR :: CP Server Thread-4 : Unable to complete the scan: list index out of range
```

**Comment by philborman** [comment] 2015-10-23 07:45
The Billy Crystal book imported ok here, the code at line 430 in gr.py 
should sanitise the name using unidecode. Your version of unidecode is 
different to mine, as I said in an earlier reply.

The Reza Aslan book seems to be a different problem. Not enough info to 
know where the "list index out of range" error is being generated. Need 
to add more debugging code.

We can't find "/Reza Aslan/Zealot/metadata.opf" (does it exist/is it 
readable) so we call  get_book_info() near the top of librarysync.py. 
Which path we take through that depends on whether the book is an epub 
or a mobi and the logs don't say which. We either hit the error in 
get_book_info(), or the dictionary returned from there isn't as 
expected, as we don't reach the debug line giving the "book meta".

Would be useful if you could give me a link to the book so I can look at 
the embedded metadata, or maybe add some print statements to 
get_book_info() to narrow down where it fails?

**Comment by philborman** [comment] 2015-10-26 15:25
Hmm, seems the <where AuthorName=? and BookName=?> type of parameter passing to the database doesn't like characters > 127 in the ascii string. I have rewritten all of the database calls to use 
calls like  <where AuthorName="%s" and BookName="%s">  and this seems to work fine. Will hit a problem if author or book name contain "   but these should all be filtered out.  Maybe it would be better if the database held unicode instead of ascii?  The database field type is TEXT  but database functions return type str.

**Comment by philborman** [comment] 2015-11-06 21:22
May have found the "/Reza Aslan/Zealot/metadata.opf"  issue. The metadata is probably incomplete, ie there is metadata there, but it doesnt have all the 4 fields we need (author,title,language,isbn)
I have added code to cater for this now.

**Comment by theguardian** [comment] 2015-11-28 06:16
I'm still getting errors on Library Scan.

```Unable to complete the scan: list index out of range```

**Comment by philborman** [comment] 2015-11-28 08:43
I guess it's still the metadata scanning, If I can't see anything obvious
in the code I will add some more debugging messages to see if we can track
it down

**Comment by philborman** [comment] 2015-11-28 15:38
I have added more error trapping in the libraryscan.py file, and put try/except around the calls to the metadata scanning function. Hopefully this will fix it, or at least show us where it's failing. 
I suspect it's a book with metadata we can't parse correctly. I that case if we trap the error we can just go from title/author and ignore the metadata, or maybe work out how to parse it properly.
The new version is in my git repository,  https://github.com/philborman/LazyLibrarian.git
If you are on dobytang master, only the librarysync.py file has changed.
Could you let me know if this fixes it, if so I will send a pull request to add it to dobytang master.
Many thanks.

**Comment by nncrypted** [comment] 2015-11-28 16:35
I created a branch called dev off the master if you want to use it for testing go ahead or if you want ppl to switch to your branch you can do that to what ever is easiest for you and the community.

**Comment by philborman** [comment] 2015-11-28 17:02
I don't have write access to dobytang, so it's easier for me to treat my git as testing, and put pull requests in when features are added. I have a couple of users on different systems who use my git to test before I ask for the code to be merged.

**Comment by nncrypted** [comment] 2015-11-28 17:29
Ok what ever is best for you. If I could give you write access I would but I'm not sure I know how even if I could.

**Closed** 2016-08-10 20:38 UTC
