### ISSUE TITLE
Does not start after upgrading today on freenas

### ISSUE THREAD

**Issue by VarunChugh** [DobyTang/LazyLibrarian#1071] opened 2017-10-13 04:50 UTC
After trying to upgrade to the latest commit today, LL does not start up. If I log in on my FreeNAS jail and try to start the service I get the error below

root@lazylibrarian_2:/ # service lazylibrarian start
Starting lazylibrarian.
Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibrarian.py", line 14, in <module>
    import lazylibrarian
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/__init__.py", line 32, in <module>
    from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/postprocess.py", line 26, in <module>
    from lazylibrarian import database, logger, utorrent, transmission, qbittorrent, \
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/utorrent.py", line 25, in <module>
    from lazylibrarian.common import USER_AGENT
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/common.py", line 29, in <module>
    import requests
ImportError: No module named requests
/usr/local/etc/rc.d/lazylibrarian: WARNING: failed to start lazylibrarian

**Comment by philborman** [comment] 2017-10-13 07:06
Duplicate of #1070

**Closed by philborman** 2017-10-13 07:06 UTC
