### ISSUE TITLE
is too old (1 days)

### ISSUE THREAD

**Issue by brinkdogg** [DobyTang/LazyLibrarian#962] opened 2017-08-02 00:06 UTC
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 822a26a2ed1bac4079d7023994c392e6e33273c1 : Latest Version: 822a26a2ed1bac4079d7023994c392e6e33273c1
### Relevant debug log 

Bryson, Bill - A Short History of Nearly Everything [pdb] is too old (1 days) Pretty much for everything I search for
 Life.and.Times.of.the.Thunderbolt.Kid .A.Memoir.The.-.Bill.Bryson is too old (1 days)
An so on!

is there a manual setting for this somewhere?

**Comment by VarunChugh** [comment] 2017-08-02 02:32
@brinkdogg I was getting the same, I set the 'Retention Max Age:' under downloaders to a very large number. Looks like the 0 setting is not working as intended.

**Comment by brinkdogg** [comment] 2017-08-02 05:56
I'm not seeing that option.

**Comment by philborman** [comment] 2017-08-02 08:34
I forgot to allow for zero as a retention age. Your nzb provider will only store files for a certain number of days, so a limit is useful, but if you don't set one it should just allow any age. That part is fixed now, but there is another possibility, bith give the same result (age 1) 
Could be your nzb provider does not send a date, or might send a date in a format we don't recognise. Can you turn debug logging on and look for a line just before the Bill.Bryson is too old (1 days) message, saying something like 'Unable to get age from [should be a date]  and an error message'
If that's what the problem is the current fix won't work for you, we need to fix it so we understand the [should be a date] part.

**Comment by Code-Slave** [comment] 2017-08-02 17:04
Im getting this same stuff now. It may be nzbhydra related too, as every book is too old and in nzbhydra there is no retention setting ive seen so far

**Comment by brinkdogg** [comment] 2017-08-03 04:06
I'm using nzbhydra as well, so this could be very much related to how it sends dates. But an issue has come up after the git pull. 

Aug 02 21:32:33 utopia lazylibrarian[41902]:  * Starting LazyLibrarian
Aug 02 21:32:33 utopia lazylibrarian[41902]: Traceback (most recent call last):
Aug 02 21:32:33 utopia lazylibrarian[41902]:   File "LazyLibrarian.py", line 15, in <module>
Aug 02 21:32:33 utopia lazylibrarian[41902]:     from lazylibrarian import webStart, logger, versioncheck, dbupgrade
Aug 02 21:32:33 utopia lazylibrarian[41902]:   File "/opt/lazylibrarian/lazylibrarian/webStart.py", line 20, in <module>
Aug 02 21:32:33 utopia lazylibrarian[41902]:     import requests
Aug 02 21:32:33 utopia lazylibrarian[41902]: ImportError: No module named requests
Aug 02 21:32:33 utopia lazylibrarian[41902]:    ...fail!
Aug 02 21:32:33 utopia systemd[1]: lazylibrarian.service: Control process exited, code=exited status=1
Aug 02 21:32:33 utopia systemd[1]: Failed to start LSB: starts instance of LazyLibrarian.

**Comment by philborman** [comment] 2017-08-03 07:45
The "ImportError: No module named requests" is a new bug, I needed requests for some code I was trying for user accounts, stripped the user account stuff out as it's not ready, but left the import line in. requests is not a standard python module on all systems.  Just pushed a fix for that part. 

The date issue was (maybe) fixed yesterday, but with the missing "requests" you haven't been able to test the latest version. code_slave comment above is still on the old version.

**Comment by Code-Slave** [comment] 2017-08-03 14:44
Ill not be able to test for a day or so. rebuild my whole home lab into a beastly unraid server. Should be done by the weekend

**Comment by brinkdogg** [comment] 2017-08-03 18:02
New pull works, nice work! nzbhydra is working as well!

DEBUG :: SEARCHBOOK : Successfully connected to NZBget
Aug 03 11:58:32 utopia lazylibrarian[133296]: 03-Aug-2017 11:58:32 - INFO :: SEARCHBOOK : Sending NZB to NZBget
Aug 03 11:58:32 utopia lazylibrarian[133296]: 03-Aug-2017 11:58:32 - DEBUG :: SEARCHBOOK : URL: http://*****:*****@xxx.xxx.xxx.xxx:6789/xmlrpc
Aug 03 11:58:32 utopia lazylibrarian[133296]: 03-Aug-2017 11:58:32 - DEBUG :: SEARCHBOOK : NZB Version 19
Aug 03 11:58:33 utopia lazylibrarian[133296]: 03-Aug-2017 11:58:33 - DEBUG :: SEARCHBOOK : NZB sent to NZBget successfully
Aug 03 11:58:33 utopia lazylibrarian[133296]: 03-Aug-2017 11:58:33 - DEBUG :: SEARCHBOOK : Nzbfile has been downloaded from http://xxx.xxx.xxx.xxx:5075/getnzb?apikey=xxxxxxxxxxxxxxxxxxxxxxx&searchresultid=3a13a99d86c8d1d35bb57a1a37b0e42bf61585cd
Aug 03 11:58:33 utopia lazylibrarian[133296]: 03-Aug-2017 11:58:33 - INFO :: SEARCHBOOK : Downloading eBook Bill Bryson - Made in America LL.(10541) from http://xxx.xxx.xxx.xxx:5075

**Comment by philborman** [comment] 2017-08-03 18:11
I'm getting quite good at fixing bugs I've introduced ;-)

**Closed by philborman** 2017-08-03 18:11 UTC
