### ISSUE TITLE
Windows 10 UnicodeEncodeError

### ISSUE THREAD

**Issue by Iamacamel** [DobyTang/LazyLibrarian#1338] opened 2018-04-19 07:58 UTC
First of all a great project.
I am running on Windows 10 with latest Python 3 (64 bit)  and get all sorts of UnicodeEncodeError for all sorts of different characters when using the program. u2032 u1ec7 
I googled this and have tried the following :
I have tried setting PYTHONIOENCODING=utf-8
I have tried chcp 65001 before launching python from the same CMD window.
I just cannot make these errors go away.

Any suggestions ?

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by philborman** [comment] 2018-04-19 08:13
Looks like you are running lazylibrarian with utf-16 when se are expecting utf-8
Can you go to the lazylibrarian config page interface tab and press the [System Info] button
We need Sys_Encoding: UTF-8
If that's showing utf-16 we need to override it.

**Comment by Iamacamel** [comment] 2018-04-19 08:57
Thank you for the reply.

It appears to be set to UTF-8 

The system info is below.

 

This was run without chcp 65001 

 

 

Startup cmd: ['C:\\Users\\Waldemar Keyser\\AppData\\Local\\Programs\\Python\\Python37\\python.exe', 'C:\\Users\\Waldemar Keyser\\Documents\\LazyLibrarian-master\\LazyLibrarian.py']

Interface: bookstrap

Loglevel: 1

Sys_Encoding: UTF-8

git_repo: lazylibrarian

git_user: dobytang

git_branch: master

latest_version: f1768e0728105ad662a5b0c395f66de76b75330a

git_updated: 1524120929

current_version: f1768e0728105ad662a5b0c395f66de76b75330a

commits_behind: 0

install_type: source

auto_update: 0

Python version: ['3.7.0b3 (v3.7.0b3:4e7efa9c6f, Mar 29 2018, 18:42:04) [MSC v.1913 64 bit (AMD64)]']

Distribution: ('', '', '')

System: Windows

Machine: AMD64

Platform: Windows-10-10.0.16299-SP0

uname: uname_result(system='Windows', node='Keyser', release='10', version='10.0.16299', machine='AMD64', processor='Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')

version: 10.0.16299

mac_ver: ('', ('', '', ''), '')

openssl: OpenSSL 1.1.0f  25 May 2017

requests: 2.12.4

sqlite3: 3.21.0

**Comment by Iamacamel** [comment] 2018-04-19 11:29
Hello there.

I deleted the data base file and then started up LL.

Below is the debug when I searched for Claire Cook

 

I hope this helps.

19-Apr-2018 12:52:17 - INFO    :: MAIN : __init__.py:initialize:569 : Log level set to [1]- Log Directory is [C:\Users\Waldemar Keyser\Documents\LazyLibrarian-master\Logs] - Config level is [1]

19-Apr-2018 12:52:17 - INFO    :: MAIN : __init__.py:initialize:575 : Screen Log set to INFO

19-Apr-2018 12:52:17 - INFO    :: MAIN : __init__.py:config_read:858 : Config file loaded

19-Apr-2018 12:52:17 - INFO    :: MAIN : __init__.py:initialize:619 : Database is version 0, integrity check: ok

19-Apr-2018 12:52:17 - WARNING :: MAIN : __init__.py:initialize:638 : pyOpenSSL: module missing

19-Apr-2018 12:52:17 - WARNING :: MAIN : __init__.py:initialize:638 : OpenSSL missing module/attribute: No module named 'OpenSSL'

19-Apr-2018 12:52:17 - WARNING :: MAIN : __init__.py:initialize:638 : cryptography: module missing

19-Apr-2018 12:52:18 - INFO    :: MAIN : __init__.py:build_bookstrap_themes:1212 : Bookstrap found 16 themes

19-Apr-2018 12:52:19 - INFO    :: MAIN : LazyLibrarian.py:main:204 : Starting LazyLibrarian on port: 5299, webroot ""

19-Apr-2018 12:52:19 - INFO    :: MAIN : webStart.py:initialize:56 : Starting LazyLibrarian web server on http://0.0.0.0:5299/

19-Apr-2018 12:52:22 - INFO    :: DB_UPGRADE : dbupgrade.py:dbupgrade:132 : Creating new database, version 30

19-Apr-2018 12:52:26 - INFO    :: DB_UPGRADE : dbupgrade.py:dbupgrade:363 : Database upgraded to version 30

19-Apr-2018 12:53:21 - INFO    :: WEBSERVER : webServe.py:toggleLog:3064 : Debug log ON, loglevel is 2

19-Apr-2018 12:53:41 - DEBUG   :: GR-RESULTS : gr.py:find_results:63 : Now searching GoodReads API with searchterm: claire cook

19-Apr-2018 12:53:43 - DEBUG   :: GR-RESULTS : cache.py:get_cached_request:183 : CacheHandler: Storing XML 9168f69524b7e1c85e0183f442ac238b for https://www.goodreads.com/search.xml?q=claire+cook&key=ckvsiSDsuqh7omh74ZZ6Q&page=4

19-Apr-2018 12:53:43 - ERROR   :: GR-RESULTS : gr.py:find_results:212 : UnicodeEncodeError finding page 4 of results: 'charmap' codec can't encode character '\u010d' in position 14229: character maps to <undefined>

19-Apr-2018 12:53:43 - DEBUG   :: GR-RESULTS : gr.py:find_results:226 : Found 58 results with keyword: claire cook

19-Apr-2018 12:53:43 - DEBUG   :: GR-RESULTS : gr.py:find_results:228 : The GoodReads API was hit 0 times for keyword claire cook

19-Apr-2018 12:53:48 - DEBUG   :: ADDAUTHOR : importer.py:addAuthorToDB:131 : Adding new author id 88452 to database

19-Apr-2018 12:53:50 - DEBUG   :: ADDAUTHOR : cache.py:get_cached_request:183 : CacheHandler: Storing XML 24aae1424dd216c530f5bf50fa5319f5 for https://www.goodreads.com/author/show/88452.xml?key=ckvsiSDsuqh7omh74ZZ6Q

19-Apr-2018 12:53:50 - ERROR   :: ADDAUTHOR : gr.py:get_author_info:279 : UnicodeEncodeError getting author info: 'charmap' codec can't encode character '\u2605' in position 29160: character maps to <undefined>

19-Apr-2018 12:53:50 - WARNING :: ADDAUTHOR : importer.py:addAuthorToDB:166 : Nothing found for 88452

19-Apr-2018 12:53:50 - DEBUG   :: ADDAUTHOR : gr.py:find_author_id:245 : Searching for author with name: unknown author

19-Apr-2018 12:53:52 - DEBUG   :: ADDAUTHOR : cache.py:get_cached_request:183 : CacheHandler: Storing XML 880294f281c8ff7ad557f99e78e9e1be for https://www.goodreads.com/author/show/14252899.xml?key=ckvsiSDsuqh7omh74ZZ6Q

19-Apr-2018 12:53:52 - ERROR   :: ADDAUTHOR : gr.py:get_author_info:279 : UnicodeEncodeError getting author info: 'charmap' codec can't encode character '\ufb02' in position 21168: character maps to <undefined>

19-Apr-2018 12:53:52 - DEBUG   :: ADDAUTHOR : importer.py:addAuthorToDB:189 : Now adding new author: unknown author to database

19-Apr-2018 12:53:52 - WARNING :: ADDAUTHOR : importer.py:addAuthorToDB:217 : Nothing found for unknown author

19-Apr-2018 12:54:41 - INFO    :: WEBSERVER : webServe.py:toggleLog:3062 : Debug log OFF, loglevel is 1

19-Apr-2018 13:02:26 - INFO    :: POSTPROCESS : postprocess.py:processDir:828 : 0 books/mags processed.

19-Apr-2018 13:02:26 - INFO    :: POSTPROCESS : postprocess.py:processDir:864 : Nothing marked as snatched. Stopping postprocessor.

**Comment by philborman** [comment] 2018-04-19 12:03
Big help, thanks.
The xml data you are getting back from Claire Cook says it should be read as utf-8, this is the start of page 4
<?xml version="1.0" encoding="UTF-8"?>
and yet it contains 
<title>Slepačia polievka pre dušu: Naštartuj svoj život</title>
which is fed to the xml parser as utf-16
The first character error in the log is character '\u010d'  which is the c with caron in Slepačia
Need to figure out why the data fed to the parser is utf-16 when the header says it should be interpreted as utf-8, or maybe we can convert it from 16 to 8 before trying to parse it.

Are you up for a bit of editing, as I can't reproduce it here?

**Comment by Iamacamel** [comment] 2018-04-19 12:07
No problem with editing or log files.

Just remember what I know about Python is dangerous. I am a C and C++ man.

**Comment by Iamacamel** [comment] 2018-04-19 12:18
BTW , what was not mentioned before is that I am running EDGE as my browser.

Not sure if this could have an impact.

**Comment by philborman** [comment] 2018-04-19 12:48
No problem, it's not too hard. Just a couple of things to remember...
1. Keep a copy of the unmodified file so you can put it back later, or lazylibrarian will complain it can't update because of local changes
2. Python is very fussy about whitespace, indents need to be done with spaces, not tabs.

The problem is (I think) we are reading the file data as utf-16 even though the file header says it is utf-8. There are a couple of ways around it, not sure which is best to use...

The file to edit is lazylibrarian/cache.py, line 180 says 
`result, success = fetchURL(url)`
change this to 
`result, success = fetchURL(url, raw=True)`
and line 195 change
`if result and result.startswith('<?xml'):`
to
`if result and result.startswith(b'<?xml'):`
and line 204 change 
`with open(hashfilename, "w") as cachefile:`
to
`with open(hashfilename, "wb") as cachefile:`

That will make sure we read/write raw bytes and hopefully fix new pages. 
For pages already fetched once and cached...
lines 164 says  
`with open(hashfilename, "r") as cachefile:`
change this to 
`with open(hashfilename, "rb") as cachefile:`
and line 166 same change to 
`if result and result.startswith(b'<?xml'):`

**Comment by philborman** [comment] 2018-04-19 12:48
Shouldn't be browser related, this is reading and interpreting xml data

**Comment by Iamacamel** [comment] 2018-04-19 13:32
Still does not function correctly.

Attached is the debug log.

Attached is cache.ph – so you can see if I got the edit correct.

I just edited it in the directory and kept the old one as cache.old (so I can wind back)

**Comment by philborman** [comment] 2018-04-19 21:05
Doesn't matter which python2, anything 2.6 onwards
64/32 bit isn't important either.
The main difference is python3 is unicode based and python2 is bytes based (at least the xml part we are having trouble with)

**Comment by Iamacamel** [comment] 2018-04-20 05:34
Will do.
Tried to find out but what version  does sonarr run on ?

**Comment by philborman** [comment] 2018-04-20 07:11
Sonarr isn't a python program. Runs on net/mono

**Comment by Iamacamel** [comment] 2018-04-20 08:27
Thanks.

Will download 2.7.14 and run it with this a bit later today.

Just to clarify.

1.	I will still run with PYTHONIOENCODING set to utf-8
2.	I will NOT run chcp 65001
3.	Must I use the original cache.ph code or the one with the changes ? (or both)

**Comment by philborman** [comment] 2018-04-20 08:32
> 1.	I will still run with PYTHONIOENCODING set to utf-8

Not important

> 2.	I will NOT run chcp 65001

Probably not important

> 3.	Must I use the original cache.ph code or the one with the changes ? (or both)

cache.py  not cache.ph  and better to run the original...
Actually is that a typo, or were you trying to run cache.ph before, in which case the edits you made were never tested ;-)

**Comment by Iamacamel** [comment] 2018-04-20 08:39
Sorry typo.

Cache.py

**Comment by Iamacamel** [comment] 2018-04-20 09:11
Did the following.

1.	Removed Python 3.x
2.	Installed 2.7.14
3.	Deleted the LL database file
4.	Did NOT clear the cache
5.	Launched LL (see system info below)
6.	Ran same test as before.

See attached log files.

It still shows errors in the log file BUT the information actually updated.

 

 

 

Startup cmd: ['C:\\Python27\\python.exe', 'C:\\Users\\Waldemar Keyser\\Documents\\LazyLibrarian-master\\LazyLibrarian.py']

Interface: bookstrap

Loglevel: 2

Sys_Encoding: UTF-8

git_repo: lazylibrarian

git_user: dobytang

git_branch: master

latest_version: f1768e0728105ad662a5b0c395f66de76b75330a

git_updated: 1524120929

current_version: f1768e0728105ad662a5b0c395f66de76b75330a

commits_behind: 0

install_type: source

auto_update: 0

Python version: ['2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]']

Distribution: ('', '', '')

System: Windows

Machine: AMD64

Platform: Windows-10-10.0.16299

uname: ('Windows', 'Keyser', '10', '10.0.16299', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')

version: 10.0.16299

mac_ver: ('', ('', '', ''), '')

openssl: OpenSSL 1.0.2k  26 Jan 2017

requests: 2.12.4

sqlite3: 3.8.11

pyOpenSSL: module missing

OpenSSL missing module/attribute: No module named OpenSSL.SSL

**Comment by Iamacamel** [comment] 2018-04-20 09:58
Apologies.

 

Please note that in the log file I sent (attached again)  I forgot to delete the old log file before I ran the program.

So the first part is the log for the 19th and shows errors.

The 20th (further down in the log file , looks good from what I can see)

To confirm Python version 2.7.14 with standard cache.py file.

 

From: Waldemar Keyser <waldemar.keyser@gmail.com> 
Sent: Friday, 20 April 2018 11:12 AM
To: 'DobyTang/LazyLibrarian' <reply@reply.github.com>; 'DobyTang/LazyLibrarian' <LazyLibrarian@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [DobyTang/LazyLibrarian] Windows 10 UnicodeEncodeError (#1338)

 

Did the following.

1.	Removed Python 3.x
2.	Installed 2.7.14
3.	Deleted the LL database file
4.	Did NOT clear the cache
5.	Launched LL (see system info below)
6.	Ran same test as before.

See attached log files.

It still shows errors in the log file BUT the information actually updated.

 

 

 

Startup cmd: ['C:\\Python27\\python.exe', 'C:\\Users\\Waldemar Keyser\\Documents\\LazyLibrarian-master\\LazyLibrarian.py']

Interface: bookstrap

Loglevel: 2

Sys_Encoding: UTF-8

git_repo: lazylibrarian

git_user: dobytang

git_branch: master

latest_version: f1768e0728105ad662a5b0c395f66de76b75330a

git_updated: 1524120929

current_version: f1768e0728105ad662a5b0c395f66de76b75330a

commits_behind: 0

install_type: source

auto_update: 0

Python version: ['2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]']

Distribution: ('', '', '')

System: Windows

Machine: AMD64

Platform: Windows-10-10.0.16299

uname: ('Windows', 'Keyser', '10', '10.0.16299', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')

version: 10.0.16299

mac_ver: ('', ('', '', ''), '')

openssl: OpenSSL 1.0.2k  26 Jan 2017

requests: 2.12.4

sqlite3: 3.8.11

pyOpenSSL: module missing

OpenSSL missing module/attribute: No module named OpenSSL.SSL

**Comment by Iamacamel** [comment] 2018-04-20 12:37
Just some more feedback.

Massive difference in functionality going from phython 3xx back to python 2.7.14

Virtually everything now works.

I notice than in some cases the released date is 0000 , yet when I check on the actual goodreads site it shows a legitimate published date.

**Comment by philborman** [comment] 2018-04-20 13:59
Major differences in the python versions and the way they handle unicode. The python 3 version of lazylibrarian is fairly new, and works fine under Linux, but for some reason there are still issues under Windows. I really need to get a working Windows system here to try it on.

The zero dates issue is because goodreads api does not always include the date even if the main book page has it. We grab books by author (ask goodreads for a list of all the authors books) and extract the information from that. It means only a few api calls per author instead of calling for all the author pages and then an extra api call per book. Much quicker (we have to leave minimum one second between calls) and also there is a daily limit of 1000 calls, which you can easily exceed if you call once per book. 

Thanks for the feedback.

**Comment by Iamacamel** [comment] 2018-04-20 14:06
Thanks a lot.
A last question.
Before I get Google api key is Google info more accurate as far as
publishing date is concerned instead of goodreads ?

**Comment by philborman** [comment] 2018-04-20 21:35
pyOpenSSL: module missing
OpenSSL missing module/attribute: No module named OpenSSL.SSL

These are not important. GoodReads said they were going to force everyone to use https for their api starting from last December, but either they haven't done it yet, or we are managing without it. If it ever becomes a problem these modules will need to be installed.

**Comment by Iamacamel** [comment] 2018-04-21 06:52
Thanks.

I did a standard python install why would those be missing ?

 

I cleared the cache files , I cleared the library , I am rescanning library but now I get Ajax errors.

**Comment by philborman** [comment] 2018-04-21 07:02
Those modules are not part of a standard install, but at least at the moment they don't matter. I have removed the warning messages but left the checking code in place as they could become relevant at a later date.

The ajax messages unfortunately are not very informative. Alerts us to an issue, but not enough info to know what is wrong. They are related to the table filling data, so what page are you seeing them on, and what version of lazylibrarian as there was an update a few hours ago that may have broken something?

**Comment by Iamacamel** [comment] 2018-04-21 07:12
Ok.
It's when I click on an author.
Could this be related to the fact that library scan is still running ?
I will let it complete then restart LL and see what happens.

**Comment by philborman** [comment] 2018-04-21 07:36
Libraryscan should still work in the background, but null values could cause issues until updated.
Ajax error should be fixed now.

**Comment by philborman** [comment] 2018-04-21 17:50
Found and fixed an error with windows trying to log messages with accented characters under cp1252
but otherwise my windows installation seems to be working with python27 and python36
If you're feeling brave maybe retry it, or stick with python27, should be ok for a while. 
Python26 is end-of-life, but Python27 is scheduled for end-of-life in 2020

**Comment by Iamacamel** [comment] 2018-04-23 07:33
Sorry for the delay in reply. Was mountain biking on weekend.

I will stick with Python 2.7 until I have everything working.

Including Nzb etc

Then I will swop back so we have a baseline of what if anything stops working then.

**Comment by Iamacamel** [comment] 2018-04-23 14:08
Found a bug related to covers.

When goodreads displays no cover. (see attached screen shot 56)

Then LL picks up a stray cover (see attached screen shot 57). (no sure where it gets it from )

I have several examples of that and in each case it is no cover art (apart from the grown replacement) in goodreads.

**Comment by Iamacamel** [comment] 2018-04-24 06:27
Not sure why. See attached.

 

From: Waldemar Keyser <waldemar.keyser@gmail.com> 
Sent: Monday, 23 April 2018 4:08 PM
To: 'DobyTang/LazyLibrarian' <reply@reply.github.com>; 'DobyTang/LazyLibrarian' <LazyLibrarian@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: Cover art incorrect

 

Found a bug related to covers.

When goodreads displays no cover. (see attached screen shot 56)

Then LL picks up a stray cover (see attached screen shot 57). (no sure where it gets it from )

I have several examples of that and in each case it is no cover art (apart from the grown replacement) in goodreads.

**Comment by philborman** [comment] 2018-04-24 08:10
Your attachments are not showing up?
Do you want to try emailing me phil.borman@gmail.com

**Comment by philborman** [comment] 2018-05-06 18:48
Added some code to try and trap utf-16 and convert to utf-8, might fix the python3 windows issue.

**Comment by Iamacamel** [comment] 2018-05-08 09:34
BTW , I now have the following issue.

Running on Python 3.6

 

1.	I have tested the interface from LL to qbittorrent in LL (It passes)
2.	I have used jackett and tested the interface from LL to jacket to MAM (it passes)

 

When I do a test wanted I get the attached error message.

If you look at the log it appears as if all the MAM stuff is working but hand over to qbittorrent is an issue.

**Comment by philborman** [comment] 2018-05-08 09:43
Not seeing any attachments in github, no message or log?

**Comment by philborman** [comment] 2018-11-10 09:53
Development has moved to [GitLab](https://lazylibrarian.gitlab.io/)
All open issues have been moved over to [LazyLibrarian Issues](https://gitlab.com/LazyLibrarian/LazyLibrarian/issues)
Please open any new issues or comments on the new repo as the old one is no longer maintained, thanks

**Closed by philborman** 2018-11-10 09:53 UTC
Labels: help wanted
