### ISSUE TITLE
Search Doesn't want me to have Thomas Harris

### ISSUE THREAD

**Issue by warlord0** [DobyTang/LazyLibrarian#250] opened 2016-01-20 20:05 UTC
I can type in a few different search keywords for other authors etc. and get results. But when I use "Thomas Harris" I get the following. I can recreate it in both themes. I'm using the Google API for searching.

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/warlord/LazyLibrarian/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/home/warlord/LazyLibrarian/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/warlord/LazyLibrarian/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/warlord/LazyLibrarian/lazylibrarian/webServe.py", line 296, in search
    result['safeauthorname'] = urllib.quote_plus(common.remove_accents(result['authorname']))
  File "/usr/lib/python2.7/urllib.py", line 1299, in quote_plus
    s = quote(s, safe + ' ')
  File "/usr/lib/python2.7/urllib.py", line 1294, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u02b9'

Powered by CherryPy 3.2.0 
```

**Comment by philborman** [comment] 2016-01-20 20:59
ok, will look into that. Nothing immediately springs to mind. Hopefully I can reproduce it.

I have added safetitle to magazines, and safeissuefile to issues, if you would like to modify your mahazines.html and issues.html to suit ;-)

**Comment by philborman** [comment] 2016-01-20 21:06
Wow, that's a good one.
This is the list of results, it falls over on the last one...
VAN THOMAS HARRIS
Thomas Harris
Charles Thomas Harris
Thomas Harris
Thomas Harris Cherry
Charles Thomas Harris
John Thomas Harris
Thomas Harris
Thomas Harris
Thomas Harris
Thomas Harris
Thomas Harris
Thomas Harris
Michael Thomas Harris
Thomas Harris
Thomas Harris MacDonald
Thomas Harris
Gleb Vasīlʹevīch Anrep

so I need to figure out why the "strip_accents" code doesn't turn it into Gleb Vasil evich Anrep

**Comment by philborman** [comment] 2016-01-20 21:42
ok, fixed now. Small change to accent stripping code. Seems the character after the 'l' in Vasil wasn't stripped out, the rest were. I guess it's not really an accent.

**Comment by philborman** [comment] 2016-01-25 10:26
Hmm, something a bit strange
In the bookstrap themes the notifications settings get wiped. If I enable "pushbullet" and set a random value for api and save, it comes back as None. Or if I set pushbullet in the default theme, switch to bookstrap, then save it gets wiped. Works fine if I stay in default theme, only happens on Save from within bookstrap. 
Can't see anything obvious in the html

**Comment by warlord0** [comment] 2016-01-25 10:43
I sorted it. id="" does not equate to name="". So I added the name
attrib the same as id.

**Comment by philborman** [comment] 2016-01-25 11:30
Many thanks, thought it had to be something simple, just couldn't see it.

Another quick query looking at issues.html...
In a table, do I have to define <thead> before <tbody> ?
I'm looking at how the "covers" column is hidden if there aren't any 
covers to show.
At present I just check if the first issue has a cover, and enable the 
column if it has.
Would be better to check if _any_ issue has a cover rather than just 
checking one.
If I could define <tbody> first I could set a flag in the <tbody> for 
loop if I find a cover on any issue, and use the flag later in <thead> 
to show/hide, unless there's a better way?

**Comment by warlord0** [comment] 2016-01-25 12:04
thead will need to be before tbody.

You're probably best setting the column with a class of "hidden" and
then if you have a cover after processing all the table trigger a
javascript to remove the hidden class if there are covers.

<th class="cover hidden"></th>

and similarly

<td class="cover hidden"></td>

Then in the script you can just have

$().(function() {
    if (${covercount} > 0) {
        $('.cover').removeClass('hidden');
    }
});

Oh, add for default you may need a css entry in style.css

.hidden {
    display: none;
}

**Comment by philborman** [comment] 2016-01-25 15:35
Thanks for that, did it in the python side in the end.
I was already checking if each coverfile existed and putting a default 
in if not,
just added a counter there and pass it to the html

**Comment by philborman** [comment] 2016-01-25 19:14
A couple of buttons missing in the config page, alongside Shutdown, Restart, CheckVersion  there should be JobStatus and RestartJobs

and in the config providers tab there should be an "enable rss search" button, though it could be somewhere else. The enable tor/nzb buttons are on the download_settings tab, might be better there? 
It's used to show/hide the providers on the default interface, which isn't really necessary, but its also used to start/stop the rss search task, which is.

**Comment by warlord0** [comment] 2016-01-25 19:45
I deliberately hid those buttons as all they seemed to do was take me to
the log page.

Also added the missing enable rss onto the providers tab.

**Comment by philborman** [comment] 2016-01-25 19:52
They show and reset the status / next runtime of the various processing 
tasks, then take you to the log page to show you the results. A nice 
pop-up would be good, rather than taking you to the log page. I got a 
pop-up working for the notifier tests, but I couldn't figure out how to 
get it working on the config page and this way seems to be almost as 
good, you get the info.

Thanks for adding the rss button. The show/hide providers is a hangover 
from when I was developing it. A few releases had the code in there but 
hidden until a couple of users had tested it for me.

**Closed** 2016-01-25 21:05 UTC
