### ISSUE TITLE
Import Goodreads export

### ISSUE THREAD

**Issue by barbequesauce** [DobyTang/LazyLibrarian#840] opened 2017-06-11 13:00 UTC
Building on #835, can you implement an import based off of the Goodreads export function?

I would describe the use case to be that of someone getting started with LL, looking to import a substantial GR collection (shockingly, that's my case). Accordingly, it would be a one-time import with the RSS performing the role of keeping the list up to date over time...

**Comment by philborman** [comment] 2017-06-11 13:55
Lazylibrarian should already be able to do that. Export your goodreads list as a .csv file,which I think is the default anyway. Drop it into lazylibrarians "alternate import/export" folder (defined in lazylibrarians config->processing page). Once you've done that, on the lazylibrarian "manage" page is a button "import csv wishlist" that will import any .csv file in the alternate folder, no special filename needed ,just needs to end in .csv

**Comment by barbequesauce** [comment] 2017-06-12 14:21
How long does the import take?

I've had it going for about 25 minutes now and nothing new is showing up anywhere... and debug log doesn't show anything...

**Comment by philborman** [comment] 2017-06-12 14:36
Varies depending on whether the authors are already in the library or not. Should see progress in the debug log though...

12-Jun-2017 16:28:51 - DEBUG   :: IMPORTCSV : Reading file /media/Popcorn/temp/Wanted - 2017-06-12 16-28-35.csv
12-Jun-2017 16:28:51 - DEBUG   :: IMPORTCSV : CSV: Found 24 books in csv file
12-Jun-2017 16:28:51 - DEBUG   :: IMPORTCSV : CSV: Author Tom Holt found in database
12-Jun-2017 16:28:51 - INFO    :: IMPORTCSV : Found book The Management Style of the Supreme Beings by Tom Holt, already marked as "Wanted"
12-Jun-2017 16:28:51 - DEBUG   :: IMPORTCSV : CSV: Author Tom Holt found in database
12-Jun-2017 16:28:51 - INFO    :: IMPORTCSV : Found book Bitter Lemmings by Tom Holt, already marked as "Wanted"
12-Jun-2017 16:28:51 - DEBUG   :: IMPORTCSV : CSV: Author Mary Berry found in database
12-Jun-2017 16:28:51 - INFO    :: IMPORTCSV : Found book Mary Berrys Ultimate Cake Book by Mary Berry, already marked as "Wanted"
12-Jun-2017 16:28:51 - DEBUG   :: IMPORTCSV : CSV: Author W.E. Bowman found in database
12-Jun-2017 16:28:51 - INFO    :: IMPORTCSV : Found book The Cruise of the Talking Fish by W.E. Bowman, already marked as "Wanted"
12-Jun-2017 16:28:51 - DEBUG   :: IMPORTCSV : CSV: Author Mary Berry found in database
12-Jun-2017 16:28:51 - INFO    :: IMPORTCSV : Found book Foolproof Cooking by Mary Berry, already marked as "Wanted"
..........
12-Jun-2017 16:29:38 - INFO    :: IMPORTCSV : Added 0 new authors, marked 0 books as 'Wanted', 0 books not found

**Comment by barbequesauce** [comment] 2017-06-12 14:43
bah, VPN issue. Restarted PIA and now it's progressing.

That said - I got an error: 

2017-06-12 10:41:57	ERROR	Unhandled exception in importCSV: Traceback (most recent call last): File "/opt/LazyLibrarian/lazylibrarian/csvfile.py", line 191, in import_CSV searchterm = "%s %s" % (content[item]['Title'], formatAuthorName(authorname)) UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)

**Comment by philborman** [comment] 2017-06-12 15:45
Ah, I haven't looked at that code in a while. It didn't like an accented aurthorname. Jut pushed a fix, should be ok now. You can run the same import again, it will skip over the ones already done.

**Comment by barbequesauce** [comment] 2017-06-12 17:53
OK - getting there - 

I'm confused about the last message in the log after import, though:

> Added 55 new authors, marked 2 books as 'Wanted', 90 books not found

How could it have books not found if the data source was GoodReads?

**Comment by philborman** [comment] 2017-06-12 18:15
LL says it failed to find 90 books. It should have reported "Closest match x% y% author, title" 
for each failure. At the moment at a quick look I can't see how the code adds new authors to the database. It says it added 55 new authors, but did it?  The message "CSV: Author %s not found"  should be in your log 55 times. Can you see if any of those authors actually exist in your database?  I'm guessing that the 90 missing books are all by those 55 authors.

**Comment by barbequesauce** [comment] 2017-06-12 20:25
Just for giggles, I nuked all the books in the library and retried the exercise. I made sure that the Authors and eBooks screens had a count of zero before reimporting...

Results were the same - 

> Added 55 new authors, marked 2 books as 'Wanted', 90 books not found

What's interesting is that there seemed to be many duplicates/inconsistencies of "not found" - for example, I have all five Game of Thrones books in there, and it says (three times) that GRRM isn't in the database (screenshot below). Two books were found and populated in the database - but GRRM doesn't appear in the Author screen.

![capture](https://user-images.githubusercontent.com/25070944/27053351-07d9d972-4f8b-11e7-9cdf-2e22f20694c4.PNG)

**Comment by philborman** [comment] 2017-06-12 21:30
Grrm not in the authors screen is probably expected behaviour, I would have to check. Because the import list is a book list, not an author list, I think he should be added as an ignored author, ie you want a few books in the list but don't want to import his whole back catalog. Having said that, he should only be flagged missing once.
Seems although the csv import routine notices authors are missing,  it doesn't try to import them. Will take a look at it tomorrow.

**Comment by philborman** [comment] 2017-06-13 17:14
Added an option to list ignored authors, should make it easier to "unignore" them, and also show they got added properly. The idea is that when you import a book list you just want bare author details, not all their books.  Also improved the csv bookname matching as it was fairly basic.

**Closed** 2017-07-16 11:04 UTC
Labels: fixed
