### ISSUE TITLE
Library Scan produces error

### ISSUE THREAD

**Issue by nncrypted** [DobyTang/LazyLibrarian#281] opened 2016-02-02 23:49 UTC
ERROR	Unable to complete the scan: 'ascii' codec can't decode byte 0xe2 in position 31: ordinal not in range(128)

**Comment by philborman** [comment] 2016-02-03 09:16
Would be good to get to the bottom of this, I had another report of the same thing from TheGuardian a few months ago, but could never find it. It's hitting an accented character (in this case a small 'a' with circumflex) in a place where it shouldn't be. I made a few changes to the code and thought maybe we'd stopped it as I never got any more feedback. Seems it's still lurking there somewhere.

The accent is either on an author name or a book name, but not necessarily on a book you have in your library, could be you have the author, but not the book. Very difficult to find. Looking through the code I think all likely causes are trapped, but obviously one has slipped through. It isn't necessarily in libraryscan either, the support routines are in goodreads/googlebooks/common/formatter and other files, and the cause could be in there.
 
What was the last valid line in the log before the error, as it would narrow it down a bit, and if I still can't find it would you be averse to running a test version with lots more debugging messages in? I have a version here that prints debugging pretty much every line to try and find it, but can't reproduce it here.   

Thanks,
Phil

**Comment by philborman** [comment] 2016-02-03 11:26
Actually if we knew which author it was, and whether goodreads or googlebooks, i _should_ be able to reproduce it here. Might be simpler that way.

**Comment by nncrypted** [comment] 2016-02-03 12:02
Author is Nora Roberts and sure I'll run what ever version you want. Send me a link.

**Comment by philborman** [comment] 2016-02-03 13:06
Think it should be fixed now, please check :-)

**Closed** 2016-02-03 13:17 UTC
