### ISSUE TITLE
Torrents not being processed

### ISSUE THREAD

**Issue by stlouisn** [DobyTang/LazyLibrarian#892] opened 2017-07-02 13:12 UTC
To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
abf2bd864acd9c5ca29a2dccc99e7836167bc542

### Operating system used (windows, mac, linux, NAS type)
debian linux, docker (linuxserver)

### Interface in use (default, bookstrap)
default

### Which api (Goodreads, GoogleBooks, both)
goodreads

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
git

### Relevant debug log with api keys and any passwords redacted
2017-07-02 09:57:27	INFO	0 books/mags processed.
2017-07-02 09:57:27	DEBUG	Closest match (58%): /downloads/complete/librarian/Macworld_USA_July_2017.pdf
2017-07-02 09:57:27	DEBUG	Snatched torrent Macworld_USA_July_2017.pdf is not in download directory
2017-07-02 09:57:27	INFO	Looking for Magazine Macworld_USA_July_2017.pdf in /downloads/complete/librarian

user@hostname:/downloads/complete/librarian$ ls -R
Macworld_USA_July_2017.pdf

not sure why the match is so low, considering its a one for one match. i can force them to process by lowering the required match but that seems like the wrong solution...

**Comment by philborman** [comment] 2017-07-02 17:22
Fuzzy matching is a little wierd, I don't really understand how it works. I'm guessing maybe it's the underscores, perhaps treating the whole title as one huge word??
Can you try turning debug level up to 3 and send the postprocessor log from that. 
Also are you using torrent blackhole rather than directly communicating with the downloader, as I think if we talk to the downloaders we don't need to fuzzy match and get the name right almost always?

**Comment by stlouisn** [comment] 2017-07-03 17:24
i am not using blackhole. it is communicating directly with transmission.

librarian attempts to redownload it continously:

Title	ID	Provider	Date	Size	Status
PC_Gamer_USA_Issue_294_August_2017.pdf 	PC Gamer 	KAT 	2017-07-02 13:02:04 	37.97 MB 	Snatched
PC_Gamer_USA_Issue_294_August_2017.pdf 	PC Gamer 	KAT 	2017-07-02 19:02:13 	37.97 MB 	Snatched
PC_Gamer_USA_Issue_294_August_2017.pdf 	PC Gamer 	KAT 	2017-07-03 01:01:06 	37.97 MB 	Snatched
PC_Gamer_USA_Issue_294_August_2017.pdf 	PC Gamer 	KAT 	2017-07-03 07:01:05 	37.97 MB 	Snatched
PC_Gamer_USA_Issue_294_August_2017.pdf 	PC Gamer 	KAT 	2017-07-03 12:57:18 	37.97 MB 	Snatched

and transmission shows it has complete and still seeding.

**Comment by stlouisn** [comment] 2017-07-03 17:27
here are level 3 debug logs:

2017-07-03 14:25:36	DEBUG	Restart processDir job in 10 minutes
2017-07-03 14:25:36	DEBUG	Stop processDir job
2017-07-03 14:25:36	INFO	0 books/mags processed.
2017-07-03 14:25:36	DEBUG	Skipping (not LL) PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	DEBUG	Scanning 1 entries in /downloads/complete/librarian for LL.(num)
2017-07-03 14:25:36	DEBUG	Match: 34% /downloads/complete/librarian/PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	DEBUG	Closest match (34%): /downloads/complete/librarian/PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	DEBUG	Snatched torrent PC_Gamer_USA_Issue_294_August_2017.pdf is not in download directory
2017-07-03 14:25:36	DEBUG	34% match PC_Gamer_USA_Issue_294_August_2017.pdf : PC Gamer USA Issue 294 August 2017.pdf
2017-07-03 14:25:36	DEBUG	Checking extn on PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	INFO	Looking for Magazine PC_Gamer_USA_Issue_294_August_2017.pdf in /downloads/complete/librarian
2017-07-03 14:25:36	DEBUG	Requesting URL via POST method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:36	DEBUG	Requesting URL via GET method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:36	DEBUG	PC_Gamer_USA_Issue_294_August_2017.pdf was sent to TRANSMISSION
2017-07-03 14:25:36	DEBUG	Match: 34% /downloads/complete/librarian/PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	DEBUG	Closest match (34%): /downloads/complete/librarian/PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	DEBUG	Snatched torrent PC_Gamer_USA_Issue_294_August_2017.pdf is not in download directory
2017-07-03 14:25:36	DEBUG	34% match PC_Gamer_USA_Issue_294_August_2017.pdf : PC Gamer USA Issue 294 August 2017.pdf
2017-07-03 14:25:36	DEBUG	Checking extn on PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	INFO	Looking for Magazine PC_Gamer_USA_Issue_294_August_2017.pdf in /downloads/complete/librarian
2017-07-03 14:25:36	DEBUG	Requesting URL via POST method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:36	DEBUG	Requesting URL via GET method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:36	DEBUG	PC_Gamer_USA_Issue_294_August_2017.pdf was sent to TRANSMISSION
2017-07-03 14:25:36	DEBUG	Match: 34% /downloads/complete/librarian/PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	DEBUG	Closest match (34%): /downloads/complete/librarian/PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	DEBUG	Snatched torrent PC_Gamer_USA_Issue_294_August_2017.pdf is not in download directory
2017-07-03 14:25:36	DEBUG	34% match PC_Gamer_USA_Issue_294_August_2017.pdf : PC Gamer USA Issue 294 August 2017.pdf
2017-07-03 14:25:36	DEBUG	Checking extn on PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	INFO	Looking for Magazine PC_Gamer_USA_Issue_294_August_2017.pdf in /downloads/complete/librarian
2017-07-03 14:25:36	DEBUG	Requesting URL via POST method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:36	DEBUG	Requesting URL via GET method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:36	DEBUG	PC_Gamer_USA_Issue_294_August_2017.pdf was sent to TRANSMISSION
2017-07-03 14:25:36	DEBUG	Match: 34% /downloads/complete/librarian/PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	DEBUG	Closest match (34%): /downloads/complete/librarian/PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	DEBUG	Snatched torrent PC_Gamer_USA_Issue_294_August_2017.pdf is not in download directory
2017-07-03 14:25:36	DEBUG	34% match PC_Gamer_USA_Issue_294_August_2017.pdf : PC Gamer USA Issue 294 August 2017.pdf
2017-07-03 14:25:36	DEBUG	Checking extn on PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	INFO	Looking for Magazine PC_Gamer_USA_Issue_294_August_2017.pdf in /downloads/complete/librarian
2017-07-03 14:25:36	DEBUG	Requesting URL via POST method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:36	DEBUG	Requesting URL via GET method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:36	DEBUG	PC_Gamer_USA_Issue_294_August_2017.pdf was sent to TRANSMISSION
2017-07-03 14:25:36	DEBUG	Match: 34% /downloads/complete/librarian/PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	DEBUG	Closest match (34%): /downloads/complete/librarian/PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	DEBUG	Snatched torrent PC_Gamer_USA_Issue_294_August_2017.pdf is not in download directory
2017-07-03 14:25:36	DEBUG	34% match PC_Gamer_USA_Issue_294_August_2017.pdf : PC Gamer USA Issue 294 August 2017.pdf
2017-07-03 14:25:36	DEBUG	Checking extn on PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	INFO	Looking for Magazine PC_Gamer_USA_Issue_294_August_2017.pdf in /downloads/complete/librarian
2017-07-03 14:25:36	DEBUG	Requesting URL via POST method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:36	DEBUG	Requesting URL via GET method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:36	DEBUG	PC_Gamer_USA_Issue_294_August_2017.pdf was sent to TRANSMISSION
2017-07-03 14:25:36	DEBUG	Match: 19% /downloads/complete/librarian/PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	DEBUG	Closest match (19%): /downloads/complete/librarian/PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	DEBUG	Snatched torrent Megan McDonald - Judy Moody LL.(930612) is not in download directory
2017-07-03 14:25:36	DEBUG	19% match Megan McDonald - Judy Moody : PC Gamer USA Issue 294 August 2017.pdf
2017-07-03 14:25:36	DEBUG	Checking extn on PC_Gamer_USA_Issue_294_August_2017.pdf
2017-07-03 14:25:36	INFO	Looking for eBook Megan McDonald - Judy Moody LL.(930612) in /downloads/complete/librarian
2017-07-03 14:25:36	DEBUG	Requesting URL via POST method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:36	DEBUG	Requesting URL via GET method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:31	DEBUG	Requesting URL via POST method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:31	DEBUG	Requesting URL via GET method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:26	DEBUG	Requesting URL via POST method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:26	DEBUG	Requesting URL via GET method: http://192.168.101.101:9091/transmission/rpc
2017-07-03 14:25:26	DEBUG	Megan McDonald - Judy Moody LL.(930612) was sent to TRANSMISSION
2017-07-03 14:25:26	DEBUG	Found 6 files marked "Snatched"

**Comment by stlouisn** [comment] 2017-07-03 17:32
as you can see Macworld_USA_July_2017.pdf was imported, but only after I lowered the match req to < 58%

it should have been a 100% match as it is exactly what it is looking for

**Comment by philborman** [comment] 2017-07-03 17:45
Yes, looks like the problem is trying to match words_with_underscores against words with spaces and getting a very low percentage. LL then assumes download failed and retries it.  I will add add a fix shortly and push a new version.

**Comment by stlouisn** [comment] 2017-07-04 17:37
could it be related to:

Current limitation: If inside book folder, magazine folder must start with _

**Comment by philborman** [comment] 2017-07-04 22:22
At this point in the code we are just trying to match the filename against the title we need, not looking at where its going to be stored. I think it is probably fixed in the latest release, seems to be working ok here. Latest version replaces all underscores with spaces before trying to match the names. Books are easier as we use the goodreads or googlebooks id to compare to, but magazines don't have anything similar, just the title.

**Comment by stlouisn** [comment] 2017-07-04 23:24
When I logged in today it was processed, I think it is fixed, it will keep an eye out for the next few that I try. Thank you

On Jul 4, 2017 7:22 PM, philborman <notifications@github.com> wrote:

At this point in the code we are just trying to match the filename against the title we need, not looking at where its going to be stored. I think it is probably fixed in the latest release, seems to be working ok here. Latest version replaces all underscores with spaces before trying to match the names. Books are easier as we use the goodreads or googlebooks id to compare to, but magazines don't have anything similar, just the title.

**Closed** 2017-07-05 06:14 UTC
