### ISSUE TITLE
Add qBittorrent support

### ISSUE THREAD

**Issue by arogl** [DobyTang/LazyLibrarian#278] opened 2016-01-31 04:48 UTC
Would you consider adding qBittorrent support?

This downloader now has a web interface and label support. a la uTorrent.

Downloader and details located here http://www.qbittorrent.org/

**Comment by philborman** [comment] 2016-02-01 20:07
I have added some qbittorrent code to lazylibrarian that looks like it should work, but can't test it.
Some kind soul has added qbittorrent support to headphones recently, so I've based it on that.
I tried installing qbittorrent on my linux box, and although i am talking to the server I just get an error back: QBitTorrent returned fatal error: could not select database! Check your config.

I can't see anything in the qbittorrent config about a database though, except geoip and i gave turned that off, so I'm a bit stuck.

**Comment by arogl** [comment] 2016-02-02 00:32
@philborman 
I can test this tonight AEST for you.

**Comment by philborman** [comment] 2016-02-02 09:18
That would be good.

The test version is at https://github.com/philborman/LazyLibrarian.git
I will push it into main version if it works.
I managed to email the guy who added it to headphones, it's in the development branch there and he's only run it on qbittorrent 3.4 which I can't find for ubuntu linux, only 3.3.1 in both stable and unstable repos. I'm fairly sure the problem is my qbittorrent server rather than lazylibrarian

**Comment by arogl** [comment] 2016-02-02 09:55
I have just tested and I can add torrents successfully under windows qbittorrent v3.3.3.

If I force a post process I get the following:

    Exception in thread POSTPROCESS:
    Traceback (most recent call last):
      File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
        self.run()
      File "C:\Python27\lib\threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "F:\Git\Philborman-LazyLibrarian\LazyLibrarian\lazylibrarian\postprocess.py", line 68, in processDir
        if not DOWNLOAD_DIR or not os.path.isdir(DOWNLOAD_DIR):
    NameError: global name 'DOWNLOAD_DIR' is not defined

However a grep of config.ini shows:

    F:\Git\Philborman-LazyLibrarian\LazyLibrarian>grep -i download_dir config.ini
    download_dir = F:\EBook_down

The download directory has the file as follows:

02/02/2016  07:44 PM    <DIR>          .
02/02/2016  07:44 PM    <DIR>          ..
02/02/2016  07:44 PM           192,367 Bloodlust - Shannon West.epub

MIght be combining 2 or 3 issues here.

**Comment by philborman** [comment] 2016-02-02 12:08
yes you are right, separate issue, fixed now.
Good to know the torrents work. I just need to find out what's wrong with my qbittorrent config then. :-)

Thanks for testing

**Closed** 2016-02-02 14:10 UTC
