### ISSUE TITLE
nzbhydra - error message from LazyLibrarian

### ISSUE THREAD

**Issue by Hobbabobba** [DobyTang/LazyLibrarian#307] opened 2016-03-05 09:39 UTC
When I use nzbhydra as indexer, I get an error 500 message. I tried both settings, for nZEDb and newznab+.

**Comment by nncrypted** [comment] 2016-03-05 16:46
beware that nzbhydra doesn't support ebooks. I get 403 errors on my setup using nzbhydra

**Comment by philborman** [comment] 2016-03-05 16:47
Haven't used nzbhydra, can you post the error message and a section of log file?
I had a quick look at the git page for nzbhydra and it looks like it does both nZEDb and newznab+, no idea how as they use different category numbers and search types.

**Comment by Hobbabobba** [comment] 2016-03-05 17:21
Here is one example:
```
2016-03-05 18:17:41	DEBUG	[NewzNabPlus] - nzb Search parameters set to {'q': 'Stephen Edger Snatched', 'apikey': u'xxxxxxxx', 't': 'search', 'extended': 1}
2016-03-05 18:17:41	DEBUG	[NewzNabPlus] searchType [general] with Host [https://www.example.com] mode [nzb] using api [xxxxxx] for item [{'searchterm': 'Stephen Edger Snatched', 'bookName': u'Snatched', 'authorName': u'Stephen Edger', 'bookid': u'JmnEnQEACAAJ'}]
2016-03-05 18:17:41	DEBUG	[IterateOverNewzNabSites] - Newznab1
2016-03-05 18:17:41	DEBUG	No nzb's found for Stephen Edger Snatched using searchtype book
2016-03-05 18:17:41	DEBUG	No data returned from https://www.example.com for Stephen Edger Snatched
2016-03-05 18:17:41	ERROR	Error 403 opening url HTTP Error 500: INTERNAL SERVER ERROR
2016-03-05 18:17:41	DEBUG	[NewzNabPlus] - nzb Search parameters set to {'author': u'Stephen Edger', 'apikey': u'xxxx', 't': 'book', 'cat': '7020', 'title': u'Snatched'}
2016-03-05 18:17:41	DEBUG	[NewzNabPlus] searchType [book] with Host [https://www.example.com] mode [nzb] using api [xxxx] for item [{'searchterm': 'Stephen Edger Snatched', 'bookName': u'Snatched', 'authorName': u'Stephen Edger', 'bookid': u'JmnEnQEACAAJ'}]
2016-03-05 18:17:41	DEBUG	[IterateOverNewzNabSites] - Newznab1
2016-03-05 18:17:41	INFO	NZB Searching for one book
```

**Comment by philborman** [comment] 2016-03-05 17:27
ok, so we get a "forbidden" error, 403, from nzbhydra because it has an internal server error caused by our api parameters. I think I need some API documentation for the nzbhydra interface, maybe talk to the developer. Also they need to fix their internal server error and report a better error message to us ;-)

**Comment by Hobbabobba** [comment] 2016-03-05 17:50
Ok, after i changed the provider type to "nZEDb" it can find a nzb. When LL tries to get the nzb, it doesn´t work:

``
2016-03-05 18:45:05	DEBUG	Requesting URL via GET method: https://www.example.com/getnzb?apikey=xxxxxxxb&id=(indexer:hp_nzedb,indexerguid:xxxxxx,searchid:30591,title:'examplebook+(retail)+(epub)')

2016-03-05 18:45:05	DEBUG	Found NZB: xxxx (retail) (epub) using book search
``

When I mark and copy the part `https://www.example.com/getnzb?apikey=xxxxxxxb&id=(indexer:hp_nzedb,indexerguid:xxxxxx,searchid:30591,title:'examplebook+(retail)+(epub)')` my browser downloads the correct nzb.

**Comment by philborman** [comment] 2016-03-05 18:00
When LL tries to get the nzb, it doesn´t work:

Can you post the log for this bit "it doesn't work" doesn't give me enough to go on...

**Comment by Hobbabobba** [comment] 2016-03-05 18:04
After this line
```
2016-03-05 18:45:05 DEBUG   Requesting URL via GET method: https://www.example.com/getnzb?apikey=xxxxxxxb&id=(indexer:hp_nzedb,indexerguid:xxxxxx,searchid:30591,title:'examplebook+(retail)+(epub)')
```
there is no other line in the log-file. Looks like LL tries go download the nzbfile, but nothing happens.

**Comment by philborman** [comment] 2016-03-05 18:38
Looks like we still aren't talking to the server correctly, we are sending a request but not getting a reply?

**Comment by philborman** [comment] 2016-03-05 18:45
ok, just had a reply from the nzbhydra dev. He says we should be using newznab+ format queries, but he hasn't implemented book search yet. Hopes to do so in the next couple of days. I suggest we wait for the nzbhydra update and then have another look if still not working.

**Comment by theotherp** [comment] 2016-03-06 09:13
Your code might have some troubles handling the NZB link format. Mylar had a similar problem until recently, it's now fixed. See https://github.com/evilhero/mylar/issues/1222

While I'm currently implementing book searches that won't help with the downloading of the actual NZB, that's your call.

**Comment by philborman** [comment] 2016-03-06 09:21
Ah yes, we will fall foul of that too. Easy fix for me though. We already have to parse results to strip extra stuff KAT includes in it's response.

**Comment by theotherp** [comment] 2016-03-06 09:23
Alright, seems like we'll get this all fixed soon :-)

**Comment by nigelhooper** [comment] 2016-03-06 20:28
I have updated LL and NZBHydra but I am still getting a (different) error.  LL works with a different Newznab provider, hydra works fine from Sonarr.  Here is an extract from my Log with API key and domain redacted:

2016-03-06 20:12:12	DEBUG	[NewzNabPlus] - nzb Search parameters set to {'q': 'Abhijit V Banerjee Poor Economics', 'apikey': u'___ApiKeyRemoved______', 't': 'search', 'extended': 1}
2016-03-06 20:12:12	DEBUG	[NewzNabPlus] searchType [general] with Host [www.mydomain.tld:5075/] mode [nzb] using api [___ApiKeyRemoved______] for item [{'searchterm': 'Abhijit V Banerjee Poor Economics', 'bookName': u'Poor Economics', 'authorName': u'Abhijit V. Banerjee', 'bookid': u'1Xh7qOGbkZ4C'}]
2016-03-06 20:12:12	DEBUG	[IterateOverNewzNabSites] - Newznab0
2016-03-06 20:12:12	DEBUG	No nzb's found for Abhijit V. Banerjee Poor Economics using searchtype book
2016-03-06 20:12:12	DEBUG	No data returned from http://www.mydomain.tld:5075/ for Abhijit V Banerjee Poor Economics
2016-03-06 20:12:12	ERROR	Error 403 opening url
2016-03-06 20:12:12	DEBUG	[NewzNabPlus] - nzb Search parameters set to {'author': u'Abhijit V Banerjee', 'apikey': u'___ApiKeyRemoved______', 't': 'book', 'cat': '7020', 'title': u'Poor Economics'}
2016-03-06 20:12:12	DEBUG	[NewzNabPlus] searchType [book] with Host [www.mydomain.tld:5075/] mode [nzb] using api [___ApiKeyRemoved______] for item [{'searchterm': 'Abhijit V Banerjee Poor Economics', 'bookName': u'Poor Economics', 'authorName': u'Abhijit V. Banerjee', 'bookid': u'1Xh7qOGbkZ4C'}]
2016-03-06 20:12:12	DEBUG	[IterateOverNewzNabSites] - Newznab0
2016-03-06 20:12:12	INFO	NZB Searching for one book
2016-03-06 20:12:12	DEBUG	Searching for book with id: 1Xh7qOGbkZ4C
2016-03-06 20:12:09	INFO	Opening file /mnt/eBooks/ByAuthor/Abhijit Banerjee/Poor Economics/Abhijit Banerjee - Poor Economics.epub
2016-03-06 20:11:59	INFO	Debug log display ON, loglevel is 2

**Comment by philborman** [comment] 2016-03-06 20:39
Still working on LL auto-detecting nZEDb vs newznab+
I have set up a NZBHydra server here to try once the capability parsing 
code is completed.

May have something by tomorrow.

**Comment by philborman** [comment] 2016-03-06 22:10
On the error line below, is there nothing after the "opening url" ?
I think it should report the url and an error message

2016-03-06 20:12:12 ERROR Error 403 opening url
2016-03-06 20:12:12 DEBUG [NewzNabPlus] - nzb Search parameters set to {'author': u'Abhijit V Banerjee', 'apikey': u'ApiKeyRemoved___', 't': 'book', 'cat': '7020', 'title': u'Poor Economics'}

**Comment by Hobbabobba** [comment] 2016-03-07 12:14
short update: after the new version of hydra, there is no more error message. after the GET Command, still nothing happens.

**Comment by philborman** [comment] 2016-03-07 15:24
ok, think I've found it.
In your LL config for nzbget, your host needs to include a port number, eg 127.0.0.1:6789
not just a host. It's not clear. The sabnzb config has separate entries for host and port which makes it obvious, I will put separate entries for nzbget host and port in the next version. Probably later today.
You can check it in the meantime by adding the nzbget port in the host details. Let me know if this doesn't fix it. Didn't have the problem here as I use sabnzb, but the error message you were getting is nzbget specific.

**Comment by theotherp** [comment] 2016-03-07 15:58
Glad to know it's not my fault for once :-D

**Comment by Hobbabobba** [comment] 2016-03-07 16:27
I set the host for nzbget to 

> 192.168.0.7:6789 

and it works with any other indexer. Just nzbhydra doesn´t get the nzb-file.

**Comment by philborman** [comment] 2016-03-07 17:23
Sorry, can't reproduce it here at all, but I got the same symptoms from not having a port in the nzbget config (nothing printed after the GET message). 

The nzbsearch thread is run separately from the main program and is crashing after the GET message. Any chance you can run LL from a terminal? If so you should see a debug trace from the nzbsearch thread. Might tell us where to look.

**Comment by Hobbabobba** [comment] 2016-03-07 18:11
Sorry, have it running inside of a docker container (or as a synology package, but it shows the same problem). Very strange: when i use the black hole to get the nzb to nzbget, LL will download the nzb and write it into the black hole folder. just nzbget won´t import it. I tried to set the permissions right, but no success.

**Comment by Hobbabobba** [comment] 2016-03-07 18:37
```
Logged from file logger.py, line 66
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 468, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
Logged from file logger.py, line 66
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 853, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 468, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
Logged from file logger.py, line 66
Exception in thread SEARCHNZBBOOKS:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/LazyLibrarian/lazylibrarian/searchnzb.py", line 84, in search_nzb_book
    found = processResultList(resultlist, book, "book")
  File "/opt/LazyLibrarian/lazylibrarian/searchnzb.py", line 180, in processResultList
    snatch = NZBDownloadMethod(bookid, nzbprov, nzbTitle, nzburl)
  File "/opt/LazyLibrarian/lazylibrarian/searchnzb.py", line 198, in NZBDownloadMethod
    data = request.request_content(url=nzburl, headers=headers)
  File "/opt/LazyLibrarian/lazylibrarian/request.py", line 176, in request_content
    response = request_response(url, **kwargs)
  File "/opt/LazyLibrarian/lazylibrarian/request.py", line 78, in request_response
    if kwargs["verify"]:
KeyError: 'verify'
```
does this help? otherwise, what kind of information do you need, and how i can get it?

**Comment by philborman** [comment] 2016-03-07 19:06
Yes, that's it thanks. Well, a start anyway...

We are hitting an SSL  error talking to nzbhydra, and don't have the 
code to handle the error.
If we suppress the faulty code we can at least get at the error message 
which might help.
Alternatively can you try using nzbhydra without ssl just to make sure 
it works without?

There's also a separate unicode decode logger error cropping up which 
isn't fatal.

**Comment by Hobbabobba** [comment] 2016-03-07 19:17
I tried without SSL and it works like a charm!

**Closed** 2016-03-07 22:16 UTC
