### ISSUE TITLE
No theme error

### ISSUE THREAD

**Issue by perezbalen** [DobyTang/LazyLibrarian#457] opened 2016-09-07 00:01 UTC
hi

I changed the theme (using an ipad, which apparently lets me do things I'm not suposed to)

And now i get this (and cant access the interface):

Error !

TopLevelLookupException: Cant locate template for uri 'index.html'

return self._load(srcfile, uri) else: raise exceptions.TopLevelLookupException( "Cant locate template for uri %r" % uri) def adjust_uri(self, uri, relativeto): """Adjust the given ``uri`` based on the given relative URI.""" key = (uri, relativeto)
/Applications/LazyLibrarian/mako/lookup.py, line 259:
"Cant locate template for uri %r" % uri)
/Applications/LazyLibrarian/lazylibrarian/webServe.py, line 45:
template = _hplookup.get_template(templatename)

**Comment by philborman** [comment] 2016-09-07 11:03
hmm, sounds like your config.ini has an invalid theme name?  I will have to add some code to trap this.
If you have a look at your config.ini file, in the "General" section put http_look = default
That should get you working again, just need to figure out how it broke so we can stop it!

**Comment by perezbalen** [comment] 2016-09-07 13:21
Thanks. 
I tried it, but now it wont start. 
My guess is that on OS X, the config.ini on the install dir (Applications folder) is not the one that's used ( http_look was empty ). Is there a path to a different workdir (like Library/Application Support)?

**Comment by philborman** [comment] 2016-09-07 14:01
on linux it's config.ini in a hidden directory in the users home folder, ie /home/phil/.lazylibrarian/config.ini
Should be the same folder as the lazylibrarian database
http_look should never be empty, should only contain default or bookstrap

**Comment by perezbalen** [comment] 2016-09-07 14:32
Can't find it

Lazylibrarian.db was modified recently on Aplications/LazyLibrarian, where the suspicious config.ini is. Chenching that config.ini I find it has the default port (not my custom port) and a lot of empty fields (likr no api_key) so my guess is that either the .lazylibrarian is somewere else on osx, or that the program re-wrote the config.ini to it's default values.

**Comment by philborman** [comment] 2016-09-07 15:42
Looks like the config.ini is the right one, but probably corrupted somehow.
If you rename it to something else (or delete it), lazylibrarian will
create a new one with default values.

Maybe the best solution is to do that, and then re-enter your settings.
Would explain why it's not starting - it probably is actually starting, but
on the wrong port.

**Comment by perezbalen** [comment] 2016-09-08 02:01
It seems so. I deleted the old file and it loaded again. I'm now trying to remember all the previous settings. 

As far as I can tell, the error happened when changing the theme form bootstrao (superhero) to default.

**Comment by philborman** [comment] 2016-09-08 11:58
Something to do with writing out the config file? Look like LazyLibrarian for some reason reverted to default settings. Can't see why without more info. Perhaps keep a copy of your config.ini once it's set correctly, and see if you can reproduce the error?

**Comment by perezbalen** [comment] 2016-09-11 15:17
Haven´t been able to reproduce it (maybe a recent update fixed it?) 

So far, When I go to config on a desktop browser, i can choose the theme bootstrap, with sub-teme superhero. 

When I go to config on the ipad/Safari, SOMETIMES the bootstrap sub-theme is blank. If I save any settings, the theme changes to a white one (no sure which sub theme, as ti changes again to cerulean). I haven't been able to figure out what triggers this behavior.

**Comment by philborman** [comment] 2016-09-11 16:19
The odd thing is that the theme details are kept on the desktop machine
that is running lazylibrarian, not on the ipad/phone or whatever is used to
access lazylibrarian. Same with the config settings. When you save
settings, it saves whatever is running on the desktop, nothing from the
ipad. The ipad is just a screen and keyboard, the program and all data are
kept on the desktop.

When the desktop first fires up lazylibrarian, it grabs a list of themes
from the bookstrap site and keeps a copy of the theme names. Only the
names. Needs internet access for this or you get a default white-ish theme.
If you have debug log enabled you should get a message saying how many
themes it found. Whenever you change theme LL downloads the new theme from
the bookstrap site, or defaults back to the white-ish default theme if it
can't download the new one for any reason.

Anything in the debug log that might help?

**Comment by philborman** [comment] 2016-09-21 19:10
Just a thought - are you using a reverse proxy with a webroot?
I am trying to debug a problem with webroot for another user, and had my config file trashed during testing. I have added extra code to keep a backup of the config.ini in case it happens again, but wondered if this might be the same bug you hit?  It looks as though the config file does not always get written out properly during a reboot if webroot is in use.

**Comment by perezbalen** [comment] 2016-09-21 19:15
I don't think so.

Atentamente:

José Rafael Pérez Balen
*perezbalen@gmail.com <perezbalen@gmail.com>*

**Comment by philborman** [comment] 2016-09-24 19:18
Changed the code that writes out the config file so it keeps a backup. Should fix the problem. My guess is that on a change of web interface we hadn't flushed the file to disc before restarting. I will close this ticket for now but feel free to reopen it if it should happen again.

**Closed by philborman** 2016-09-24 19:18 UTC
